import AsyncStorage from "@react-native-async-storage/async-storage";
import React, { createContext, useCallback, useContext, useEffect, useState } from "react";

export type Language = "ta" | "te" | "kn" | "ml" | "hi" | "en";

export const LANGUAGE_NAMES: Record<Language, string> = {
  ta: "தமிழ்",
  te: "తెలుగు",
  kn: "ಕನ್ನಡ",
  ml: "മലയാളം",
  hi: "हिंदी",
  en: "English",
};

export const LANGUAGE_NATIVE: Record<Language, { name: string; flag: string; english: string }> = {
  ta: { name: "தமிழ்", flag: "🏛️", english: "Tamil" },
  te: { name: "తెలుగు", flag: "🌺", english: "Telugu" },
  kn: { name: "ಕನ್ನಡ", flag: "🌿", english: "Kannada" },
  ml: { name: "മലയാളം", flag: "🌴", english: "Malayalam" },
  hi: { name: "हिंदी", flag: "🇮🇳", english: "Hindi" },
  en: { name: "English", flag: "🔤", english: "English" },
};

const base = {
  appName: "ThulirFarm",
  tagline: "Your Farm, In Your Hands",
  tabAnimals: "My Animals", tabDashboard: "Dashboard", tabHelp: "Help", tabMoney: "Money", tabToday: "Today",
  animals: "Animals", addAnimal: "Add Animal", noAnimals: "No Animals",
  noAnimalsHint: "Tap + to add your first animal", searchPlaceholder: "Search by name or tag...",
  filterAll: "All", filterCow: "Cow", filterBuffalo: "Buffalo",
  filterHealthy: "Healthy", filterAttention: "Attention", filterCritical: "Critical",
  milkLog: "Log Milk", milkLogSuccess: "Milk logged!", milkToday: "Today's Milk",
  milkLogTitle: "Log Milk Entry", session: "Session", morning: "Morning", evening: "Evening",
  quantity: "Quantity (Litres)", fatPercentage: "Fat % (optional)", save: "Save", cancel: "Cancel",
  health: "Health", healthy: "Healthy", attention: "Needs Attention", critical: "Critical",
  income: "Income", expense: "Expense", profit: "Profit", loss: "Loss",
  totalIncome: "Total Income", totalExpense: "Total Expense",
  addIncome: "Add Income", addExpense: "Add Expense",
  today: "Today", goodMorning: "Good Morning, Farmer!", goodAfternoon: "Good Afternoon",
  goodEvening: "Good Evening", goodNight: "Good Night, Farmer!",
  tasks: "Tasks", allTasksDone: "All tasks done!", progress: "Today's Progress",
  help: "Problems & Help", sosButton: "Something Wrong?", sosSub: "Tap to call for emergency",
  symptoms: "Select Symptoms", diagnose: "Get AI Advice", diagnosing: "AI analyzing...",
  emergency: "Emergency Contacts", callVet: "Call Vet Immediately", speak: "Listen", stop: "Stop",
  profile: "My Profile", farmerName: "Farmer Name", village: "Village", district: "District",
  phone: "Phone Number", totalAnimals: "Total Animals", language: "Language",
  logout: "Log Out", editProfile: "Edit", saveProfile: "Save Profile",
  login: "Login", signup: "Sign Up",
  loginTitle: "Welcome to ThulirFarm", loginSub: "Enter your mobile number",
  signupTitle: "Complete Your Profile", signupSub: "Tell us about yourself",
  sendOtp: "Send OTP",
  verifyOtp: "Verify OTP",
  otpSentTo: "OTP sent to",
  enterOtp: "Enter 6-digit OTP",
  resendOtp: "Resend OTP",
  resendIn: "Resend in",
  seconds: "sec",
  otpExpiry: "OTP valid for 5 minutes",
  wrongOtp: "Incorrect OTP",
  otpVerified: "Verified!",
  namePlaceholder: "Your name (e.g. Murugan)",
  villagePlaceholder: "Village name",
  districtPlaceholder: "District",
  phonePlaceholder: "10-digit mobile number",
  farmNamePlaceholder: "Your farm's name (optional)",
  noAccount: "New to ThulirFarm?",
  haveAccount: "Already registered?",
  createAccount: "Create account",
  skip: "Skip for now",
  continueBtn: "Continue",
  required: "This field is required",
  invalidPhone: "Enter a valid 10-digit mobile number",
  success: "Success", error: "Error", networkError: "Network error",
  sync: "Saved", syncing: "Saving...", offline: "Offline",
  voice: "Voice", voiceTitle: "Voice Command", voiceSub: "Speak in English",
  voiceHint: "Press the button to start", listening: "Listening...", processing: "Processing...",
  sampleCommands: "Sample Commands", speakAgain: "Speak Again",
  voicePlaceholder: "Type command...",
  voiceStatusRecording: "🎙 Listening... (press again to stop)",
  voiceStatusProcessing: "⚡ Processing...",
  voiceStatusError: "⚠ Please try again",
  voiceNoMatch: "Voice not heard clearly. Please type text.",
  voiceNotUnderstood: "Could not understand. \"{text}\" — please try again",
  voiceMicPermission: "Please grant microphone access",
  voiceNavLabel: "Navigation",
  voiceSampleMilk: "Lakshmi 5 liters morning",
  voiceSampleHealth: "Rani fever",
  voiceSampleExpense: "Feed expense 500",
  voiceSampleNav: "Go to finance page",
  settingsTitle: "Settings", notifications: "Notifications",
  notifEnabled: "Notifications enabled", enableNotif: "Enable reminders",
  demoOtpNote: "Demo OTP (testing only)",
  newUser: "New farmer? Create profile",
  existingUser: "Already a member? Log in",
  welcomeBack: "Welcome back",
  step1of3: "Step 1/3", step2of3: "Step 2/3", step3of3: "Step 3/3",
  verifying: "Verifying...",
  sending: "Sending...",

  // ── Animals sub-tabs ──
  herdTab: "Herd",
  breedingTab: "Breeding",
  vaccinesTab: "Vaccines",
  myAnimalsTitle: "My Animals",
  animalsCountSuffix: "animals",

  // ── Breeding ──
  breedingMgmt: "Reproductive Management",
  logEvent: "Log Event",
  noEvents: "No events recorded",
  pregnantLabel: "Pregnant",
  calvingExpected: "Expected calving:",
  daysAgoSuffix: "d ago",
  overdueLabel: "overdue",
  daysLabel: "days",
  addAnimalsFirst: "Add animals to track breeding",

  // ── Vaccination ──
  vaccinationSchedule: "Vaccination Schedule",
  upcomingOverdue: "⏰ Upcoming / Overdue",
  recentlyAdministered: "✅ Recently Administered",
  noUpcomingVaccines: "No upcoming vaccinations",
  scheduleVaccineBtn: "+ Schedule a Vaccination",
  scheduledDateLabel: "Scheduled:",
  givenDateLabel: "Given:",
  nextDueLabel: "Next due:",
  markDoneBtn: "Done",
  vaccineMarkTitle: "Mark as Administered?",
  vaccineMarkBody: "Record as given today?",
  yes: "Yes",

  // ── Smart Alerts ──
  todayAlerts: "Today's Alerts",
  urgentLabel: "URGENT",
  highLabel: "HIGH",
  milkDropAlert: "Milk Drop Alert",
  milkDropSuffix: "drop",
  todayPrefix: "Today:",
  avgPrefix: "Avg:",

  // ── Help sub-tabs ──
  diagnoseTab: "Diagnose",
  gauguruTab: "GauGuru AI",
  emergencyTab: "Emergency",
  helpTitle: "Help & Advice",
  aiDairyAssistant: "AI Dairy Assistant",
  whichAnimal: "Which animal? (optional)",
  additionalNotes: "Additional notes... (optional)",
  callNow: "Call Now!",
  firstAidTips: "First Aid Tips",
  emergencySosBtn: "Emergency?",
  emergencySosSub: "Tap to call vet",
  quickQuestions: "⚡ Quick Questions",

  // ── GauGuru ──
  gauguruSubtitle: "24/7 Dairy Advisor",
  chatPlaceholder: "Ask GauGuru...",
  clearChat: "Clear",
  thinking: "Thinking...",
  errorMsg: "Sorry, an error occurred. Please try again.",

  // ── Money / Inventory ──
  financeTitle: "Finances",
  incomeTab: "Income",
  expenseTab: "Expenses",
  inventoryTab: "Inventory",
  sevenDayFinancials: "7-Day Financials",
  totalInventoryValue: "Total Inventory Value",
  lowStockItems: "items low on stock",
  noInventory: "No inventory items yet",
  addFirstItem: "+ Add First Item",
  deleteConfirmTitle: "Delete?",
  deleteConfirmBtn: "Delete",
  deleteItemBodyPrefix: "Delete",

  // ── Today ──
  herdStatus: "Herd Status",
  morningTasks: "Morning Tasks",
  eveningTasks: "Evening Tasks",
  loadingTasks: "Loading tasks...",
  reminders: "Reminders",
  remindersSet: "Reminders set!",
  savedLabel: "Saved",
  savingLabel: "Saving...",
  expenseBreakdown: "Expense Breakdown",

  // ── Animal Detail screen ──
  animalDetailHealth: "Health Status",
  animalDetailMilkLog: "Log Milk",
  animalDetailHealthNote: "Health Note",
  animalDetailMilkHistory: "7-Day Milk History",
  animalDetailHealthHistory: "Health History",
  animalDetailRecentMilk: "Recent Milk Entries",
  animalDetailNoNotes: "No notes — tap 'Health Note' above",
  animalDetailNoMilk: "No entries",
  animalDetailTagPrefix: "Tag: #",
  animalDetailDeleteTitle: "Delete Animal",
  animalDetailDeleteBody: "Delete {name}?",
  animalDetailDeleteConfirm: "Delete",
  animalDetailDeleteCancel: "No",
  animalDetailPhotoTitle: "Take Photo",
  animalDetailPhotoBody: "Take a photo or choose from gallery",
  animalDetailCamera: "📷 Camera",
  animalDetailGallery: "🖼 Gallery",
  animalDetailPermissionNeeded: "Permission Required",
  animalDetailCameraPermission: "Please grant camera access",
  animalDetailGalleryPermission: "Please grant gallery access",
  animalDetailNotFound: "Animal not found",
  animalDetailGoBack: "Go Back",
  animalDetailAddHealthNote: "Add Health Note",
  animalDetailSelectSymptom: "Select symptom/event",
  typeCow: "Cow",
  typeBuffalo: "Buffalo",
  typeCalf: "Calf",

  // ── AddAnimalModal ──
  addAnimalTitle: "Add New Animal",
  addAnimalSelectType: "Select Type",
  addAnimalName: "Name *",
  addAnimalNamePlaceholder: "e.g. Lakshmi",
  addAnimalBreed: "Breed",
  addAnimalBreedPlaceholder: "e.g. Jersey, Murrah",
  addAnimalTag: "Tag Number",
  addAnimalTagPlaceholder: "e.g. A001",
  addAnimalSave: "Add",
  addAnimalNameRequired: "Please enter animal name",
  addAnimalCustomBreed: "Custom",
  addAnimalBreedRequired: "Please select a breed",

  // ── MilkLogModal ──
  milkLogSelectSession: "Select Session",
  milkLogQuantityLabel: "Milk Quantity (Litres)",
  milkLogFatLabel: "Fat % (optional)",
  milkLogSaveBtn: "Save",
  milkLogInvalidQty: "Please enter a valid quantity",

  // ── AnimalCard quick actions ──
  quickActionFever: "Fever",
  quickActionNotEating: "Not Eating",
  quickActionInjury: "Injury",
  quickActionInHeat: "In Heat",

  // ── Health event options ──
  healthEventFever: "Fever",
  healthEventNotEating: "Not Eating",
  healthEventLimping: "Limping",
  healthEventDiarrhea: "Diarrhea",
  healthEventCoughing: "Coughing",
  healthEventVetVisit: "Vet Visit",
  healthEventVaccination: "Vaccination",

  // ── Onboarding ──
  languagePreference: "Language Preference",
  selectLanguage: "Select Language",
  onboardingWelcomeTitle: "Welcome to\nUpcheck Dairy",
  onboardingWelcomeSubtitle: "Manage your dairy farm smarter.\nTrack animals, monitor health, record milk production and grow your farm effortlessly.",
  onboardingWelcomeFeature1Title: "Milk Production Tracking",
  onboardingWelcomeFeature1Desc: "Record daily milk yield, monitor trends and improve farm productivity with ease.",
  onboardingWelcomeFeature2Title: "Animal Health Monitoring",
  onboardingWelcomeFeature2Desc: "Stay ahead of vaccinations, breeding schedules and medical records for every animal.",
  onboardingWelcomeFeature3Title: "Smart Farm Insights",
  onboardingWelcomeFeature3Desc: "Visualize growth, expenses and farm performance through intuitive dashboards.",
  onboardingWelcomeGetStarted: "Get Started",
  onboardingWelcomeFooter: "Your dairy journey starts here.",
  onboardingFarmDetailsTitle: "Tell us about your farm",
  onboardingFarmDetailsSubtitle: "We'll personalize your dairy management experience.",
  onboardingFarmDetailsFarmNameLabel: "Farm Name",
  onboardingFarmDetailsFarmNamePlaceholder: "Enter your farm name",
  onboardingFarmDetailsOwnerNameLabel: "Owner Name",
  onboardingFarmDetailsOwnerNamePlaceholder: "Enter owner's name",
  onboardingPhoneLabel: "Phone Number", // Use onboardingPhoneLabel to avoid overriding "phone" if it causes any type conflict, or use descriptive keys
  onboardingFarmDetailsPhonePlaceholder: "10-digit mobile number",
  onboardingFarmDetailsEmailLabel: "Email Address",
  onboardingFarmDetailsEmailPlaceholder: "example@email.com",
  onboardingLocationTitle: "Where is your farm?",
  onboardingLocationSubtitle: "We'll personalize weather updates, nearby veterinary services and local insights.",
  onboardingLocationVillageLabel: "Village",
  onboardingLocationVillagePlaceholder: "Enter village name",
  onboardingLocationDistrictLabel: "District",
  onboardingLocationDistrictPlaceholder: "Enter district",
  onboardingLocationStateLabel: "State",
  onboardingLocationStatePlaceholder: "Enter state",
  onboardingLocationPincodeLabel: "PIN Code",
  onboardingLocationPincodePlaceholder: "6-digit PIN code",
  onboardingAnimalTitle: "Animals on your farm",
  onboardingAnimalSubtitle: "Add the number of animals you currently own.",
  onboardingAnimalCow: "Cow",
  onboardingAnimalBuffalo: "Buffalo",
  onboardingAnimalGoat: "Goat",
  onboardingAnimalCalf: "Calf",
  onboardingAnimalBull: "Bull",
  onboardingAnimalOthers: "Others",
  onboardingAnimalTotalLabel: "Total Animals",
  onboardingAnimalSummarySubtext: "This helps us personalize your dashboard and farm insights.",
  onboardingPermissionTitle: "Community & Permissions",
  onboardingPermissionSubtitle: "Make this feel useful, not technical.",
  onboardingPermissionLocationTitle: "Find nearby dairy farmers",
  onboardingPermissionLocationSubtitle: "Get local advice, buy/sell fodder, and receive disease alerts.",
  onboardingPermissionLocationEnable: "Enable Location",
  onboardingPermissionLocationEnabled: "Enabled",
  onboardingPermissionNotifTitle: "Receive reminders",
  onboardingPermissionNotifSubtitle: "Vaccination alerts, milk payments, and community updates.",
  onboardingPermissionNotifEnable: "Enable Notifications",
  onboardingPermissionNotifEnabled: "Enabled",
  onboardingPermissionFinish: "Finish Setup",
  onboardingSuccessTitle: "You're all set! 🎉",
  onboardingSuccessSubtitle: "Your farm has been successfully registered",
  onboardingSuccessFarmName: "Farm Name",
  onboardingSuccessLocation: "Location",
  onboardingSuccessAnimalsAdded: "Animals Added",
  onboardingSuccessGoDashboard: "Go to Dashboard",
  onboardingSuccessReviewDetails: "Review Details",
  onboardingSuccessDefaultFarmSuffix: "Farm",
};

type T = typeof base;

const translations: Record<Language, T> = {
  en: { ...base },

  ta: {
    ...base,
    appName: "துளிர்பண்ணை",
    tagline: "உங்கள் பண்ணை, உங்கள் கையில்",
    tabAnimals: "என் மாடுகள்", tabHelp: "உதவி", tabMoney: "பணம்", tabToday: "இன்று",
    animals: "மாடுகள்", addAnimal: "மாடு சேர்", noAnimals: "மாடுகள் இல்லை",
    noAnimalsHint: "+ பொத்தானை அழுத்தி மாடு சேர்க்கவும்",
    filterAll: "அனைத்தும்", filterCow: "பசு", filterBuffalo: "எருமை",
    filterHealthy: "ஆரோக்கியம்", filterAttention: "கவனிக்கவும்", filterCritical: "அவசரம்",
    milkLog: "பால் பதிவு", milkLogSuccess: "பால் பதிவு ஆனது!", milkToday: "இன்று பால்",
    milkLogTitle: "பால் பதிவு செய்யவும்", session: "நேரம்", morning: "காலை", evening: "மாலை",
    quantity: "அளவு (லிட்டர்)", fatPercentage: "கொழுப்பு % (விருப்பம்)", save: "சேமி", cancel: "ரத்து",
    health: "உடல் நிலை", healthy: "ஆரோக்கியம்", attention: "கவனிக்கவும்", critical: "அவசரம்",
    income: "வருமானம்", expense: "செலவு", profit: "லாபம்", loss: "நஷ்டம்",
    totalIncome: "மொத்த வருமானம்", totalExpense: "மொத்த செலவு",
    addIncome: "வருமானம் சேர்", addExpense: "செலவு சேர்",
    today: "இன்று", goodMorning: "காலை வணக்கம், விவசாயி!", goodAfternoon: "மதிய வணக்கம்",
    goodEvening: "மாலை வணக்கம்", goodNight: "இரவு வணக்கம், விவசாயி!",
    tasks: "பணிகள்", allTasksDone: "அனைத்து பணிகளும் முடிந்தது!", progress: "இன்றைய முன்னேற்றம்",
    help: "பிரச்சனை & உதவி", sosButton: "ஏதாவது தவறா?", sosSub: "அழுத்தி அவசர உதவி பெறவும்",
    symptoms: "அறிகுறிகள் தேர்வு", diagnose: "AI ஆலோசனை பெறவும்", diagnosing: "AI பகுப்பாய்கிறது...",
    emergency: "அவசர தொடர்பு", callVet: "உடனே மருத்துவர் அழைக்கவும்", speak: "கேளு", stop: "நிறுத்து",
    profile: "என் சுயவிவரம்", farmerName: "விவசாயி பெயர்", village: "கிராமம்", district: "மாவட்டம்",
    phone: "தொலைபேசி", totalAnimals: "மொத்த மாடுகள்", language: "மொழி",
    logout: "வெளியேறு", editProfile: "திருத்து", saveProfile: "சுயவிவரம் சேமி",
    login: "உள்நுழை", signup: "பதிவு செய்",
    loginTitle: "துளிர்பண்ணைக்கு வரவேற்கிறோம்!", loginSub: "உங்கள் கைபேசி எண் உள்ளிடவும்",
    signupTitle: "உங்கள் சுயவிவரம் நிரப்பவும்", signupSub: "உங்களைப் பற்றி சொல்லுங்கள்",
    sendOtp: "OTP அனுப்பவும்",
    verifyOtp: "OTP சரிபார்க்கவும்",
    otpSentTo: "OTP அனுப்பப்பட்டது",
    enterOtp: "6 இலக்க OTP உள்ளிடவும்",
    resendOtp: "மீண்டும் OTP அனுப்பவும்",
    resendIn: "மீண்டும் அனுப்ப",
    seconds: "நொடி",
    otpExpiry: "OTP 5 நிமிடங்களில் காலாவதியாகும்",
    wrongOtp: "தவறான OTP",
    otpVerified: "சரிபார்க்கப்பட்டது!",
    namePlaceholder: "பெயர் (எ.கா: முருகன்)",
    villagePlaceholder: "கிராமம் (எ.கா: தஞ்சாவூர்)",
    districtPlaceholder: "மாவட்டம்",
    phonePlaceholder: "கைபேசி எண் (10 இலக்கம்)",
    farmNamePlaceholder: "பண்ணை பெயர் (விருப்பம்)",
    noAccount: "புதியதா?", haveAccount: "ஏற்கனவே உறுப்பினரா?",
    createAccount: "புதிய கணக்கு", skip: "இப்போது வேண்டாம்",
    continueBtn: "தொடர்க",
    required: "இது கட்டாயம்",
    invalidPhone: "சரியான கைபேசி எண் உள்ளிடவும்",
    success: "வெற்றி", error: "பிழை", networkError: "இணைப்பு பிழை",
    sync: "சேமிக்கப்பட்டது", syncing: "சேமிக்கிறது", offline: "offline",
    voice: "குரல்", voiceTitle: "குரல் கட்டளை", voiceSub: "தமிழில் பேசவும்",
    voiceHint: "மேலே பொத்தானை அழுத்தவும்", listening: "கேட்கிறேன்...", processing: "புரிந்துகொள்கிறேன்...",
    sampleCommands: "உதாரண கட்டளைகள்", speakAgain: "மீண்டும் சொல்",
    voicePlaceholder: "கட்டளை தட்டச்சு செய்யவும்...",
    voiceStatusRecording: "🎙 கேட்கிறேன்... (நிறுத்த மீண்டும் அழுத்தவும்)",
    voiceStatusProcessing: "⚡ புரிந்துகொள்கிறேன்...",
    voiceStatusError: "⚠ மீண்டும் முயற்சிக்கவும்",
    voiceNoMatch: "குரல் தெளிவாக கேட்கவில்லை. உரை உள்ளிடவும்.",
    voiceNotUnderstood: "புரியவில்லை. \"{text}\" — மீண்டும் முயற்சிக்கவும்",
    voiceMicPermission: "மைக்ரோஃபோன் அணுகல் வழங்கவும்",
    voiceNavLabel: "வழிசெலுத்தல்",
    voiceSampleMilk: "லட்சுமி 5 லிட்டர் காலை",
    voiceSampleHealth: "ராணி காய்ச்சல்",
    voiceSampleExpense: "தீவனம் செலவு 500",
    voiceSampleNav: "நிதி பக்கம் செல்",
    settingsTitle: "அமைப்புகள்", notifications: "அறிவிப்புகள்",
    notifEnabled: "அறிவிப்புகள் தயார்", enableNotif: "நினைவூட்டல் இயக்கு",
    demoOtpNote: "Demo OTP (சோதனைக்கு மட்டும்)",
    newUser: "புதிய விவசாயி? சுயவிவரம் உருவாக்கவும்",
    existingUser: "ஏற்கனவே உறுப்பினரா? உள்நுழையவும்",
    welcomeBack: "மீண்டும் வரவேற்கிறோம்",
    step1of3: "படி 1/3", step2of3: "படி 2/3", step3of3: "படி 3/3",
    verifying: "சரிபார்க்கிறது...",
    sending: "அனுப்புகிறது...",
    herdTab: "மந்தை", breedingTab: "இனப்பெருக்கம்", vaccinesTab: "தடுப்பூசி",
    myAnimalsTitle: "என் மாடுகள்", animalsCountSuffix: "மாடுகள்",
    breedingMgmt: "இனப்பெருக்க நிர்வாகம்", logEvent: "நிகழ்வு பதிவு",
    noEvents: "பதிவு இல்லை", pregnantLabel: "கர்ப்பம்", calvingExpected: "குட்டி தேதி:",
    daysAgoSuffix: " நாட்கள் முன்", overdueLabel: "கடந்தது", daysLabel: "நாட்கள்",
    addAnimalsFirst: "மாடுகள் சேர்க்கவும்", vaccinationSchedule: "தடுப்பூசி அட்டவணை",
    upcomingOverdue: "⏰ வரவிருக்கும் / கடந்த தடுப்பூசி",
    recentlyAdministered: "✅ சமீபத்தில் போட்டவை",
    noUpcomingVaccines: "தடுப்பூசி பதிவு இல்லை",
    scheduleVaccineBtn: "+ தடுப்பூசி திட்டமிடுங்கள்",
    scheduledDateLabel: "திட்டமிட்ட தேதி:", givenDateLabel: "போட்ட தேதி:",
    nextDueLabel: "அடுத்து:", markDoneBtn: "போட்டாயிற்று",
    vaccineMarkTitle: "தடுப்பூசி போட்டாயிற்றா?",
    vaccineMarkBody: "இன்று தடுப்பூசி போடப்பட்டதாக பதிவு செய்யவும்?", yes: "ஆம்",
    todayAlerts: "இன்றைய எச்சரிக்கைகள்", urgentLabel: "அவசரம்", highLabel: "முக்கியம்",
    milkDropAlert: "பால் குறைவு எச்சரிக்கை", milkDropSuffix: "குறைந்தது",
    todayPrefix: "இன்று:", avgPrefix: "சராசரி:",
    diagnoseTab: "நோய் கண்டறி", gauguruTab: "கோ குரு AI", emergencyTab: "அவசரம்",
    helpTitle: "பிரச்சனை & உதவி", aiDairyAssistant: "AI கால்நடை உதவியாளர்",
    whichAnimal: "எந்த மாடு? (விருப்பம்)", additionalNotes: "கூடுதல் குறிப்புகள்... (விருப்பம்)",
    callNow: "உடனே அழை!", firstAidTips: "முதல் உதவி குறிப்புகள்",
    emergencySosBtn: "ஏதாவது தவறா?", emergencySosSub: "அழுத்தி அவசர உதவி",
    quickQuestions: "⚡ விரைவு கேள்விகள்", gauguruSubtitle: "24/7 பண்ணை உதவியாளர்",
    chatPlaceholder: "GauGuru-ஐ கேளுங்கள்...", clearChat: "அழி",
    thinking: "யோசிக்கிறேன்...", errorMsg: "மன்னிக்கவும், பிழை ஏற்பட்டது. மீண்டும் முயற்சிக்கவும்.",
    financeTitle: "பணம்", incomeTab: "வருமானம்", expenseTab: "செலவுகள்", inventoryTab: "இருப்பு",
    sevenDayFinancials: "7 நாட்கள் நிதி", totalInventoryValue: "மொத்த இருப்பு மதிப்பு",
    lowStockItems: "பொருட்கள் குறைந்தவை", noInventory: "இருப்பு பதிவு இல்லை",
    addFirstItem: "+ பொருள் சேர்க்கவும்", deleteConfirmTitle: "நீக்கு?",
    deleteConfirmBtn: "நீக்கு", deleteItemBodyPrefix: "நீக்கவும்",
    herdStatus: "மாடுகள் நிலை", morningTasks: "காலை பணிகள்", eveningTasks: "மாலை பணிகள்",
    loadingTasks: "பணிகள் ஏற்றப்படுகின்றன...", reminders: "நினைவூட்டல்",
    remindersSet: "நினைவூட்டல் அமைக்கப்பட்டது!", savedLabel: "சேமிக்கப்பட்டது",
    savingLabel: "சேமிக்கிறது...", expenseBreakdown: "செலவு வகைகள்",
    animalDetailHealth: "உடல் நிலை",
    animalDetailMilkLog: "பால் பதிவு",
    animalDetailHealthNote: "உடல் குறிப்பு",
    animalDetailMilkHistory: "7 நாட்கள் பால் வரலாறு",
    animalDetailHealthHistory: "உடல்நிலை வரலாறு",
    animalDetailRecentMilk: "சமீபத்திய பால் பதிவுகள்",
    animalDetailNoNotes: "குறிப்புகள் இல்லை — மேலே 'உடல் குறிப்பு' அழுத்தவும்",
    animalDetailNoMilk: "பதிவுகள் இல்லை",
    animalDetailTagPrefix: "குறி: #",
    animalDetailDeleteTitle: "மாடு நீக்கு",
    animalDetailDeleteBody: "{name} ஐ நீக்கவா?",
    animalDetailDeleteConfirm: "நீக்கு",
    animalDetailDeleteCancel: "இல்லை",
    animalDetailPhotoTitle: "புகைப்படம் எடுக்கவும்",
    animalDetailPhotoBody: "புகைப்படம் எடுக்கவும் அல்லது கேலரியில் இருந்து தேர்வு செய்யவும்",
    animalDetailCamera: "📷 கேமரா",
    animalDetailGallery: "🖼 கேலரி",
    animalDetailPermissionNeeded: "அனுமதி தேவை",
    animalDetailCameraPermission: "கேமரா அணுகல் வழங்கவும்",
    animalDetailGalleryPermission: "கேலரி அணுகல் வழங்கவும்",
    animalDetailNotFound: "மாடு கிடைக்கவில்லை",
    animalDetailGoBack: "திரும்பு",
    animalDetailAddHealthNote: "உடல்நிலை குறிப்பு சேர்க்கவும்",
    animalDetailSelectSymptom: "அறிகுறி/நிகழ்வு தேர்வு செய்யவும்",
    typeCow: "பசு",
    typeBuffalo: "எருமை",
    typeCalf: "கன்று",
    addAnimalTitle: "புதிய மாடு சேர்க்கவும்",
    addAnimalSelectType: "வகை தேர்வு",
    addAnimalName: "பெயர் *",
    addAnimalNamePlaceholder: "உதா: லட்சுமி",
    addAnimalBreed: "ரகம்",
    addAnimalBreedPlaceholder: "உதா: ஜெர்சி, முர்ராஹ்",
    addAnimalTag: "குறி எண்",
    addAnimalTagPlaceholder: "உதா: A001",
    addAnimalSave: "சேர்க்கவும்",
    addAnimalNameRequired: "மாடு பெயர் உள்ளிடவும்",
    addAnimalCustomBreed: "தனிப்பயன்",
    addAnimalBreedRequired: "இனம் தேர்வு செய்யவும்",
    milkLogSelectSession: "அமர்வு தேர்வு",
    milkLogQuantityLabel: "பால் அளவு (லிட்டர்)",
    milkLogFatLabel: "கொழுப்பு % (விருப்பம்)",
    milkLogSaveBtn: "சேமி",
    milkLogInvalidQty: "சரியான அளவை உள்ளிடவும்",
    quickActionFever: "காய்ச்சல்",
    quickActionNotEating: "சாப்பிடவில்லை",
    quickActionInjury: "காயம்",
    quickActionInHeat: "ஈட்டு",
    healthEventFever: "காய்ச்சல் — Fever",
    healthEventNotEating: "சாப்பிடவில்லை — Not Eating",
    healthEventLimping: "கால் வலி — Limping",
    healthEventDiarrhea: "வயிற்றுப்போக்கு — Diarrhea",
    healthEventCoughing: "இருமல் — Coughing",
    healthEventVetVisit: "மருத்துவர் வருகை — Vet Visit",
    healthEventVaccination: "தடுப்பூசி — Vaccination",

    // ── Onboarding ──
    languagePreference: "மொழி விருப்பம்",
    selectLanguage: "மொழியைத் தேர்ந்தெடுக்கவும்",
    onboardingWelcomeTitle: "வரவேற்கிறோம்\nஅப்செக் டைரி",
    onboardingWelcomeSubtitle: "உங்கள் பால் பண்ணையை சிறந்த முறையில் நிர்வகிக்கவும்.\nமாடுகளைக் கண்காணிக்கவும், ஆரோக்கியத்தைக் கண்காணிக்கவும், பால் உற்பத்தியைப் பதிவு செய்யவும் மற்றும் உங்கள் பண்ணையை எளிதாக வளர்க்கவும்.",
    onboardingWelcomeFeature1Title: "பால் உற்பத்தி கண்காணிப்பு",
    onboardingWelcomeFeature1Desc: "தினசரி பால் அளவை பதிவு செய்து, போக்குகளைக் கண்காணித்து பண்ணை உற்பத்தித்திறனை எளிதாக மேம்படுத்தவும்.",
    onboardingWelcomeFeature2Title: "மாடுகளின் ஆரோக்கியக் கண்காணிப்பு",
    onboardingWelcomeFeature2Desc: "ஒவ்வொரு மாட்டின் தடுப்பூசிகள், இனப்பெருக்க அட்டவணைகள் மற்றும் மருத்துவப் பதிவுகளை முன்கூட்டியே நிர்வகிக்கவும்.",
    onboardingWelcomeFeature3Title: "ஸ்மார்ட் பண்ணை நுண்ணறிவு",
    onboardingWelcomeFeature3Desc: "எளிதான டாஷ்போர்டுகள் மூலம் வளர்ச்சி, செலவுகள் மற்றும் பண்ணை செயல்திறனைக் காணுங்கள்.",
    onboardingWelcomeGetStarted: "தொடங்குங்கள்",
    onboardingWelcomeFooter: "உங்கள் பால் பண்ணை பயணம் இங்கு தொடங்குகிறது.",
    onboardingFarmDetailsTitle: "உங்கள் பண்ணை பற்றி சொல்லுங்கள்",
    onboardingFarmDetailsSubtitle: "உங்கள் பால் பண்ணை மேலாண்மை அனுபவத்தை நாங்கள் தனிப்பயனாக்குவோம்.",
    onboardingFarmDetailsFarmNameLabel: "பண்ணை பெயர்",
    onboardingFarmDetailsFarmNamePlaceholder: "உங்கள் பண்ணையின் பெயரை உள்ளிடவும்",
    onboardingFarmDetailsOwnerNameLabel: "உரிமையாளர் பெயர்",
    onboardingFarmDetailsOwnerNamePlaceholder: "உரிமையாளரின் பெயரை உள்ளிடவும்",
    onboardingPhoneLabel: "தொலைபேசி எண்",
    onboardingFarmDetailsPhonePlaceholder: "10-இலக்க கைபேசி எண்",
    onboardingFarmDetailsEmailLabel: "மின்னஞ்சல் முகவரி",
    onboardingFarmDetailsEmailPlaceholder: "example@email.com",
    onboardingLocationTitle: "பண்ணை எங்கு உள்ளது?",
    onboardingLocationSubtitle: "வானிலை அறிவிப்புகள், அருகில் உள்ள கால்நடை சேவைகள் மற்றும் உள்ளூர் தகவல்களைத் தனிப்பயனாக்குவோம்.",
    onboardingLocationVillageLabel: "கிராமம்",
    onboardingLocationVillagePlaceholder: "கிராமத்தின் பெயரை உள்ளிடவும்",
    onboardingLocationDistrictLabel: "மாவட்டம்",
    onboardingLocationDistrictPlaceholder: "மாவட்டம் உள்ளிடவும்",
    onboardingLocationStateLabel: "மாநிலம்",
    onboardingLocationStatePlaceholder: "மாநிலம் உள்ளிடவும்",
    onboardingLocationPincodeLabel: "அஞ்சல் குறியீடு (PIN)",
    onboardingLocationPincodePlaceholder: "6-இலக்க அஞ்சல் குறியீடு",
    onboardingAnimalTitle: "பண்ணையில் உள்ள மாடுகள்",
    onboardingAnimalSubtitle: "தற்போது உங்களிடம் உள்ள மாடுகளின் எண்ணிக்கையைச் சேர்க்கவும்.",
    onboardingAnimalCow: "பசு",
    onboardingAnimalBuffalo: "எருமை",
    onboardingAnimalGoat: "ஆடு",
    onboardingAnimalCalf: "கன்று",
    onboardingAnimalBull: "காளை",
    onboardingAnimalOthers: "மற்றவை",
    onboardingAnimalTotalLabel: "மொத்த மாடுகள்",
    onboardingAnimalSummarySubtext: "இது உங்கள் டாஷ்போர்டு மற்றும் பண்ணை நுண்ணறிவுகளைத் தனிப்பயனாக்க உதவுகிறது.",
    onboardingPermissionTitle: "சமூகம் மற்றும் அனுமதிகள்",
    onboardingPermissionSubtitle: "இதை தொழில்நுட்பமாக இல்லாமல் பயனுள்ளதாக மாற்றுங்கள்.",
    onboardingPermissionLocationTitle: "அருகிலுள்ள விவசாயிகளைக் கண்டறியவும்",
    onboardingPermissionLocationSubtitle: "உள்ளூர் ஆলোசனைகளைப் பெறவும், தீவனம் வாங்க/விற்க மற்றும் நோய் எச்சரிக்கைகளைப் பெறவும்.",
    onboardingPermissionLocationEnable: "இருப்பிடத்தை அனுமதி",
    onboardingPermissionLocationEnabled: "அனுமதிக்கப்பட்டது",
    onboardingPermissionNotifTitle: "நினைவூட்டல்களைப் பெறுங்கள்",
    onboardingPermissionNotifSubtitle: "தடுப்பூசி எச்சரிக்கைகள், பால் பணம் செலுத்துதல் மற்றும் சமூக மேம்பாடுகள்.",
    onboardingPermissionNotifEnable: "அறிவிப்புகளை அனுமதி",
    onboardingPermissionNotifEnabled: "அனுமதிக்கப்பட்டது",
    onboardingPermissionFinish: "அமைப்பை முடிக்கவும்",
    onboardingSuccessTitle: "எல்லாம் தயாராகிவிட்டது! 🎉",
    onboardingSuccessSubtitle: "உங்கள் பண்ணை வெற்றிகரமாக பதிவு செய்யப்பட்டுள்ளது",
    onboardingSuccessFarmName: "பண்ணை பெயர்",
    onboardingSuccessLocation: "இருப்பிடம்",
    onboardingSuccessAnimalsAdded: "சேர்க்கப்பட்ட மாடுகள்",
    onboardingSuccessGoDashboard: "டாஷ்போர்டுக்குச் செல்லவும்",
    onboardingSuccessReviewDetails: "விவரங்களை மதிப்பாய்வு செய்க",
    onboardingSuccessDefaultFarmSuffix: "பண்ணை",
  },

  te: {
    ...base,
    appName: "థులిర్‌ఫార్మ్",
    tagline: "మీ పొలం, మీ చేతిలో",
    tabAnimals: "నా జంతువులు", tabHelp: "సహాయం", tabMoney: "డబ్బు", tabToday: "నేడు",
    animals: "జంతువులు", addAnimal: "జంతువు జోడించు", noAnimals: "జంతువులు లేవు",
    noAnimalsHint: "+ నొక్కి జంతువు జోడించండి",
    filterAll: "అన్నీ", filterCow: "ఆవు", filterBuffalo: "గేదె",
    filterHealthy: "ఆరోగ్యకరమైన", filterAttention: "శ్రద్ధ అవసరం", filterCritical: "అత్యవసరం",
    milkLog: "పాలు నమోదు", milkLogSuccess: "పాలు నమోదయ్యాయి!", milkToday: "నేడు పాలు",
    milkLogTitle: "పాలు నమోదు చేయండి", session: "సమయం", morning: "ఉదయం", evening: "సాయంత్రం",
    quantity: "పరిమాణం (లీటర్లు)", fatPercentage: "కొవ్వు % (ఐచ్ఛికం)", save: "సేవ్", cancel: "రద్దు",
    health: "ఆరోగ్యం", healthy: "ఆరోగ్యకరమైన", attention: "శ్రద్ధ అవసరం", critical: "అత్యవసరం",
    income: "ఆదాయం", expense: "వ్యయం", profit: "లాభం", loss: "నష్టం",
    totalIncome: "మొత్తం ఆదాయం", totalExpense: "మొత్తం వ్యయం",
    addIncome: "ఆదాయం జోడించు", addExpense: "వ్యయం జోడించు",
    today: "నేడు", goodMorning: "శుభోదయం, రైతు!", goodAfternoon: "శుభమధ్యాహ్నం",
    goodEvening: "శుభసాయంత్రం", goodNight: "శుభరాత్రి, రైతు!",
    tasks: "పనులు", allTasksDone: "అన్ని పనులు పూర్తయ్యాయి!", progress: "నేటి పురోగతి",
    help: "సమస్య & సహాయం", sosButton: "ఏదైనా తప్పు జరిగిందా?", sosSub: "అత్యవసర సహాయం కోసం నొక్కండి",
    symptoms: "లక్షణాలు ఎంచుకోండి", diagnose: "AI సలహా పొందండి", diagnosing: "AI విశ్లేషిస్తోంది...",
    emergency: "అత్యవసర సంప్రదింపులు", callVet: "వెంటనే వైద్యుని పిలవండి", speak: "వినండి", stop: "ఆపు",
    profile: "నా వివరాలు", farmerName: "రైతు పేరు", village: "గ్రామం", district: "జిల్లా",
    phone: "ఫోన్ నంబర్", totalAnimals: "మొత్తం జంతువులు", language: "భాష",
    logout: "లాగ్అవుట్", editProfile: "సవరించు", saveProfile: "వివరాలు సేవ్ చేయి",
    login: "లాగిన్", signup: "నమోదు",
    loginTitle: "థులిర్‌ఫార్మ్‌కు స్వాగతం!", loginSub: "మీ మొబైల్ నంబర్ నమోదు చేయండి",
    signupTitle: "మీ వివరాలు నమోదు చేయండి", signupSub: "మీ గురించి చెప్పండి",
    sendOtp: "OTP పంపండి",
    verifyOtp: "OTP ధృవీకరించండి",
    otpSentTo: "OTP పంపబడింది",
    enterOtp: "6-అంకె OTP నమోదు చేయండి",
    resendOtp: "OTP మళ్ళీ పంపండి",
    resendIn: "మళ్ళీ పంపు",
    seconds: "సెకన్లు",
    otpExpiry: "OTP 5 నిమిషాలలో గడువు ముగుస్తుంది",
    wrongOtp: "తప్పు OTP",
    otpVerified: "ధృవీకరించబడింది!",
    namePlaceholder: "పేరు (ఉదా: రాములు)",
    villagePlaceholder: "గ్రామం",
    districtPlaceholder: "జిల్లా",
    phonePlaceholder: "10-అంకె మొబైల్ నంబర్",
    farmNamePlaceholder: "పొలం పేరు (ఐచ్ఛికం)",
    noAccount: "కొత్తగా వచ్చారా?", haveAccount: "ఇప్పటికే సభ్యులా?",
    createAccount: "కొత్త ఖాతా", skip: "ఇప్పుడు వద్దు",
    continueBtn: "కొనసాగించు",
    required: "ఇది తప్పనిసరి",
    invalidPhone: "సరైన 10-అంకె మొబైల్ నంబర్ నమోదు చేయండి",
    success: "విజయం", error: "లోపం", networkError: "నెట్‌వర్క్ లోపం",
    sync: "సేవ్ చేయబడింది", syncing: "సేవ్ అవుతోంది...", offline: "ఆఫ్‌లైన్",
    demoOtpNote: "Demo OTP (పరీక్ష మాత్రమే)",
    newUser: "కొత్త రైతు? ప్రొఫైల్ తయారు చేయండి",
    existingUser: "ఇప్పటికే సభ్యులా? లాగిన్ అవ్వండి",
    welcomeBack: "తిరిగి స్వాగతం",
    step1of3: "దశ 1/3", step2of3: "దశ 2/3", step3of3: "దశ 3/3",
    verifying: "ధృవీకరిస్తోంది...",
    sending: "పంపుతోంది...",
    herdTab: "మంద", breedingTab: "పునరుత్పత్తి", vaccinesTab: "టీకాలు",
    myAnimalsTitle: "నా జంతువులు", animalsCountSuffix: "జంతువులు",
    breedingMgmt: "పునరుత్పత్తి నిర్వహణ", logEvent: "ఘటన నమోదు",
    noEvents: "నమోదు లేదు", pregnantLabel: "గర్భం", calvingExpected: "ప్రసవ తేదీ:",
    daysAgoSuffix: " రోజుల క్రితం", overdueLabel: "గడువు మించింది", daysLabel: "రోజులు",
    addAnimalsFirst: "జంతువులను జోడించండి", vaccinationSchedule: "టీకా షెడ్యూల్",
    upcomingOverdue: "⏰ రానున్న / గడువు మించిన",
    recentlyAdministered: "✅ ఇటీవల ఇచ్చినవి",
    noUpcomingVaccines: "రానున్న టీకాలు లేవు",
    scheduleVaccineBtn: "+ టీకా షెడ్యూల్ చేయండి",
    scheduledDateLabel: "నిర్ణయించిన తేదీ:", givenDateLabel: "ఇచ్చిన తేదీ:",
    nextDueLabel: "తర్వాత:", markDoneBtn: "పూర్తి",
    vaccineMarkTitle: "టీకా ఇవ్వబడిందా?",
    vaccineMarkBody: "ఈరోజు ఇచ్చినట్టు నమోదు చేయాలా?", yes: "అవును",
    todayAlerts: "నేటి హెచ్చరికలు", urgentLabel: "అత్యవసరం", highLabel: "ముఖ్యం",
    milkDropAlert: "పాల తగ్గుదల హెచ్చరిక", milkDropSuffix: "తగ్గింది",
    todayPrefix: "నేడు:", avgPrefix: "సగటు:",
    diagnoseTab: "రోగ నిర్ధారణ", gauguruTab: "GauGuru AI", emergencyTab: "అత్యవసరం",
    helpTitle: "సమస్య & సహాయం", aiDairyAssistant: "AI పాడి సహాయకుడు",
    whichAnimal: "ఏ జంతువు? (ఐచ్ఛికం)", additionalNotes: "అదనపు గమనికలు... (ఐచ్ఛికం)",
    callNow: "ఇప్పుడే పిలవండి!", firstAidTips: "ప్రాథమిక చికిత్స చిట్కాలు",
    emergencySosBtn: "ఏదైనా తప్పా?", emergencySosSub: "అత్యవసర సహాయానికి నొక్కండి",
    quickQuestions: "⚡ త్వరిత ప్రశ్నలు", gauguruSubtitle: "24/7 పాడి నిపుణుడు",
    chatPlaceholder: "GauGuru ని అడగండి...", clearChat: "తొలగించు",
    thinking: "ఆలోచిస్తున్నాను...", errorMsg: "క్షమించండి, దోషం సంభవించింది. మళ్ళీ ప్రయత్నించండి.",
    financeTitle: "ఆర్థికం", incomeTab: "ఆదాయం", expenseTab: "వ్యయాలు", inventoryTab: "సూచీ",
    sevenDayFinancials: "7 రోజుల ఆర్థికం", totalInventoryValue: "మొత్తం సూచీ విలువ",
    lowStockItems: "వస్తువులు తక్కువగా ఉన్నాయి", noInventory: "సూచీ లేదు",
    addFirstItem: "+ మొదటి వస్తువు జోడించు", deleteConfirmTitle: "తొలగించాలా?",
    deleteConfirmBtn: "తొలగించు", deleteItemBodyPrefix: "తొలగించు",
    herdStatus: "మంద స్థితి", morningTasks: "ఉదయం పనులు", eveningTasks: "సాయంత్రం పనులు",
    loadingTasks: "పనులు లోడవుతున్నాయి...", reminders: "రిమైండర్లు",
    remindersSet: "రిమైండర్లు సెట్ చేశారు!", savedLabel: "సేవ్ చేయబడింది",
    savingLabel: "సేవ్ అవుతోంది...", expenseBreakdown: "వ్యయ వర్గాలు",
    animalDetailHealth: "ఆరోగ్య స్థితి",
    animalDetailMilkLog: "పాలు నమోదు",
    animalDetailHealthNote: "ఆరోగ్య గమనిక",
    animalDetailMilkHistory: "7 రోజుల పాల చరిత్ర",
    animalDetailHealthHistory: "ఆరోగ్య చరిత్ర",
    animalDetailRecentMilk: "ఇటీవలి పాల నమోదులు",
    animalDetailNoNotes: "గమనికలు లేవు — పైన 'ఆరోగ్య గమనిక' నొక్కండి",
    animalDetailNoMilk: "నమోదులు లేవు",
    animalDetailTagPrefix: "ట్యాగ్: #",
    animalDetailDeleteTitle: "పశువును తొలగించు",
    animalDetailDeleteBody: "{name} ను తొలగించాలా?",
    animalDetailDeleteConfirm: "తొలగించు",
    animalDetailDeleteCancel: "వద్దు",
    animalDetailPhotoTitle: "ఫోటో తీయండి",
    animalDetailPhotoBody: "ఫోటో తీయండి లేదా గ్యాలరీ నుండి ఎంచుకోండి",
    animalDetailCamera: "📷 కెమెరా",
    animalDetailGallery: "🖼 గ్యాలరీ",
    animalDetailPermissionNeeded: "అనుమతి అవసరం",
    animalDetailCameraPermission: "కెమెరా యాక్సెస్ ఇవ్వండి",
    animalDetailGalleryPermission: "గ్యాలరీ యాక్సెస్ ఇవ్వండి",
    animalDetailNotFound: "పశువు కనబడలేదు",
    animalDetailGoBack: "వెనక్కి",
    animalDetailAddHealthNote: "ఆరోగ్య గమనిక చేర్చు",
    animalDetailSelectSymptom: "లక్షణం/సంఘటన ఎంచుకోండి",
    typeCow: "ఆవు",
    typeBuffalo: "గేదె",
    typeCalf: "దూడ",
    addAnimalTitle: "కొత్త పశువు చేర్చు",
    addAnimalSelectType: "రకం ఎంచుకోండి",
    addAnimalName: "పేరు *",
    addAnimalNamePlaceholder: "ఉదా: లక్ష్మి",
    addAnimalBreed: "జాతి",
    addAnimalBreedPlaceholder: "ఉదా: జెర్సీ, మురా",
    addAnimalTag: "ట్యాగ్ నంబర్",
    addAnimalTagPlaceholder: "ఉదా: A001",
    addAnimalSave: "చేర్చు",
    addAnimalNameRequired: "పశువు పేరు నమోదు చేయండి",
    addAnimalCustomBreed: "కస్టమ్",
    addAnimalBreedRequired: "జాతి ఎంచుకోండి",
    milkLogSelectSession: "సెషన్ ఎంచుకోండి",
    milkLogQuantityLabel: "పాల పరిమాణం (లీటర్లు)",
    milkLogFatLabel: "కొవ్వు % (ఐచ్ఛికం)",
    milkLogSaveBtn: "సేవ్ చేయి",
    milkLogInvalidQty: "సరైన పరిమాణం నమోదు చేయండి",
    quickActionFever: "జ్వరం",
    quickActionNotEating: "తినడం లేదు",
    quickActionInjury: "గాయం",
    quickActionInHeat: "ఎదకు వచ్చింది",
    healthEventFever: "జ్వరం — Fever",
    healthEventNotEating: "తినడం లేదు — Not Eating",
    healthEventLimping: "కుంటుతోంది — Limping",
    healthEventDiarrhea: "విరేచనాలు — Diarrhea",
    healthEventCoughing: "దగ్గు — Coughing",
    healthEventVetVisit: "డాక్టర్ సందర్శన — Vet Visit",
    healthEventVaccination: "టీకా — Vaccination",

    // ── Onboarding ──
    languagePreference: "భాషా ప్రాధాన్యత",
    selectLanguage: "భాషను ఎంచుకోండి",
    onboardingWelcomeTitle: "స్వాగతం\nఅప్‌చెక్ డెయిరీ",
    onboardingWelcomeSubtitle: "మీ పాడి పరిశ్రమను మరింత తెలివిగా నిర్వహించండి.\nజంతువులను ట్రాక్ చేయండి, ఆరోగ్యాన్ని పర్యవేక్షించండి, పాలు ఉత్పత్తిని నమోదు చేయండి మరియు మీ ఫారమ్‌ను సులഭంగా అభివృద్ధి చేయండి.",
    onboardingWelcomeFeature1Title: "పాలు ఉత్పత్తి ట్రాకింగ్",
    onboardingWelcomeFeature1Desc: "రోజువారీ పాలు దిగుబడిని నమోదు చేయండి, ట్రెండ్‌లను పర్యవేక్షించండి మరియు ఫారమ్ ఉత్పాదకతను సులభంగా మెరుగుపరచండి.",
    onboardingWelcomeFeature2Title: "జంతువుల ఆరోగ్య పర్యవేక్షణ",
    onboardingWelcomeFeature2Desc: "ప్రతి జంతువు కోసం టీకాలు, ప్రజనన షెడ్యూల్‌లు మరియు వైద్య రికార్డులను ముందుగానే నిర్వహించండి.",
    onboardingWelcomeFeature3Title: "స్మార్ట్ ఫారమ్ అంతర్దృష్టులు",
    onboardingWelcomeFeature3Desc: "సులభమైన డ్యాష్‌బోర్డ్‌ల ద్వారా వృద్ధి, ఖర్చులు మరియు ఫారమ్ పనితీరును దృశ్యమానం చేయండి.",
    onboardingWelcomeGetStarted: "ప్రారంభించండి",
    onboardingWelcomeFooter: "మీ పాడి పరిశ్రమ ప్రయాణం ఇక్కడే ప్రారంభమవుతుంది.",
    onboardingFarmDetailsTitle: "మీ పొలం గురించి చెప్పండి",
    onboardingFarmDetailsSubtitle: "మేము మీ పాడి నిర్వహణ అనుభవాన్ని వ్యక్తిగతీకరిస్తాము.",
    onboardingFarmDetailsFarmNameLabel: "ఫారమ్ పేరు",
    onboardingFarmDetailsFarmNamePlaceholder: "మీ ఫారమ్ పేరు నమోదు చేయండి",
    onboardingFarmDetailsOwnerNameLabel: "యజమాని పేరు",
    onboardingFarmDetailsOwnerNamePlaceholder: "యజమాని పేరు నమోదు చేయండి",
    onboardingPhoneLabel: "ఫోన్ నంబర్",
    onboardingFarmDetailsPhonePlaceholder: "10-అంకెల మొబైల్ నంబర్",
    onboardingFarmDetailsEmailLabel: "ఈమెయిల్ చిరునామా",
    onboardingFarmDetailsEmailPlaceholder: "example@email.com",
    onboardingLocationTitle: "మీ పొలం ఎక్కడ ఉంది?",
    onboardingLocationSubtitle: "మేము వాతావరణ అప్‌డేట్‌లు, సమీప పశువైద్య సేవలు మరియు స్థానిక అంతర్దృష్టులను వ్యక్తిగతీకరిస్తాము.",
    onboardingLocationVillageLabel: "గ్రామం",
    onboardingLocationVillagePlaceholder: "గ్రామం పేరు నమోదు చేయండి",
    onboardingLocationDistrictLabel: "జిల్లా",
    onboardingLocationDistrictPlaceholder: "జిల్లా నమోదు చేయండి",
    onboardingLocationStateLabel: "రాష్ట్రం",
    onboardingLocationStatePlaceholder: "రాష్ట్రం నమోదు చేయండి",
    onboardingLocationPincodeLabel: "పిన్ కోడ్",
    onboardingLocationPincodePlaceholder: "6-అంకెల పిన్ కోడ్",
    onboardingAnimalTitle: "మీ పొలంలో ఉన్న జంతువులు",
    onboardingAnimalSubtitle: "ప్రస్తుತು మీ వద్ద ఉన్న జంతువుల సంఖ్యను జోడించండి.",
    onboardingAnimalCow: "ఆవు",
    onboardingAnimalBuffalo: "గేదె",
    onboardingAnimalGoat: "మేక",
    onboardingAnimalCalf: "దూడ",
    onboardingAnimalBull: "ఎద్దు",
    onboardingAnimalOthers: "ఇతరాలు",
    onboardingAnimalTotalLabel: "మొత్తం జంతువులు",
    onboardingAnimalSummarySubtext: "ఇది మీ డ్యాష్‌బోర్డ్ మరియు ఫారమ్ అంతర్దృష్టులను వ్యక్తిగతీకరించడంలో మాకు సహాయపడుతుంది.",
    onboardingPermissionTitle: "కమ్యూనిటీ & అనుమతులు",
    onboardingPermissionSubtitle: "దీనిని సాంకేతికంగా కాకుండా ఉపయోగకరంగా మార్చండి.",
    onboardingPermissionLocationTitle: "సమీపంలోని పాడి రైతులను కనుగొనండి",
    onboardingPermissionLocationSubtitle: "స్థానిక సలహాలను పొందండి, పశుగ్రాసాన్ని కొనండి/అమ్మండి మరియు వ్యాధి హెచ్చరికలను అందుకోండి.",
    onboardingPermissionLocationEnable: "స్థానాన్ని అనుమతించు",
    onboardingPermissionLocationEnabled: "అనుమతించబడింది",
    onboardingPermissionNotifTitle: "రిమైండర్‌లను స్వీకరించండి",
    onboardingPermissionNotifSubtitle: "టీకా హెచ్చరికలు, పాలు చెల్లింపులు మరియు కమ్యూనిటీ అప్‌డేట్‌లు.",
    onboardingPermissionNotifEnable: "నోటిఫికేషన్‌లను అనుమతించు",
    onboardingPermissionNotifEnabled: "అనుమతించబడింది",
    onboardingPermissionFinish: "సెటప్ ముగించు",
    onboardingSuccessTitle: "అంతా సిద్ధమైంది! 🎉",
    onboardingSuccessSubtitle: "మీ పొలం విజయవంతంగా నమోదైంది",
    onboardingSuccessFarmName: "ఫారమ్ పేరు",
    onboardingSuccessLocation: "స్థానం",
    onboardingSuccessAnimalsAdded: "జోడించిన జంతువులు",
    onboardingSuccessGoDashboard: "డ్యాష్‌బోర్డ్‌కు వెళ్లండి",
    onboardingSuccessReviewDetails: "వివరాలను సమీక్షించండి",
    onboardingSuccessDefaultFarmSuffix: "ఫారమ్",
    voiceTitle: "వాయిస్ కమాండ్",
    voiceSub: "తెలుగులో మాట్లాడండి",
    voiceHint: "ప్రారంభించడానికి బటన్‌ను నొక్కండి",
    listening: "వింటున్నాను...",
    processing: "అర్థం చేసుకుంటున్నాను...",
    speakAgain: "మళ్ళీ మాట్లాడండి",
    sampleCommands: "ఉదాహరణ కమాండ్లు",
    voicePlaceholder: "ఆదేశాన్ని టైప్ చేయండి...",
    voiceStatusRecording: "🎙 వింటున్నాను... (ఆపడానికి మళ్ళీ నొక్కండి)",
    voiceStatusProcessing: "⚡ అర్థం చేసుకుంటున్నాను...",
    voiceStatusError: "⚠ దయచేసి మళ్ళీ ప్రయత్నించండి",
    voiceNoMatch: "స్వరం స్పష్టంగా వినబడలేదు. దయచేసి టైప్ చేయండి.",
    voiceNotUnderstood: "అర్థం కాలేదు. \"{text}\" — దయచేసి మళ్ళీ ప్రయత్నించండి",
    voiceMicPermission: "దయచేసి మైక్రోఫోన్ యాక్సెస్ ఇవ్వండి",
    voiceNavLabel: "నావిగేషన్",
    voiceSampleMilk: "లక్ష్మి 5 లీటర్లు ఉదయం",
    voiceSampleHealth: "రాణి జ్వరం",
    voiceSampleExpense: "మేత ఖర్చు 500",
    voiceSampleNav: "ఆర్థిక పేజీకి వెళ్ళు",
  },

  kn: {
    ...base,
    appName: "ತುಳಿರ್‌ಫಾರ್ಮ್",
    tagline: "ನಿಮ್ಮ ತೋಟ, ನಿಮ್ಮ ಕೈಯಲ್ಲಿ",
    tabAnimals: "ನನ್ನ ಪ್ರಾಣಿಗಳು", tabHelp: "ಸಹಾಯ", tabMoney: "ಹಣ", tabToday: "ಇಂದು",
    animals: "ಪ್ರಾಣಿಗಳು", addAnimal: "ಪ್ರಾಣಿ ಸೇರಿಸಿ", noAnimals: "ಪ್ರಾಣಿಗಳಿಲ್ಲ",
    noAnimalsHint: "+ ಒತ್ತಿ ಪ್ರಾಣಿ ಸೇರಿಸಿ",
    filterAll: "ಎಲ್ಲ", filterCow: "ಹಸು", filterBuffalo: "ಕೋಣ",
    filterHealthy: "ಆರೋಗ್ಯಕರ", filterAttention: "ಗಮನ ಬೇಕು", filterCritical: "ತುರ್ತು",
    milkLog: "ಹಾಲು ದಾಖಲು", milkLogSuccess: "ಹಾಲು ದಾಖಲಾಯಿತು!", milkToday: "ಇಂದಿನ ಹಾಲು",
    milkLogTitle: "ಹಾಲು ದಾಖಲಿಸಿ", session: "ಸಮಯ", morning: "ಬೆಳಿಗ್ಗೆ", evening: "ಸಂಜೆ",
    quantity: "ಪ್ರಮಾಣ (ಲೀಟರ್)", fatPercentage: "ಕೊಬ್ಬು % (ಐಚ್ಛಿಕ)", save: "ಉಳಿಸಿ", cancel: "ರದ್ದು",
    health: "ಆರೋಗ್ಯ", healthy: "ಆರೋಗ್ಯಕರ", attention: "ಗಮನ ಬೇಕು", critical: "ತುರ್ತು",
    income: "ಆದಾಯ", expense: "ವೆಚ್ಚ", profit: "ಲಾಭ", loss: "ನಷ್ಟ",
    totalIncome: "ಒಟ್ಟು ಆದಾಯ", totalExpense: "ಒಟ್ಟು ವೆಚ್ಚ",
    addIncome: "ಆದಾಯ ಸೇರಿಸಿ", addExpense: "ವೆಚ್ಚ ಸೇರಿಸಿ",
    today: "ಇಂದು", goodMorning: "ಶುಭೋದಯ, ರೈತ!", goodAfternoon: "ಶುಭ ಮಧ್ಯಾಹ್ನ",
    goodEvening: "ಶುಭ ಸಂಜೆ", goodNight: "ಶುಭ ರಾತ್ರಿ, ರೈತ!",
    tasks: "ಕೆಲಸಗಳು", allTasksDone: "ಎಲ್ಲ ಕೆಲಸ ಮುಗಿಯಿತು!", progress: "ಇಂದಿನ ಪ್ರಗತಿ",
    help: "ಸಮಸ್ಯೆ & ಸಹಾಯ", sosButton: "ಏನಾದರೂ ತಪ್ಪಾಯಿತೇ?", sosSub: "ತುರ್ತು ಸಹಾಯಕ್ಕೆ ಒತ್ತಿ",
    symptoms: "ರೋಗಲಕ್ಷಣಗಳು ಆರಿಸಿ", diagnose: "AI ಸಲಹೆ ಪಡೆಯಿರಿ", diagnosing: "AI ವಿಶ್ಲೇಷಿಸುತ್ತಿದೆ...",
    emergency: "ತುರ್ತು ಸಂಪರ್ಕಗಳು", callVet: "ತಕ್ಷಣ ಪಶು ವೈದ್ಯರನ್ನು ಕರೆಯಿರಿ", speak: "ಕೇಳಿ", stop: "ನಿಲ್ಲಿಸಿ",
    profile: "ನನ್ನ ಪ್ರೊಫೈಲ್", farmerName: "ರೈತರ ಹೆಸರು", village: "ಗ್ರಾಮ", district: "ಜಿಲ್ಲೆ",
    phone: "ಫೋನ್ ಸಂಖ್ಯೆ", totalAnimals: "ಒಟ್ಟು ಪ್ರಾಣಿಗಳು", language: "ಭಾಷೆ",
    logout: "ಲಾಗ್ ಔಟ್", editProfile: "ತಿದ್ದಿ", saveProfile: "ಪ್ರೊಫೈಲ್ ಉಳಿಸಿ",
    login: "ಲಾಗಿನ್", signup: "ನೋಂದಣಿ",
    loginTitle: "ತುಳಿರ್‌ಫಾರ್ಮ್‌ಗೆ ಸ್ವಾಗತ!", loginSub: "ನಿಮ್ಮ ಮೊಬೈಲ್ ನಂಬರ್ ನಮೂದಿಸಿ",
    signupTitle: "ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಪೂರ್ಣಗೊಳಿಸಿ", signupSub: "ನಿಮ್ಮ ಬಗ್ಗೆ ಹೇಳಿ",
    sendOtp: "OTP ಕಳುಹಿಸಿ",
    verifyOtp: "OTP ದೃಢೀಕರಿಸಿ",
    otpSentTo: "OTP ಕಳುಹಿಸಲಾಗಿದೆ",
    enterOtp: "6-ಅಂಕಿ OTP ನಮೂದಿಸಿ",
    resendOtp: "OTP ಮತ್ತೆ ಕಳುಹಿಸಿ",
    resendIn: "ಮತ್ತೆ ಕಳುಹಿಸು",
    seconds: "ಸೆಕೆಂಡ್",
    otpExpiry: "OTP 5 ನಿಮಿಷಗಳಲ್ಲಿ ಅವಧಿ ಮೀರುತ್ತದೆ",
    wrongOtp: "ತಪ್ಪು OTP",
    otpVerified: "ದೃಢೀಕರಿಸಲಾಗಿದೆ!",
    namePlaceholder: "ಹೆಸರು (ಉದಾ: ರಾಮಪ್ಪ)",
    villagePlaceholder: "ಗ್ರಾಮ",
    districtPlaceholder: "ಜಿಲ್ಲೆ",
    phonePlaceholder: "10-ಅಂಕಿ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
    farmNamePlaceholder: "ತೋಟದ ಹೆಸರು (ಐಚ್ಛಿಕ)",
    noAccount: "ಹೊಸಬರೇ?", haveAccount: "ಈಗಾಗಲೇ ಸದಸ್ಯರೇ?",
    createAccount: "ಹೊಸ ಖಾತೆ", skip: "ಈಗ ಬೇಡ",
    continueBtn: "ಮುಂದುವರಿಸಿ",
    required: "ಇದು ಅಗತ್ಯ",
    invalidPhone: "ಸರಿಯಾದ 10-ಅಂಕಿ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ",
    success: "ಯಶಸ್ಸು", error: "ದೋಷ", networkError: "ನೆಟ್‌ವರ್ಕ್ ದೋಷ",
    sync: "ಉಳಿಸಲಾಗಿದೆ", syncing: "ಉಳಿಸುತ್ತಿದೆ...", offline: "ಆಫ್‌ಲೈನ್",
    demoOtpNote: "Demo OTP (ಪರೀಕ್ಷೆಗಾಗಿ ಮಾತ್ರ)",
    newUser: "ಹೊಸ ರೈತ? ಪ್ರೊಫೈಲ್ ತಯಾರಿಸಿ",
    existingUser: "ಈಗಾಗಲೇ ಸದಸ್ಯರೇ? ಲಾಗಿನ್ ಅಗಿ",
    welcomeBack: "ಮತ್ತೆ ಸ್ವಾಗತ",
    step1of3: "ಹಂತ 1/3", step2of3: "ಹಂತ 2/3", step3of3: "ಹಂತ 3/3",
    verifying: "ದೃಢೀಕರಿಸುತ್ತಿದೆ...",
    sending: "ಕಳುಹಿಸುತ್ತಿದೆ...",
    herdTab: "ಹಿಂಡು", breedingTab: "ಸಂತಾನೋತ್ಪತ್ತಿ", vaccinesTab: "ಲಸಿಕೆಗಳು",
    myAnimalsTitle: "ನನ್ನ ಪ್ರಾಣಿಗಳು", animalsCountSuffix: "ಪ್ರಾಣಿಗಳು",
    breedingMgmt: "ಸಂತಾನೋತ್ಪತ್ತಿ ನಿರ್ವಹಣೆ", logEvent: "ಘಟನೆ ದಾಖಲಿಸಿ",
    noEvents: "ದಾಖಲೆ ಇಲ್ಲ", pregnantLabel: "ಗರ್ಭ", calvingExpected: "ಹೆರಿಗೆ ದಿನ:",
    daysAgoSuffix: " ದಿನಗಳ ಹಿಂದೆ", overdueLabel: "ಗಡುವು ಮೀರಿದೆ", daysLabel: "ದಿನಗಳು",
    addAnimalsFirst: "ಪ್ರಾಣಿಗಳನ್ನು ಸೇರಿಸಿ", vaccinationSchedule: "ಲಸಿಕೆ ವೇಳಾಪಟ್ಟಿ",
    upcomingOverdue: "⏰ ಮುಂದಿನ / ಗಡುವು ಮೀರಿದ",
    recentlyAdministered: "✅ ಇತ್ತೀಚೆಗೆ ನೀಡಿದವು",
    noUpcomingVaccines: "ಮುಂದಿನ ಲಸಿಕೆಗಳಿಲ್ಲ",
    scheduleVaccineBtn: "+ ಲಸಿಕೆ ನಿಗದಿಪಡಿಸಿ",
    scheduledDateLabel: "ನಿಗದಿ ದಿನ:", givenDateLabel: "ನೀಡಿದ ದಿನ:",
    nextDueLabel: "ಮುಂದಿನ:", markDoneBtn: "ಮುಗಿಯಿತು",
    vaccineMarkTitle: "ಲಸಿಕೆ ನೀಡಿದ್ದೀರಾ?",
    vaccineMarkBody: "ಇಂದು ನೀಡಿದ್ದಾಗಿ ದಾಖಲಿಸಬೇಕೇ?", yes: "ಹೌದು",
    todayAlerts: "ಇಂದಿನ ಎಚ್ಚರಿಕೆಗಳು", urgentLabel: "ತುರ್ತು", highLabel: "ಪ್ರಮುಖ",
    milkDropAlert: "ಹಾಲು ಕಡಿಮೆ ಎಚ್ಚರಿಕೆ", milkDropSuffix: "ಕಡಿಮೆಯಾಗಿದೆ",
    todayPrefix: "ಇಂದು:", avgPrefix: "ಸರಾಸರಿ:",
    diagnoseTab: "ರೋಗ ನಿರ್ಣಯ", gauguruTab: "GauGuru AI", emergencyTab: "ತುರ್ತು",
    helpTitle: "ಸಮಸ್ಯೆ & ಸಹಾಯ", aiDairyAssistant: "AI ಹಾಲು ಸಹಾಯಕ",
    whichAnimal: "ಯಾವ ಪ್ರಾಣಿ? (ಐಚ್ಛಿಕ)", additionalNotes: "ಹೆಚ್ಚಿನ ಟಿಪ್ಪಣಿ... (ಐಚ್ಛಿಕ)",
    callNow: "ತಕ್ಷಣ ಕರೆಯಿರಿ!", firstAidTips: "ಪ್ರಥಮ ಚಿಕಿತ್ಸೆ ಸಲಹೆಗಳು",
    emergencySosBtn: "ಏನಾದರೂ ತಪ್ಪಾಯಿತೇ?", emergencySosSub: "ತುರ್ತು ಸಹಾಯಕ್ಕೆ ಒತ್ತಿ",
    quickQuestions: "⚡ ತ್ವರಿತ ಪ್ರಶ್ನೆಗಳು", gauguruSubtitle: "24/7 ಹಾಲು ತಜ್ಞ",
    chatPlaceholder: "GauGuru ಕೇಳಿ...", clearChat: "ಅಳಿಸು",
    thinking: "ಯೋಚಿಸುತ್ತಿದ್ದೇನೆ...", errorMsg: "ಕ್ಷಮಿಸಿ, ದೋಷ ಸಂಭವಿಸಿದೆ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    financeTitle: "ಹಣಕಾಸು", incomeTab: "ಆದಾಯ", expenseTab: "ವೆಚ್ಚಗಳು", inventoryTab: "ದಾಸ್ತಾನು",
    sevenDayFinancials: "7 ದಿನಗಳ ಹಣಕಾಸು", totalInventoryValue: "ಒಟ್ಟು ದಾಸ್ತಾನು ಮೌಲ್ಯ",
    lowStockItems: "ವಸ್ತುಗಳ ದಾಸ್ತಾನು ಕಡಿಮೆ", noInventory: "ದಾಸ್ತಾನು ಇಲ್ಲ",
    addFirstItem: "+ ಮೊದಲ ವಸ್ತು ಸೇರಿಸಿ", deleteConfirmTitle: "ಅಳಿಸಬೇಕೇ?",
    deleteConfirmBtn: "ಅಳಿಸಿ", deleteItemBodyPrefix: "ಅಳಿಸಿ",
    herdStatus: "ಹಿಂಡಿನ ಸ್ಥಿತಿ", morningTasks: "ಬೆಳಿಗ್ಗೆ ಕೆಲಸಗಳು", eveningTasks: "ಸಂಜೆ ಕೆಲಸಗಳು",
    loadingTasks: "ಕೆಲಸಗಳು ಲೋಡ್ ಆಗುತ್ತಿವೆ...", reminders: "ಜ್ಞಾಪನಗಳು",
    remindersSet: "ಜ್ಞಾಪನಗಳು ಸಿದ್ಧ!", savedLabel: "ಉಳಿಸಲಾಗಿದೆ",
    savingLabel: "ಉಳಿಸುತ್ತಿದೆ...", expenseBreakdown: "ವೆಚ್ಚ ವರ್ಗಗಳು",
    animalDetailHealth: "ಆರೋಗ್ಯ ಸ್ಥಿತಿ",
    animalDetailMilkLog: "ಹಾಲು ದಾಖಲು",
    animalDetailHealthNote: "ಆರೋಗ್ಯ ಟಿಪ್ಪಣಿ",
    animalDetailMilkHistory: "7 ದಿನಗಳ ಹಾಲಿನ ಇತಿಹಾಸ",
    animalDetailHealthHistory: "ಆರೋಗ್ಯ ಇತಿಹಾಸ",
    animalDetailRecentMilk: "ಇತ್ತೀಚಿನ ಹಾಲಿನ ದಾಖಲೆಗಳು",
    animalDetailNoNotes: "ಟಿಪ್ಪಣಿಗಳಿಲ್ಲ — ಮೇಲೆ 'ಆರೋಗ್ಯ ಟಿಪ್ಪಣಿ' ಒತ್ತಿ",
    animalDetailNoMilk: "ದಾಖಲೆಗಳಿಲ್ಲ",
    animalDetailTagPrefix: "ಟ್ಯಾಗ್: #",
    animalDetailDeleteTitle: "ಪ್ರಾಣಿ ತೆಗೆದುಹಾಕು",
    animalDetailDeleteBody: "{name} ಅನ್ನು ತೆಗೆದುಹಾಕಬೇಕೇ?",
    animalDetailDeleteConfirm: "ತೆಗೆದುಹಾಕು",
    animalDetailDeleteCancel: "ಬೇಡ",
    animalDetailPhotoTitle: "ಫೋಟೋ ತೆಗೆಯಿರಿ",
    animalDetailPhotoBody: "ಫೋಟೋ ತೆಗೆಯಿರಿ ಅಥವಾ ಗ್ಯಾಲರಿಯಿಂದ ಆಯ್ಕೆ ಮಾಡಿ",
    animalDetailCamera: "📷 ಕ್ಯಾಮೆರಾ",
    animalDetailGallery: "🖼 ಗ್ಯಾಲರಿ",
    animalDetailPermissionNeeded: "ಅನುಮತಿ ಬೇಕು",
    animalDetailCameraPermission: "ಕ್ಯಾಮೆರಾ ಪ್ರವೇಶ ನೀಡಿ",
    animalDetailGalleryPermission: "ಗ್ಯಾಲರಿ ಪ್ರವೇಶ ನೀಡಿ",
    animalDetailNotFound: "ಪ್ರಾಣಿ ಸಿಗಲಿಲ್ಲ",
    animalDetailGoBack: "ಹಿಂದೆ ಹೋಗಿ",
    animalDetailAddHealthNote: "ಆರೋಗ್ಯ ಟಿಪ್ಪಣಿ ಸೇರಿಸಿ",
    animalDetailSelectSymptom: "ಲಕ್ಷಣ/ಘಟನೆ ಆಯ್ಕೆ ಮಾಡಿ",
    typeCow: "ಹಸು",
    typeBuffalo: "ಎಮ್ಮೆ",
    typeCalf: "ಕರು",
    addAnimalTitle: "ಹೊಸ ಪ್ರಾಣಿ ಸೇರಿಸಿ",
    addAnimalSelectType: "ವಿಧ ಆಯ್ಕೆ ಮಾಡಿ",
    addAnimalName: "ಹೆಸರು *",
    addAnimalNamePlaceholder: "ಉದಾ: ಲಕ್ಷ್ಮಿ",
    addAnimalBreed: "ತಳಿ",
    addAnimalBreedPlaceholder: "ಉದಾ: ಜರ್ಸಿ, ಮುರ್ರಾ",
    addAnimalTag: "ಟ್ಯಾಗ್ ಸಂಖ್ಯೆ",
    addAnimalTagPlaceholder: "ಉದಾ: A001",
    addAnimalSave: "ಸೇರಿಸಿ",
    addAnimalNameRequired: "ಪ್ರಾಣಿಯ ಹೆಸರು ನಮೂದಿಸಿ",
    addAnimalCustomBreed: "ಕಸ್ಟಮ್",
    addAnimalBreedRequired: "ತಳಿ ಆರಿಸಿ",
    milkLogSelectSession: "ಅವಧಿ ಆಯ್ಕೆ ಮಾಡಿ",
    milkLogQuantityLabel: "ಹಾಲಿನ ಪ್ರಮಾಣ (ಲೀಟರ್)",
    milkLogFatLabel: "ಕೊಬ್ಬು % (ಐಚ್ಛಿಕ)",
    milkLogSaveBtn: "ಉಳಿಸಿ",
    milkLogInvalidQty: "ಸರಿಯಾದ ಪ್ರಮಾಣ ನಮೂದಿಸಿ",
    quickActionFever: "ಜ್ವರ",
    quickActionNotEating: "ತಿನ್ನುತ್ತಿಲ್ಲ",
    quickActionInjury: "ಗಾಯ",
    quickActionInHeat: "ಬೆದೆಗೆ ಬಂದಿದೆ",
    healthEventFever: "ಜ್ವರ — Fever",
    healthEventNotEating: "ತಿನ್ನುತ್ತಿಲ್ಲ — Not Eating",
    healthEventLimping: "ಕುಂಟುತ್ತಿದೆ — Limping",
    healthEventDiarrhea: "ಭೇದಿ — Diarrhea",
    healthEventCoughing: "ಕೆಮ್ಮು — Coughing",
    healthEventVetVisit: "ವೈದ್ಯರ ಭೇಟಿ — Vet Visit",
    healthEventVaccination: "ಲಸಿಕೆ — Vaccination",

    // ── Onboarding ──
    languagePreference: "ಭಾಷಾ ಆದ್ಯತೆ",
    selectLanguage: "ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    onboardingWelcomeTitle: "ಸ್ವಾಗತ\nಅಪ್‌ಚೆಕ್ ಡೈರಿ",
    onboardingWelcomeSubtitle: "ನಿಮ್ಮ ಡೈರಿ ಫಾರ್ಮ್ ಅನ್ನು ಹೆಚ್ಚು ಸ್ಮಾರ್ಟ್ ಆಗಿ ನಿರ್ವಹಿಸಿ.\nಪ್ರಾಣಿಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ, ಆರೋಗ್ಯವನ್ನು ಮೇಲ್ವಿಚಾರಣೆ ಮಾಡಿ, ಹಾಲು ಉತ್ಪಾದನೆಯನ್ನು ದಾಖಲಿಸಿ ಮತ್ತು ನಿಮ್ಮ ಫಾರ್ಮ್ ಅನ್ನು ಸುಲಭವಾಗಿ ಬೆಳೆಸಿಕೊಳ್ಳಿ.",
    onboardingWelcomeFeature1Title: "ಹಾಲು ಉತ್ಪಾದನೆ ಟ್ರ್ಯಾಕಿಂಗ್",
    onboardingWelcomeFeature1Desc: "ದೈನಂದಿನ ಹಾಲಿನ ಇಳುವರಿಯನ್ನು ದಾಖಲಿಸಿ, ಪ್ರವೃತ್ತಿಗಳನ್ನು ಮೇಲ್ವಿಚಾರಣೆ ಮಾಡಿ ಮತ್ತು ಫಾರ್ಮ್ ಉತ್ಪಾದಕತೆಯನ್ನು ಸುಲಭವಾಗಿ ಸುಧಾರಿಸಿ.",
    onboardingWelcomeFeature2Title: "ಪ್ರಾಣಿಗಳ ಆರೋಗ್ಯ ಮೇಲ್ವಿಚಾರಣೆ",
    onboardingWelcomeFeature2Desc: "ಪ್ರತಿ ಪ್ರಾಣಿಯ ಲಸಿಕೆಗಳು, ಸಂತಾನೋತ್ಪತ್ತಿ ವೇಳಾಪಟ್ಟಿಗಳು ಮತ್ತು ವೈದ್ಯಕೀಯ ದಾಖಲೆಗಳ ಬಗ್ಗೆ ಮುಂಚಿತವಾಗಿ ತಿಳಿದುಕೊಳ್ಳಿ.",
    onboardingWelcomeFeature3Title: "ಸ್ಮಾರ್ಟ್ ಫಾರ್ಮ್ ಒಳನೋಟಗಳು",
    onboardingWelcomeFeature3Desc: "ಸುಲಭವಾದ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗಳ ಮೂಲಕ ಬೆಳವಣಿಗೆ, ವೆಚ್ಚಗಳು ಮತ್ತು ಫಾರ್ಮ್ ಕಾರ್ಯಕ್ಷಮತೆಯನ್ನು ದೃಶ್ಯೀಕರಿಸಿ.",
    onboardingWelcomeGetStarted: "ಪ್ರಾರಂಭಿಸಿ",
    onboardingWelcomeFooter: "ನಿಮ್ಮ ಡೈರಿ ಪ್ರಯಾಣವು ಇಲ್ಲಿಂದ ಪ್ರಾರಂಭವಾಗುತ್ತದೆ.",
    onboardingFarmDetailsTitle: "ನಿಮ್ಮ ಫಾರ್ಮ್ ಬಗ್ಗೆ ತಿಳಿಸಿ",
    onboardingFarmDetailsSubtitle: "ನಿಮ್ಮ ಡೈರಿ ನಿರ್ವಹಣಾ ಅನುಭವವನ್ನು ನಾವು ವೈಯಕ್ತಿಕಗೊಳಿಸುತ್ತೇವೆ.",
    onboardingFarmDetailsFarmNameLabel: "Farming Name", // Custom fallback/label
    onboardingFarmDetailsFarmNamePlaceholder: "ನಿಮ್ಮ ಫಾರ್ಮ್ ಹೆಸರು ನಮೂದಿಸಿ",
    onboardingFarmDetailsOwnerNameLabel: "ಮಾಲೀಕರ ಹೆಸರು",
    onboardingFarmDetailsOwnerNamePlaceholder: "ಮಾಲೀಕರ ಹೆಸರು ನಮೂದಿಸಿ",
    onboardingPhoneLabel: "ಫೋನ್ ಸಂಖ್ಯೆ",
    onboardingFarmDetailsPhonePlaceholder: "10-ಅಂಕಿಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
    onboardingFarmDetailsEmailLabel: "ಇಮೇಲ್ ವಿಳಾಸ",
    onboardingFarmDetailsEmailPlaceholder: "example@email.com",
    onboardingLocationTitle: "ನಿಮ್ಮ ಫಾರ್ಮ್ ಎಲ್ಲಿದೆ?",
    onboardingLocationSubtitle: "ನಾವು ಹವಾಮಾನ ನವೀಕರಣಗಳು, ಹತ್ತಿರದ ಪಶುವೈದ್ಯಕೀಯ ಸೇವೆಗಳು ಮತ್ತು ಸ್ಥಳೀಯ ಒಳನೋಟಗಳನ್ನು ವೈಯಕ್ತಿಕಗೊಳಿಸುತ್ತೇವೆ.",
    onboardingLocationVillageLabel: "ಗ್ರಾಮ",
    onboardingLocationVillagePlaceholder: "ಗ್ರಾಮದ ಹೆಸರು ನಮೂದಿಸಿ",
    onboardingLocationDistrictLabel: "ಜಿಲ್ಲೆ",
    onboardingLocationDistrictPlaceholder: "ಜಿಲ್ಲೆ ನಮೂದಿಸಿ",
    onboardingLocationStateLabel: "ರಾಜ್ಯ",
    onboardingLocationStatePlaceholder: "ರಾಜ್ಯ ನಮೂದಿಸಿ",
    onboardingLocationPincodeLabel: "ಪಿನ್ ಕೋಡ್",
    onboardingLocationPincodePlaceholder: "6-ಅಂಕಿಯ ಪಿನ್ ಕೋಡ್",
    onboardingAnimalTitle: "ನಿಮ್ಮ ಫಾರ್ಮ್‌ನಲ್ಲಿರುವ ಪ್ರಾಣಿಗಳು",
    onboardingAnimalSubtitle: "ಪ್ರಸ್ತುತ ನಿಮ್ಮಲ್ಲಿರುವ ಪ್ರಾಣಿಗಳ ಸಂಖ್ಯೆಯನ್ನು ಸೇರಿಸಿ.",
    onboardingAnimalCow: "ಹಸು",
    onboardingAnimalBuffalo: "ಎಮ್ಮೆ",
    onboardingAnimalGoat: "ಮೇಕೆ",
    onboardingAnimalCalf: "ಕರು",
    onboardingAnimalBull: "ಹೋರಿ",
    onboardingAnimalOthers: "ಇತರರು",
    onboardingAnimalTotalLabel: "ಒಟ್ಟು ಪ್ರಾಣಿಗಳು",
    onboardingAnimalSummarySubtext: "ಇದು ನಿಮ್ಮ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ಮತ್ತು ಫಾರ್ಮ್ ಒಳನೋಟಗಳನ್ನು ವೈಯಕ್ತಿಕಗೊಳಿಸಲು ನಮಗೆ ಸಹಾಯ ಮಾಡುತ್ತದೆ.",
    onboardingPermissionTitle: "ಸಮುದಾಯ ಮತ್ತು ಅನುಮತಿಗಳು",
    onboardingPermissionSubtitle: "ಇದನ್ನು ತಾಂತ್ರಿಕವಾಗಿ ಮಾಡದೆ ಉಪಯುಕ್ತವಾಗುವಂತೆ ಮಾಡಿ.",
    onboardingPermissionLocationTitle: "ಹತ್ತಿರದ ಡೈರಿ ರೈತರನ್ನು ಹುಡುಕಿ",
    onboardingPermissionLocationSubtitle: "ಸ್ಥಳೀಯ ಸಲಹೆ ಪಡೆಯಿರಿ, ಮೇವು ಖರೀದಿಸಿ/ಮಾರಿ ಮತ್ತು ರೋಗದ ಮುನ್ನೆಚ್ಚರಿಕೆಗಳನ್ನು ಸ್ವೀಕರಿಸಿ.",
    onboardingPermissionLocationEnable: "ಸ್ಥಳವನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಿ",
    onboardingPermissionLocationEnabled: "ಸಕ್ರಿಯಗೊಳಿಸಲಾಗಿದೆ",
    onboardingPermissionNotifTitle: "ಜ್ಞಾಪನೆಗಳನ್ನು ಸ್ವೀಕರಿಸಿ",
    onboardingPermissionNotifSubtitle: "ಲಸಿಕೆ ಎಚ್ಚರಿಕೆಗಳು, ಹಾಲು ಪಾವತಿಗಳು ಮತ್ತು ಸಮುದಾಯ ನವೀಕರಣಗಳು.",
    onboardingPermissionNotifEnable: "ಅಧಿಸೂಚನೆಗಳನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಿ",
    onboardingPermissionNotifEnabled: "ಸಕ್ರಿಯಗೊಳಿಸಲಾಗಿದೆ",
    onboardingPermissionFinish: "ಸೆಟಪ್ ಮುಗಿಸಿ",
    onboardingSuccessTitle: "ಎಲ್ಲವೂ ಸಿದ್ಧವಾಗಿದೆ! 🎉",
    onboardingSuccessSubtitle: "ನಿಮ್ಮ ಫಾರ್ಮ್ ಯಶಸ್ವಿಯಾಗಿ ನೋন্দಾಯಿಸಲ್ಪಟ್ಟಿದೆ",
    onboardingSuccessFarmName: "ಫಾರ್ಮ್ ಹೆಸರು",
    onboardingSuccessLocation: "ಸ್ಥಳ",
    onboardingSuccessAnimalsAdded: "ಸೇರಿಸಲಾದ ಪ್ರಾಣಿಗಳು",
    onboardingSuccessGoDashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಹೋಗಿ",
    onboardingSuccessReviewDetails: "ವಿವರಗಳನ್ನು ಪರಿಶೀಲಿಸಿ",
    onboardingSuccessDefaultFarmSuffix: "ಫಾರ್ಮ್",
    voiceTitle: "ಧ್ವನಿ ಆಜ್ಞೆ",
    voiceSub: "ಕನ್ನಡದಲ್ಲಿ ಮಾತನಾಡಿ",
    voiceHint: "ಪ್ರಾರಂಭಿಸಲು ಬಟನ್ ಒತ್ತಿ",
    listening: "ಆಲಿಸಲಾಗುತ್ತಿದೆ...",
    processing: "ಅರ್ಥಮಾಡಿಕೊಳ್ಳುತ್ತಿದ್ದೇನೆ...",
    speakAgain: "ಮತ್ತೆ ಮಾತನಾಡಿ",
    sampleCommands: "ಉದಾಹರಣೆ ಆಜ್ಞೆಗಳು",
    voicePlaceholder: "ಆಜ್ಞೆಯನ್ನು ಟೈಪ್ ಮಾಡಿ...",
    voiceStatusRecording: "🎙 ಆಲಿಸಲಾಗುತ್ತಿದೆ... (ನಿಲ್ಲಿಸಲು ಮತ್ತೆ ಒತ್ತಿ)",
    voiceStatusProcessing: "⚡ ಅರ್ಥಮಾಡಿಕೊಳ್ಳುತ್ತಿದ್ದೇನೆ...",
    voiceStatusError: "⚠ ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ",
    voiceNoMatch: "ಧ್ವನಿ ಸ್ಪಷ್ಟವಾಗಿ ಕೇಳಿಸಲಿಲ್ಲ. ದಯವಿಟ್ಟು ಟೈಪ್ ಮಾಡಿ.",
    voiceNotUnderstood: "ಅರ್ಥವಾಗಲಿಲ್ಲ. \"{text}\" — ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ",
    voiceMicPermission: "ದಯವಿಟ್ಟು ಮೈಕ್ರೊಫೋನ್ ಪ್ರವೇಶವನ್ನು ನೀಡಿ",
    voiceNavLabel: "ನ್ಯಾವಿಗೇಶನ್",
    voiceSampleMilk: "ಲಕ್ಷ್ಮಿ 5 ಲೀಟರ್ ಬೆಳಿಗ್ಗೆ",
    voiceSampleHealth: "ರಾಣಿ ಜ್ವರ",
    voiceSampleExpense: "ಮೇವು ವೆಚ್ಚ 500",
    voiceSampleNav: "ಹಣಕಾಸು ಪುಟಕ್ಕೆ ಹೋಗು",
  },

  ml: {
    ...base,
    appName: "തുളിർ‌ഫാം",
    tagline: "നിങ്ങളുടെ ഫാം, നിങ്ങളുടെ കൈകളിൽ",
    tabAnimals: "എന്റെ മൃഗങ്ങൾ", tabHelp: "സഹായം", tabMoney: "പണം", tabToday: "ഇന്ന്",
    animals: "മൃഗങ്ങൾ", addAnimal: "മൃഗം ചേർക്കുക", noAnimals: "മൃഗങ്ങൾ ഇല്ല",
    noAnimalsHint: "+ അമർത്തി മൃഗം ചേർക്കുക",
    filterAll: "എല്ലാം", filterCow: "പശു", filterBuffalo: "എരുമ",
    filterHealthy: "ആരോഗ്യകരം", filterAttention: "ശ്രദ്ധ വേണം", filterCritical: "അടിയന്തര",
    milkLog: "പാൽ രേഖ", milkLogSuccess: "പാൽ രേഖപ്പെടുത്തി!", milkToday: "ഇന്നത്തെ പാൽ",
    milkLogTitle: "പാൽ രേഖപ്പെടുത്തുക", session: "സമയം", morning: "രാവിലെ", evening: "വൈകുന്നേരം",
    quantity: "അളവ് (ലിറ്റർ)", fatPercentage: "കൊഴുപ്പ് % (ഐഛിക)", save: "സേവ്", cancel: "റദ്ദ്",
    health: "ആരോഗ്യം", healthy: "ആരോഗ്യകരം", attention: "ശ്രദ്ധ വേണം", critical: "അടിയന്തര",
    income: "വരുമാനം", expense: "ചെലവ്", profit: "ലാഭം", loss: "നഷ്ടം",
    totalIncome: "മൊത്തം വരുമാനം", totalExpense: "മൊത്തം ചെലവ്",
    addIncome: "വരുമാനം ചേർക്കുക", addExpense: "ചെലവ് ചേർക്കുക",
    today: "ഇന്ന്", goodMorning: "ശുഭ പ്രഭാതം, കർഷക!", goodAfternoon: "ശുഭ ഉച്ച",
    goodEvening: "ശുഭ സന്ധ്യ", goodNight: "ശുഭ രാത്രി, കർഷക!",
    tasks: "ജോലികൾ", allTasksDone: "എല്ലാ ജോലികളും പൂർത്തി!", progress: "ഇന്നത്തെ പ്രഗതി",
    help: "പ്രശ്നം & സഹായം", sosButton: "എന്തെങ്കിലും തെറ്റായോ?", sosSub: "അടിയന്തര സഹായത്തിന് അമർത്തുക",
    symptoms: "ലക്ഷണങ്ങൾ തിരഞ്ഞെടുക്കുക", diagnose: "AI ഉപദേശം നേടുക", diagnosing: "AI വിശകലനം ചെയ്യുന്നു...",
    emergency: "അടിയന്തര ബന്ധപ്പെടൽ", callVet: "ഉടൻ ഡോക്ടറെ വിളിക്കുക", speak: "കേൾക്കുക", stop: "നിർത്തുക",
    profile: "എന്റെ പ്രൊഫൈൽ", farmerName: "കർഷകന്റെ പേര്", village: "ഗ്രാമം", district: "ജില്ല",
    phone: "ഫോൺ നമ്പർ", totalAnimals: "ആകെ മൃഗങ്ങൾ", language: "ഭാഷ",
    logout: "ലോഗ് ഔട്ട്", editProfile: "എഡിറ്റ്", saveProfile: "പ്രൊഫൈൽ സേവ്",
    login: "ലോഗിൻ", signup: "രജിസ്ട്രേഷൻ",
    loginTitle: "തുളിർ‌ഫാമിലേക്ക് സ്വാഗതം!", loginSub: "നിങ്ങളുടെ മൊബൈൽ നമ്പർ നൽകുക",
    signupTitle: "പ്രൊഫൈൽ പൂർത്തിയാക്കുക", signupSub: "നിങ്ങളെ കുറിച്ച് പറയൂ",
    sendOtp: "OTP അയയ്ക്കുക",
    verifyOtp: "OTP സ്ഥിരീകരിക്കുക",
    otpSentTo: "OTP അയച്ചിരിക്കുന്നു",
    enterOtp: "6-അക്ക OTP നൽകുക",
    resendOtp: "OTP വീണ്ടും അയയ്ക്കുക",
    resendIn: "വീണ്ടും അയക്കൂ",
    seconds: "സെക്കൻഡ്",
    otpExpiry: "OTP 5 മിനിറ്റിൽ കാലഹരണപ്പെടും",
    wrongOtp: "തെറ്റായ OTP",
    otpVerified: "സ്ഥിരീകരിച്ചു!",
    namePlaceholder: "പേര് (ഉദാ: രാജൻ)",
    villagePlaceholder: "ഗ്രാമം",
    districtPlaceholder: "ജില്ല",
    phonePlaceholder: "10-അക്ക മൊബൈൽ നമ്പർ",
    farmNamePlaceholder: "ഫാമിന്റെ പേര് (ഐഛിക)",
    noAccount: "പുതിയതോ?", haveAccount: "ഇതിനകം അംഗമോ?",
    createAccount: "പുതിയ അക്കൗണ്ട്", skip: "ഇപ്പോൾ വേണ്ട",
    continueBtn: "തുടരുക",
    required: "ഇത് ആവശ്യമാണ്",
    invalidPhone: "ശരിയായ 10-അക്ക മൊബൈൽ നമ്പർ നൽകുക",
    success: "വിജയം", error: "പിഴവ്", networkError: "നെറ്റ്‌വർക്ക് പിഴവ്",
    sync: "സേവ് ചെയ്തു", syncing: "സേവ് ചെയ്യുന്നു...", offline: "ഓഫ്‌ലൈൻ",
    demoOtpNote: "Demo OTP (പരീക്ഷണം മാത്രം)",
    newUser: "പുതിയ കർഷക? പ്രൊഫൈൽ ഉണ്ടാക്കൂ",
    existingUser: "ഇതിനകം അംഗമോ? ലോഗിൻ ആകൂ",
    welcomeBack: "തിരിച്ചു സ്വാഗതം",
    step1of3: "ഘട്ടം 1/3", step2of3: "ഘട്ടം 2/3", step3of3: "ഘട്ടം 3/3",
    verifying: "സ്ഥിരീകരിക്കുന്നു...",
    sending: "അയക്കുന്നു...",
    herdTab: "കൂട്ടം", breedingTab: "പ്രജനനം", vaccinesTab: "കുത്തിവയ്പ്പ്",
    myAnimalsTitle: "എന്റെ മൃഗങ്ങൾ", animalsCountSuffix: "മൃഗങ്ങൾ",
    breedingMgmt: "പ്രജനന മാനേജ്‌മെന്റ്", logEvent: "സംഭവം രേഖ",
    noEvents: "രേഖ ഇല്ല", pregnantLabel: "ഗർഭം", calvingExpected: "ഈനൽ തീയതി:",
    daysAgoSuffix: " ദിവസം മുൻ", overdueLabel: "കാലഹരണം", daysLabel: "ദിവസം",
    addAnimalsFirst: "മൃഗങ്ങൾ ചേർക്കൂ", vaccinationSchedule: "കുത്തിവയ്പ്പ് ഷെഡ്യൂൾ",
    upcomingOverdue: "⏰ വരുന്ന / കാലഹരണ",
    recentlyAdministered: "✅ അടുത്തിടെ നൽകിയത്",
    noUpcomingVaccines: "വരുന്ന കുത്തിവയ്പ്പ് ഇല്ല",
    scheduleVaccineBtn: "+ കുത്തിവയ്പ്പ് ഷെഡ്യൂൾ",
    scheduledDateLabel: "നിശ്ചിത തീയതി:", givenDateLabel: "നൽകിയ തീയതി:",
    nextDueLabel: "അടുത്ത:", markDoneBtn: "ചെയ്തു",
    vaccineMarkTitle: "കുത്തിവയ്പ്പ് ചെയ്തോ?",
    vaccineMarkBody: "ഇന്ന് നൽകിയതായി രേഖ ചേർക്കണോ?", yes: "അതേ",
    todayAlerts: "ഇന്നത്തെ അലർട്ടുകൾ", urgentLabel: "അടിയന്തര", highLabel: "പ്രധാനം",
    milkDropAlert: "പാൽ കുറവ് അലർട്ട്", milkDropSuffix: "കുറഞ്ഞു",
    todayPrefix: "ഇന്ന്:", avgPrefix: "ശരാശരി:",
    diagnoseTab: "രോഗ നിർണ്ണയം", gauguruTab: "GauGuru AI", emergencyTab: "അടിയന്തര",
    helpTitle: "പ്രശ്നം & സഹായം", aiDairyAssistant: "AI ഡയറി സഹായി",
    whichAnimal: "ഏത് മൃഗം? (ഐഛിക)", additionalNotes: "കൂടുതൽ കുറിപ്പ്... (ഐഛിക)",
    callNow: "ഉടൻ വിളിക്കൂ!", firstAidTips: "പ്രഥമ ചികിത്സ നുറുങ്ങുകൾ",
    emergencySosBtn: "എന്തെങ്കിലും തെറ്റോ?", emergencySosSub: "അടിയന്തര സഹായത്തിന് അമർത്തുക",
    quickQuestions: "⚡ വേഗ ചോദ്യങ്ങൾ", gauguruSubtitle: "24/7 ഡയറി വിദഗ്ദ്ധൻ",
    chatPlaceholder: "GauGuru ചോദിക്കൂ...", clearChat: "മായ്ക്കൂ",
    thinking: "ചിന്തിക്കുന്നു...", errorMsg: "ക്ഷമിക്കൂ, പിഴവ് സംഭവിച്ചു. വീണ്ടും ശ്രമിക്കൂ.",
    financeTitle: "ധനകാര്യം", incomeTab: "വരുമാനം", expenseTab: "ചെലവുകൾ", inventoryTab: "ശേഖരം",
    sevenDayFinancials: "7 ദിവസ ധനകാര്യം", totalInventoryValue: "ആകെ ശേഖര മൂല്യം",
    lowStockItems: "സ്റ്റോക്ക് കുറഞ്ഞ ഇനങ്ങൾ", noInventory: "ശേഖരം ഇല്ല",
    addFirstItem: "+ ആദ്യ ഇനം ചേർക്കൂ", deleteConfirmTitle: "നീക്കണോ?",
    deleteConfirmBtn: "നീക്കൂ", deleteItemBodyPrefix: "നീക്കൂ",
    herdStatus: "കൂട്ടത്തിന്റെ നില", morningTasks: "രാവിലത്തെ ജോലികൾ", eveningTasks: "വൈകുന്നേര ജോലികൾ",
    loadingTasks: "ജോലികൾ ലോഡ് ആകുന്നു...", reminders: "ഓർമ്മപ്പെടുത്തൽ",
    remindersSet: "ഓർമ്മപ്പെടുത്തൽ സജ്ജം!", savedLabel: "സേവ് ചെയ്തു",
    savingLabel: "സേവ് ചെയ്യുന്നു...", expenseBreakdown: "ചെലവ് വർഗ്ഗങ്ങൾ",
    animalDetailHealth: "ആരോഗ്യ നില",
    animalDetailMilkLog: "പാൽ രേഖ",
    animalDetailHealthNote: "ആരോഗ്യ കുറിപ്പ്",
    animalDetailMilkHistory: "7 ദിവസ പാൽ ചരിത്രം",
    animalDetailHealthHistory: "ആരോഗ്യ ചരിത്രം",
    animalDetailRecentMilk: "സമീപകാല പാൽ രേഖകൾ",
    animalDetailNoNotes: "കുറിപ്പുകൾ ഇല്ല — മുകളിൽ 'ആരോഗ്യ കുറിപ്പ്' അമർത്തുക",
    animalDetailNoMilk: "രേഖകൾ ഇല്ല",
    animalDetailTagPrefix: "ടാഗ്: #",
    animalDetailDeleteTitle: "മൃഗത്തെ നീക്കം ചെയ്യുക",
    animalDetailDeleteBody: "{name} നീക്കം ചെയ്യണോ?",
    animalDetailDeleteConfirm: "നീക്കം",
    animalDetailDeleteCancel: "വേണ്ട",
    animalDetailPhotoTitle: "ഫോട്ടോ എടുക്കൂ",
    animalDetailPhotoBody: "ഫോട്ടോ എടുക്കൂ അല്ലെങ്കിൽ ഗ്യാലറിയിൽ നിന്ന് തിരഞ്ഞെടുക്കൂ",
    animalDetailCamera: "📷 ക്യാമറ",
    animalDetailGallery: "🖼 ഗ്യാലറി",
    animalDetailPermissionNeeded: "അനുമതി ആവശ്യമാണ്",
    animalDetailCameraPermission: "ക്യാമറ ആക്സസ് അനുവദിക്കൂ",
    animalDetailGalleryPermission: "ഗ്യാലറി ആക്സസ് അനുവദിക്കൂ",
    animalDetailNotFound: "മൃഗം കണ്ടെത്തിയില്ല",
    animalDetailGoBack: "തിരിച്ചു പോകൂ",
    animalDetailAddHealthNote: "ആരോഗ്യ കുറിപ്പ് ചേർക്കൂ",
    animalDetailSelectSymptom: "ലക്ഷണം/സംഭവം തിരഞ്ഞെടുക്കൂ",
    typeCow: "പശു",
    typeBuffalo: "എരുമ",
    typeCalf: "കിടാവ്",
    addAnimalTitle: "പുതിയ മൃഗം ചേർക്കൂ",
    addAnimalSelectType: "തരം തിരഞ്ഞെടുക്കൂ",
    addAnimalName: "പേര് *",
    addAnimalNamePlaceholder: "ഉദാ: ലക്ഷ്മി",
    addAnimalBreed: "ഇനം",
    addAnimalBreedPlaceholder: "ഉദാ: ജേഴ്സി, മുർറ",
    addAnimalTag: "ടാഗ് നമ്പർ",
    addAnimalTagPlaceholder: "ഉദാ: A001",
    addAnimalSave: "ചേർക്കൂ",
    addAnimalNameRequired: "മൃഗത്തിന്റെ പേര് നൽകൂ",
    addAnimalCustomBreed: "കസ്റ്റം",
    addAnimalBreedRequired: "ജാതി തിരഞ്ഞെടുക്കൂ",
    milkLogSelectSession: "സെഷൻ തിരഞ്ഞെടുക്കൂ",
    milkLogQuantityLabel: "പാൽ അളവ് (ലിറ്റർ)",
    milkLogFatLabel: "കൊഴുപ്പ് % (ഐഛിക)",
    milkLogSaveBtn: "സേവ് ചെയ്യൂ",
    milkLogInvalidQty: "ശരിയായ അളവ് നൽകൂ",
    quickActionFever: "പനി",
    quickActionNotEating: "തിന്നുന്നില്ല",
    quickActionInjury: "പരിക്ക്",
    quickActionInHeat: "മദി വന്നു",
    healthEventFever: "പനി — Fever",
    healthEventNotEating: "തിന്നുന്നില്ല — Not Eating",
    healthEventLimping: "മുടന്തുന്നു — Limping",
    healthEventDiarrhea: "വയറിളക്കം — Diarrhea",
    healthEventCoughing: "ചുമ — Coughing",
    healthEventVetVisit: "ഡോക്ടർ സന്ദർശനം — Vet Visit",
    healthEventVaccination: "കുത്തിവയ്പ്പ് — Vaccination",

    // ── Onboarding ──
    languagePreference: "ഭാഷാ മുൻഗണന",
    selectLanguage: "ഭാഷ തിരഞ്ഞെടുക്കുക",
    onboardingWelcomeTitle: "സ്വാഗതം\nഅപ്‌ചെക്ക് ഡയറി",
    onboardingWelcomeSubtitle: "നിങ്ങളുടെ ഡയറി ഫാം കൂടുതൽ സ്മാർട്ടായി കൈകാര്യം ചെയ്യുക.\nമൃഗങ്ങളെ ട്രാക്ക് ചെയ്യുക, ആരോഗ്യം നിരീക്ഷിക്കുക, പാൽ ഉത്പാദനം രേഖപ്പെടുത്തുക, നിങ്ങളുടെ ഫാം എളുപ്പത്തിൽ വളർത്തുക.",
    onboardingWelcomeFeature1Title: "പാൽ ഉത്പാദന ട്രാക്കിംഗ്",
    onboardingWelcomeFeature1Desc: "ദിവസേനയുള്ള പാൽ അളവ് രേഖപ്പെടുത്തുക, ട്രെൻഡുകൾ നിരീക്ഷിക്കുക, ഫാമിന്റെ ഉൽപ്പാദനക്ഷമത എളുപ്പത്തിൽ മെച്ചപ്പെടുത്തുക.",
    onboardingWelcomeFeature2Title: "മൃഗങ്ങളുടെ ആരോഗ്യ നിരീക്ഷണം",
    onboardingWelcomeFeature2Desc: "ഓരോ മൃഗത്തിന്റെയും പ്രതിരോധ കുത്തിവയ്പ്പുകൾ, പ്രജനന ഷെഡ്യൂളുകൾ, മെഡിക്കൽ രേഖകൾ എന്നിവ മുൻകൂട്ടി അറിയുക.",
    onboardingWelcomeFeature3Title: "സ്മാർട്ട് ഫാം സ്ഥിതിവിവരക്കണക്കുകൾ",
    onboardingWelcomeFeature3Desc: "ലളിതമായ ഡാഷ്‌ബോർഡുകളിലൂടെ വളർച്ച, ചെലവുകൾ, ഫാമിന്റെ പ്രകടനം എന്നിവ കാണുക.",
    onboardingWelcomeGetStarted: "ആരംഭിക്കുക",
    onboardingWelcomeFooter: "നിങ്ങളുടെ ഡയറി യാത്ര ഇവിടെ ആരംഭിക്കുന്നു.",
    onboardingFarmDetailsTitle: "നിങ്ങളുടെ ഫാമിനെക്കുറിച്ച് പറയൂ",
    onboardingFarmDetailsSubtitle: "നിങ്ങളുടെ ഡയറി മാനേജ്‌മെന്റ് അനുഭവം ഞങ്ങൾ വ്യക്തിഗതമാക്കും.",
    onboardingFarmDetailsFarmNameLabel: "ഫാമിന്റെ പേര്",
    onboardingFarmDetailsFarmNamePlaceholder: "നിങ്ങളുടെ ഫാമിന്റെ പേര് നൽകുക",
    onboardingFarmDetailsOwnerNameLabel: "ഉടമയുടെ പേര്",
    onboardingFarmDetailsOwnerNamePlaceholder: "ഉടമയുടെ പേര് നൽകുക",
    onboardingPhoneLabel: "ഫോൺ നമ്പർ",
    onboardingFarmDetailsPhonePlaceholder: "10-അക്ക മൊബൈൽ നമ്പർ",
    onboardingFarmDetailsEmailLabel: "ഇമെയിൽ വിലാസം",
    onboardingFarmDetailsEmailPlaceholder: "example@email.com",
    onboardingLocationTitle: "നിങ്ങളുടെ ഫാം എവിടെയാണ്?",
    onboardingLocationSubtitle: "കാലാവസ്ഥാ അപ്‌ഡേറ്റുകൾ, സമീപത്തുള്ള വെറ്ററിനറി സേവനങ്ങൾ, പ്രാദേശിക സ്ഥിതിവിവരക്കണക്കുകൾ എന്നിവ ഞങ്ങൾ വ്യക്തിഗതമാക്കും.",
    onboardingLocationVillageLabel: "ഗ്രാമം",
    onboardingLocationVillagePlaceholder: "ഗ്രാമത്തിന്റെ പേര് നൽകുക",
    onboardingLocationDistrictLabel: "ജില്ല",
    onboardingLocationDistrictPlaceholder: "ജില്ല നൽകുക",
    onboardingLocationStateLabel: "സംസ്ഥാനം",
    onboardingLocationStatePlaceholder: "സംസ്ഥാനം നൽകുക",
    onboardingLocationPincodeLabel: "പിൻ കോഡ്",
    onboardingLocationPincodePlaceholder: "6-അക്ക പിൻ കോഡ്",
    onboardingAnimalTitle: "നിങ്ങളുടെ ഫാമിലെ മൃഗങ്ങൾ",
    onboardingAnimalSubtitle: "നിലവിൽ നിങ്ങളുടെ ഉടമസ്ഥതയിലുള്ള മൃഗങ്ങളുടെ എണ്ണം ചേർക്കുക.",
    onboardingAnimalCow: "പശു",
    onboardingAnimalBuffalo: "എരുമ",
    onboardingAnimalGoat: "ആട്",
    onboardingAnimalCalf: "കിടാവ്",
    onboardingAnimalBull: "കാള",
    onboardingAnimalOthers: "മറ്റുള്ളവ",
    onboardingAnimalTotalLabel: "ആകെ മൃഗങ്ങൾ",
    onboardingAnimalSummarySubtext: "നിങ്ങളുടെ ഡാഷ്‌ബോർഡും ഫാം സ്ഥിതിവിവരക്കണക്കുകളും വ്യക്തിഗതമാക്കാൻ ഇത് ഞങ്ങളെ സഹായിക്കുന്നു.",
    onboardingPermissionTitle: "കമ്മ്യൂണിറ്റിയും അനുമതികളും",
    onboardingPermissionSubtitle: "ഇത് സാങ്കേതികമല്ലാതെ ഉപയോഗപ്രദമായി തോന്നിപ്പിക്കുക.",
    onboardingPermissionLocationTitle: "സമീപത്തുള്ള ഡയറി കർഷകരെ കണ്ടെത്തുക",
    onboardingPermissionLocationSubtitle: "പ്രാദേശിക ഉപദേശം നേടുക, തീറ്റ വാങ്ങുക/വിൽക്കുക, രോഗ മുന്നറിയിപ്പുകൾ സ്വീകരിക്കുക.",
    onboardingPermissionLocationEnable: "ലൊക്കേഷൻ അനുവദിക്കുക",
    onboardingPermissionLocationEnabled: "അനുവദിച്ചു",
    onboardingPermissionNotifTitle: "ഓർമ്മപ്പെടുത്തലുകൾ സ്വീകരിക്കുക",
    onboardingPermissionNotifSubtitle: "പ്രതിരോധ കുത്തിവയ്പ്പ് മുന്നറിയിപ്പുകൾ, പാൽ പേയ്‌മെന്റുകൾ, കമ്മ്യൂണിറ്റി അപ്‌ഡേറ്റുകൾ.",
    onboardingPermissionNotifEnable: "അറിയിപ്പുകൾ അനുവദിക്കുക",
    onboardingPermissionNotifEnabled: "അനുവദിച്ചു",
    onboardingPermissionFinish: "സെറ്റപ്പ് പൂർത്തിയാക്കുക",
    onboardingSuccessTitle: "എല്ലാം സജ്ജമായി! 🎉",
    onboardingSuccessSubtitle: "നിങ്ങളുടെ ഫാം വിജയകരമായി രജിസ്റ്റർ ചെയ്തു",
    onboardingSuccessFarmName: "ഫാമിന്റെ പേര്",
    onboardingSuccessLocation: "ലൊക്കേഷൻ",
    onboardingSuccessAnimalsAdded: "ചേർത്ത മൃഗങ്ങൾ",
    onboardingSuccessGoDashboard: "ഡാഷ്‌ബോർഡിലേക്ക് പോകുക",
    onboardingSuccessReviewDetails: "വിശദാംശങ്ങൾ പരിശോധിക്കുക",
    onboardingSuccessDefaultFarmSuffix: "ഫാം",
    voiceTitle: "വോയ്‌സ് കമാൻഡ്",
    voiceSub: "മലയാളത്തിൽ സംസാരിക്കുക",
    voiceHint: "തുടങ്ങാൻ ബട്ടൺ അമർത്തുക",
    listening: "കേൾക്കുന്നു...",
    processing: "ഗ്രഹിക്കുന്നു...",
    speakAgain: "വീണ്ടും സംസാരിക്കുക",
    sampleCommands: "ഉദാഹരണങ്ങൾ",
    voicePlaceholder: "കമാൻഡ് ടൈപ്പ് ചെയ്യുക...",
    voiceStatusRecording: "🎙 കേൾക്കുന്നു... (നിർത്താൻ വീണ്ടും അമർത്തുക)",
    voiceStatusProcessing: "⚡ ഗ്രഹിക്കുന്നു...",
    voiceStatusError: "⚠ ദയവായി വീണ്ടും ശ്രമിക്കുക",
    voiceNoMatch: "ശബ്ദം വ്യക്തമായി കേട്ടില്ല. ദയവായി ടൈപ്പ് ചെയ്യുക.",
    voiceNotUnderstood: "മനസ്സിലായില്ല. \"{text}\" — ദയവായി വീണ്ടും ശ്രമിക്കുക",
    voiceMicPermission: "ദയവായി മൈക്രോഫോൺ അനുമതി നൽകുക",
    voiceNavLabel: "നാവിഗേഷൻ",
    voiceSampleMilk: "ലക്ഷ്മി 5 ലിറ്റർ രാവിലെ",
    voiceSampleHealth: "റാണി പനി",
    voiceSampleExpense: "തീറ്റ ചെലവ് 500",
    voiceSampleNav: "ധനകാര്യ പേജിലേക്ക് പോവുക",
  },

  hi: {
    ...base,
    appName: "थुलिर फार्म",
    tagline: "आपका फार्म, आपके हाथ में",
    tabAnimals: "मेरे पशु", tabHelp: "मदद", tabMoney: "पैसा", tabToday: "आज",
    animals: "पशु", addAnimal: "पशु जोड़ें", noAnimals: "कोई पशु नहीं",
    noAnimalsHint: "+ दबाएं और पशु जोड़ें",
    filterAll: "सभी", filterCow: "गाय", filterBuffalo: "भैंस",
    filterHealthy: "स्वस्थ", filterAttention: "ध्यान दें", filterCritical: "गंभीर",
    milkLog: "दूध दर्ज", milkLogSuccess: "दूध दर्ज हो गया!", milkToday: "आज का दूध",
    milkLogTitle: "दूध दर्ज करें", session: "समय", morning: "सुबह", evening: "शाम",
    quantity: "मात्रा (लीटर)", fatPercentage: "वसा % (वैकल्पिक)", save: "सेव करें", cancel: "रद्द",
    health: "स्वास्थ्य", healthy: "स्वस्थ", attention: "ध्यान दें", critical: "गंभीर",
    income: "आय", expense: "व्यय", profit: "लाभ", loss: "हानि",
    totalIncome: "कुल आय", totalExpense: "कुल व्यय",
    addIncome: "आय जोड़ें", addExpense: "व्यय जोड़ें",
    today: "आज", goodMorning: "सुप्रभात, किसान!", goodAfternoon: "नमस्कार",
    goodEvening: "शुभ संध्या", goodNight: "शुभ रात्रि, किसान!",
    tasks: "कार्य", allTasksDone: "सभी काम पूरे!", progress: "आज की प्रगति",
    help: "समस्या और मदद", sosButton: "कुछ गलत है?", sosSub: "आपातकाल के लिए दबाएं",
    symptoms: "लक्षण चुनें", diagnose: "AI सलाह लें", diagnosing: "AI जांच रहा है...",
    emergency: "आपातकालीन संपर्क", callVet: "तुरंत पशु डॉक्टर बुलाएं", speak: "सुनें", stop: "रोकें",
    profile: "मेरी प्रोफ़ाइल", farmerName: "किसान का नाम", village: "गाँव", district: "जिला",
    phone: "फ़ोन नंबर", totalAnimals: "कुल पशु", language: "भाषा",
    logout: "लॉगआउट", editProfile: "बदलें", saveProfile: "प्रोफ़ाइल सेव करें",
    login: "लॉगिन", signup: "साइन अप",
    loginTitle: "थुलिर फार्म में स्वागत!", loginSub: "अपना मोबाइल नंबर दर्ज करें",
    signupTitle: "अपनी प्रोफ़ाइल बनाएं", signupSub: "अपने बारे में बताएं",
    sendOtp: "OTP भेजें",
    verifyOtp: "OTP जाँचें",
    otpSentTo: "OTP भेजा गया",
    enterOtp: "6-अंकों का OTP दर्ज करें",
    resendOtp: "OTP फिर से भेजें",
    resendIn: "फिर से भेजें",
    seconds: "सेकंड",
    otpExpiry: "OTP 5 मिनट में समाप्त हो जाएगा",
    wrongOtp: "गलत OTP",
    otpVerified: "सत्यापित!",
    namePlaceholder: "नाम (जैसे: रामलाल)",
    villagePlaceholder: "गाँव",
    districtPlaceholder: "जिला",
    phonePlaceholder: "10 अंकों का मोबाइल नंबर",
    farmNamePlaceholder: "फार्म का नाम (वैकल्पिक)",
    noAccount: "नए हैं?", haveAccount: "पहले से सदस्य?",
    createAccount: "नया खाता", skip: "अभी छोड़ें",
    continueBtn: "जारी रखें",
    required: "यह ज़रूरी है",
    invalidPhone: "सही 10 अंकों का मोबाइल नंबर दर्ज करें",
    success: "सफलता", error: "त्रुटि", networkError: "नेटवर्क त्रुटि",
    sync: "सेव हो गया", syncing: "सेव हो रहा है...", offline: "ऑफ़लाइन",
    demoOtpNote: "Demo OTP (परीक्षण केवल)",
    newUser: "नए किसान? प्रोफ़ाइल बनाएं",
    existingUser: "पहले से सदस्य? लॉगिन करें",
    welcomeBack: "वापस स्वागत है",
    step1of3: "चरण 1/3", step2of3: "चरण 2/3", step3of3: "चरण 3/3",
    verifying: "जाँच रहा है...",
    sending: "भेज रहा है...",
    herdTab: "झुंड", breedingTab: "प्रजनन", vaccinesTab: "टीके",
    myAnimalsTitle: "मेरे पशु", animalsCountSuffix: "पशु",
    breedingMgmt: "प्रजनन प्रबंधन", logEvent: "घटना दर्ज करें",
    noEvents: "कोई रिकॉर्ड नहीं", pregnantLabel: "गर्भवती", calvingExpected: "ब्याने की तारीख:",
    daysAgoSuffix: " दिन पहले", overdueLabel: "अवधि पूरी", daysLabel: "दिन",
    addAnimalsFirst: "पशु जोड़ें", vaccinationSchedule: "टीकाकरण अनुसूची",
    upcomingOverdue: "⏰ आगामी / अतिदेय",
    recentlyAdministered: "✅ हाल ही में दिए गए",
    noUpcomingVaccines: "कोई आगामी टीके नहीं",
    scheduleVaccineBtn: "+ टीका शेड्यूल करें",
    scheduledDateLabel: "निर्धारित तारीख:", givenDateLabel: "दी गई तारीख:",
    nextDueLabel: "अगला:", markDoneBtn: "हो गया",
    vaccineMarkTitle: "टीका दिया गया?",
    vaccineMarkBody: "आज दिया गया दर्ज करें?", yes: "हाँ",
    todayAlerts: "आज की अलर्ट", urgentLabel: "अत्यावश्यक", highLabel: "महत्वपूर्ण",
    milkDropAlert: "दूध कमी अलर्ट", milkDropSuffix: "कम हो गया",
    todayPrefix: "आज:", avgPrefix: "औसत:",
    diagnoseTab: "रोग निदान", gauguruTab: "GauGuru AI", emergencyTab: "आपातकाल",
    helpTitle: "समस्या और मदद", aiDairyAssistant: "AI डेयरी सहायक",
    whichAnimal: "कौनसा पशु? (वैकल्पिक)", additionalNotes: "अतिरिक्त नोट्स... (वैकल्पिक)",
    callNow: "अभी कॉल करें!", firstAidTips: "प्राथमिक चिकित्सा टिप्स",
    emergencySosBtn: "कुछ गलत है?", emergencySosSub: "आपातकाल के लिए दबाएं",
    quickQuestions: "⚡ त्वरित प्रश्न", gauguruSubtitle: "24/7 डेयरी विशेषज्ञ",
    chatPlaceholder: "GauGuru से पूछें...", clearChat: "साफ करें",
    thinking: "सोच रहा हूँ...", errorMsg: "माफ़ करें, त्रुटि हुई। फिर से प्रयास करें।",
    financeTitle: "वित्त", incomeTab: "आय", expenseTab: "व्यय", inventoryTab: "भंडार",
    sevenDayFinancials: "7 दिन का वित्त", totalInventoryValue: "कुल स्टॉक मूल्य",
    lowStockItems: "कम स्टॉक वाली वस्तुएं", noInventory: "कोई स्टॉक नहीं",
    addFirstItem: "+ पहली वस्तु जोड़ें", deleteConfirmTitle: "हटाएं?",
    deleteConfirmBtn: "हटाएं", deleteItemBodyPrefix: "हटाएं",
    herdStatus: "झुंड की स्थिति", morningTasks: "सुबह के कार्य", eveningTasks: "शाम के कार्य",
    loadingTasks: "कार्य लोड हो रहे हैं...", reminders: "रिमाइंडर",
    remindersSet: "रिमाइंडर सेट हो गए!", savedLabel: "सेव हो गया",
    savingLabel: "सेव हो रहा है...", expenseBreakdown: "व्यय वर्ग",
    animalDetailHealth: "स्वास्थ्य स्थिति",
    animalDetailMilkLog: "दूध दर्ज",
    animalDetailHealthNote: "स्वास्थ्य नोट",
    animalDetailMilkHistory: "7 दिन का दूध इतिहास",
    animalDetailHealthHistory: "स्वास्थ्य इतिहास",
    animalDetailRecentMilk: "हालिया दूध प्रविष्टियाँ",
    animalDetailNoNotes: "कोई नोट नहीं — ऊपर 'स्वास्थ्य नोट' दबाएं",
    animalDetailNoMilk: "कोई प्रविष्टि नहीं",
    animalDetailTagPrefix: "टैग: #",
    animalDetailDeleteTitle: "पशु हटाएं",
    animalDetailDeleteBody: "{name} को हटाना है?",
    animalDetailDeleteConfirm: "हटाएं",
    animalDetailDeleteCancel: "नहीं",
    animalDetailPhotoTitle: "फोटो लें",
    animalDetailPhotoBody: "फोटो लें या गैलरी से चुनें",
    animalDetailCamera: "📷 कैमरा",
    animalDetailGallery: "🖼 गैलरी",
    animalDetailPermissionNeeded: "अनुमति आवश्यक",
    animalDetailCameraPermission: "कैमरा एक्सेस दें",
    animalDetailGalleryPermission: "गैलरी एक्सेस दें",
    animalDetailNotFound: "पशु नहीं मिला",
    animalDetailGoBack: "वापस जाएं",
    animalDetailAddHealthNote: "स्वास्थ्य नोट जोड़ें",
    animalDetailSelectSymptom: "लक्षण/घटना चुनें",
    typeCow: "गाय",
    typeBuffalo: "भैंस",
    typeCalf: "बछड़ा",
    addAnimalTitle: "नया पशु जोड़ें",
    addAnimalSelectType: "प्रकार चुनें",
    addAnimalName: "नाम *",
    addAnimalNamePlaceholder: "जैसे: लक्ष्मी",
    addAnimalBreed: "नस्ल",
    addAnimalBreedPlaceholder: "जैसे: जर्सी, मुर्रा",
    addAnimalTag: "टैग नंबर",
    addAnimalTagPlaceholder: "जैसे: A001",
    addAnimalSave: "जोड़ें",
    addAnimalNameRequired: "पशु का नाम दर्ज करें",
    addAnimalCustomBreed: "कस्टम",
    addAnimalBreedRequired: "नस्ल चुनें",
    milkLogSelectSession: "सत्र चुनें",
    milkLogQuantityLabel: "दूध मात्रा (लीटर)",
    milkLogFatLabel: "वसा % (वैकल्पिक)",
    milkLogSaveBtn: "सेव करें",
    milkLogInvalidQty: "सही मात्रा दर्ज करें",
    quickActionFever: "बुखार",
    quickActionNotEating: "नहीं खा रहा",
    quickActionInjury: "चोट",
    quickActionInHeat: "गर्मी में",
    healthEventFever: "बुखार — Fever",
    healthEventNotEating: "नहीं खा रहा — Not Eating",
    healthEventLimping: "लंगड़ा रहा — Limping",
    healthEventDiarrhea: "दस्त — Diarrhea",
    healthEventCoughing: "खांसी — Coughing",
    healthEventVetVisit: "डॉक्टर की विज़िट — Vet Visit",
    healthEventVaccination: "टीका — Vaccination",

    // ── Onboarding ──
    languagePreference: "भाषा प्राथमिकता",
    selectLanguage: "भाषा चुनें",
    onboardingWelcomeTitle: "आपका स्वागत है\nअपचेक डेयरी",
    onboardingWelcomeSubtitle: "अपने डेयरी फार्म को अधिक स्मार्ट तरीके से प्रबंधित करें।\nपशुओं को ट्रैक करें, स्वास्थ्य की निगरानी करें, दूध उत्पादन दर्ज करें और अपने फार्म को आसानी से विकसित करें।",
    onboardingWelcomeFeature1Title: "दूध उत्पादन ट्रैकिंग",
    onboardingWelcomeFeature1Desc: "दैनिक दूध की मात्रा दर्ज करें, रुझानों की निगरानी करें और फार्म की उत्पादकता में आसानी से सुधार करें।",
    onboardingWelcomeFeature2Title: "पशु स्वास्थ्य निगरानी",
    onboardingWelcomeFeature2Desc: "प्रत्येक पशु के टीकाकरण, प्रजनन कार्यक्रम और चिकित्सा रिकॉर्ड की जानकारी पहले से रखें।",
    onboardingWelcomeFeature3Title: "स्मार्ट फार्म अंतर्दृष्टि",
    onboardingWelcomeFeature3Desc: "आसान डैशबोर्ड के माध्यम से विकास, खर्च और फार्म के प्रदर्शन को देखें।",
    onboardingWelcomeGetStarted: "शुरू करें",
    onboardingWelcomeFooter: "आपकी डेयरी यात्रा यहीं से शुरू होती है।",
    onboardingFarmDetailsTitle: "अपने फार्म के बारे में बताएं",
    onboardingFarmDetailsSubtitle: "हम आपके डेयरी प्रबंधन अनुभव को व्यक्तिगत बनाएंगे।",
    onboardingFarmDetailsFarmNameLabel: "फार्म का नाम",
    onboardingFarmDetailsFarmNamePlaceholder: "अपने फार्म का नाम दर्ज करें",
    onboardingFarmDetailsOwnerNameLabel: "मालिक का नाम",
    onboardingFarmDetailsOwnerNamePlaceholder: "मालिक का नाम दर्ज करें",
    onboardingPhoneLabel: "फ़ोन नंबर",
    onboardingFarmDetailsPhonePlaceholder: "10 अंकों का मोबाइल नंबर",
    onboardingFarmDetailsEmailLabel: "ईमेल पता",
    onboardingFarmDetailsEmailPlaceholder: "example@email.com",
    onboardingLocationTitle: "आपका फार्म कहाँ है?",
    onboardingLocationSubtitle: "हम मौसम के अपडेट, नजदीकी पशु चिकित्सा सेवाओं और स्थानीय जानकारी को व्यक्तिगत बनाएंगे।",
    onboardingLocationVillageLabel: "गाँव",
    onboardingLocationVillagePlaceholder: "गाँव का नाम दर्ज करें",
    onboardingLocationDistrictLabel: "जिला",
    onboardingLocationDistrictPlaceholder: "जिला दर्ज करें",
    onboardingLocationStateLabel: "राज्य",
    onboardingLocationStatePlaceholder: "राज्य दर्ज करें",
    onboardingLocationPincodeLabel: "पिन कोड",
    onboardingLocationPincodePlaceholder: "6 अंकों का पिन कोड",
    onboardingAnimalTitle: "आपके फार्म में पशु",
    onboardingAnimalSubtitle: "उन पशुओं की संख्या जोड़ें जो वर्तमान में आपके पास हैं।",
    onboardingAnimalCow: "गाय",
    onboardingAnimalBuffalo: "भैंस",
    onboardingAnimalGoat: "बकरी",
    onboardingAnimalCalf: "बछड़ा",
    onboardingAnimalBull: "सांड",
    onboardingAnimalOthers: "अन्य",
    onboardingAnimalTotalLabel: "कुल पशु",
    onboardingAnimalSummarySubtext: "यह आपके डैशबोर्ड और फार्म अंतर्दृष्टि को व्यक्तिगत बनाने में हमारी सहायता करता है।",
    onboardingPermissionTitle: "समुदाय और अनुमतियाँ",
    onboardingPermissionSubtitle: "इसे तकनीकी नहीं बल्कि उपयोगी महसूस कराएं।",
    onboardingPermissionLocationTitle: "नजदीकी डेयरी किसानों को खोजें",
    onboardingPermissionLocationSubtitle: "स्थानीय सलाह प्राप्त करें, चारा खरीदें/बेचें और रोग के अलर्ट प्राप्त करें।",
    onboardingPermissionLocationEnable: "स्थान सक्षम करें",
    onboardingPermissionLocationEnabled: "सक्षम किया गया",
    onboardingPermissionNotifTitle: "रिमाइंडर प्राप्त करें",
    onboardingPermissionNotifSubtitle: "टीकाकरण अलर्ट, दूध भुगतान और सामुदायिक अपडेट।",
    onboardingPermissionNotifEnable: "अधिसूचना सक्षम करें",
    onboardingPermissionNotifEnabled: "सक्षम किया गया",
    onboardingPermissionFinish: "सेटअप समाप्त करें",
    onboardingSuccessTitle: "सब कुछ तैयार है! 🎉",
    onboardingSuccessSubtitle: "आपका फार्म सफलतापूर्वक पंजीकृत हो गया है",
    onboardingSuccessFarmName: "फार्म का नाम",
    onboardingSuccessLocation: "स्थान",
    onboardingSuccessAnimalsAdded: "जोड़े गए पशु",
    onboardingSuccessGoDashboard: "डैशबोर्ड पर जाएं",
    onboardingSuccessReviewDetails: "विवरण की समीक्षा करें",
    onboardingSuccessDefaultFarmSuffix: "फार्म",
    voiceTitle: "वॉइस कमांड",
    voiceSub: "हिंदी में बोलें",
    voiceHint: "शुरू करने के लिए बटन दबाएँ",
    listening: "🎙 सुन रहा हूँ... (रोकने के लिए फिर दबाएँ)",
    processing: "⚡ समझ रहा हूँ...",
    sampleCommands: "उदाहरण कमांड",
    speakAgain: "फिर से बोलें",
    voicePlaceholder: "कमांड टाइप करें...",
    voiceStatusRecording: "🎙 सुन रहा हूँ... (रोकने के लिए फिर दबाएँ)",
    voiceStatusProcessing: "⚡ समझ रहा हूँ...",
    voiceStatusError: "⚠ कृपया पुनः प्रयास करें",
    voiceNoMatch: "आवाज स्पष्ट रूप से सुनाई नहीं दी। कृपया टेक्स्ट टाइप करें।",
    voiceNotUnderstood: "समझ नहीं आया। \"{text}\" — कृपया पुनः प्रयास करें",
    voiceMicPermission: "कृपया माइक्रोफ़ोन एक्सेस प्रदान करें",
    voiceNavLabel: "नेविगेशन",
    voiceSampleMilk: "लक्ष्मी 5 लीटर सुबह",
    voiceSampleHealth: "रानी को बुखार",
    voiceSampleExpense: "चारा खर्च 500",
    voiceSampleNav: "वित्त पृष्ठ पर जाएं",
  },
};

export type Translations = T;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: T;
}

const LanguageContext = createContext<LanguageContextType | null>(null);
const LANGUAGE_KEY = "thulirafarm_language";

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("ta");

  useEffect(() => {
    AsyncStorage.getItem(LANGUAGE_KEY).then((stored) => {
      if (stored && stored in translations) {
        setLanguageState(stored as Language);
      }
    });
  }, []);

  const setLanguage = useCallback(async (lang: Language) => {
    setLanguageState(lang);
    await AsyncStorage.setItem(LANGUAGE_KEY, lang);
  }, []);

  const t = translations[language];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
