import AsyncStorage from "@react-native-async-storage/async-storage";
import React, { createContext, useCallback, useContext, useEffect, useState } from "react";

export type Language = "ta" | "te" | "kn" | "ml" | "hi" | "en";

export const LANGUAGE_NAMES: Record<Language, string> = {
  ta: "தமிழ்",
  te: "తెలుగు",
  kn: "ಕನ್ನಡ",
  ml: "മലയാളം",
  hi: "हिंदी",
  en: "English",
};

export const LANGUAGE_NATIVE: Record<Language, { name: string; flag: string; english: string }> = {
  ta: { name: "தமிழ்", flag: "🏛️", english: "Tamil" },
  te: { name: "తెలుగు", flag: "🌺", english: "Telugu" },
  kn: { name: "ಕನ್ನಡ", flag: "🌿", english: "Kannada" },
  ml: { name: "മലയാളം", flag: "🌴", english: "Malayalam" },
  hi: { name: "हिंदी", flag: "🇮🇳", english: "Hindi" },
  en: { name: "English", flag: "🔤", english: "English" },
};

const base = {
  appName: "ThulirFarm",
  tagline: "Your Farm, In Your Hands",
  tabAnimals: "My Animals", tabHelp: "Help", tabMoney: "Money", tabToday: "Today",
  animals: "Animals", addAnimal: "Add Animal", noAnimals: "No Animals",
  noAnimalsHint: "Tap + to add your first animal",
  filterAll: "All", filterCow: "Cow", filterBuffalo: "Buffalo",
  filterHealthy: "Healthy", filterAttention: "Attention", filterCritical: "Critical",
  milkLog: "Log Milk", milkLogSuccess: "Milk logged!", milkToday: "Today's Milk",
  milkLogTitle: "Log Milk Entry", session: "Session", morning: "Morning", evening: "Evening",
  quantity: "Quantity (Litres)", fatPercentage: "Fat % (optional)", save: "Save", cancel: "Cancel",
  health: "Health", healthy: "Healthy", attention: "Needs Attention", critical: "Critical",
  income: "Income", expense: "Expense", profit: "Profit", loss: "Loss",
  totalIncome: "Total Income", totalExpense: "Total Expense",
  addIncome: "Add Income", addExpense: "Add Expense",
  today: "Today", goodMorning: "Good Morning, Farmer!", goodAfternoon: "Good Afternoon",
  goodEvening: "Good Evening", goodNight: "Good Night, Farmer!",
  tasks: "Tasks", allTasksDone: "All tasks done!", progress: "Today's Progress",
  help: "Problems & Help", sosButton: "Something Wrong?", sosSub: "Tap to call for emergency",
  symptoms: "Select Symptoms", diagnose: "Get AI Advice", diagnosing: "AI analyzing...",
  emergency: "Emergency Contacts", callVet: "Call Vet Immediately", speak: "Listen", stop: "Stop",
  profile: "My Profile", farmerName: "Farmer Name", village: "Village", district: "District",
  phone: "Phone Number", totalAnimals: "Total Animals", language: "Language",
  logout: "Log Out", editProfile: "Edit", saveProfile: "Save Profile",
  login: "Login", signup: "Sign Up",
  loginTitle: "Welcome to ThulirFarm", loginSub: "Enter your mobile number",
  signupTitle: "Complete Your Profile", signupSub: "Tell us about yourself",
  sendOtp: "Send OTP",
  verifyOtp: "Verify OTP",
  otpSentTo: "OTP sent to",
  enterOtp: "Enter 6-digit OTP",
  resendOtp: "Resend OTP",
  resendIn: "Resend in",
  seconds: "sec",
  otpExpiry: "OTP valid for 5 minutes",
  wrongOtp: "Incorrect OTP",
  otpVerified: "Verified!",
  namePlaceholder: "Your name (e.g. Murugan)",
  villagePlaceholder: "Village name",
  districtPlaceholder: "District",
  phonePlaceholder: "10-digit mobile number",
  farmNamePlaceholder: "Your farm's name (optional)",
  noAccount: "New to ThulirFarm?",
  haveAccount: "Already registered?",
  createAccount: "Create account",
  skip: "Skip for now",
  continueBtn: "Continue",
  required: "This field is required",
  invalidPhone: "Enter a valid 10-digit mobile number",
  success: "Success", error: "Error", networkError: "Network error",
  sync: "Saved", syncing: "Saving...", offline: "Offline",
  voice: "Voice", voiceTitle: "Voice Command", voiceSub: "Speak in Tamil or English",
  voiceHint: "Press the button to start", listening: "Listening...", processing: "Processing...",
  sampleCommands: "Sample Commands", speakAgain: "Speak Again",
  settingsTitle: "Settings", notifications: "Notifications",
  notifEnabled: "Notifications enabled", enableNotif: "Enable reminders",
  demoOtpNote: "Demo OTP (testing only)",
  newUser: "New farmer? Create profile",
  existingUser: "Already a member? Log in",
  welcomeBack: "Welcome back",
  step1of3: "Step 1/3", step2of3: "Step 2/3", step3of3: "Step 3/3",
  verifying: "Verifying...",
  sending: "Sending...",

  // ── Animals sub-tabs ──
  herdTab: "Herd",
  breedingTab: "Breeding",
  vaccinesTab: "Vaccines",
  myAnimalsTitle: "My Animals",
  animalsCountSuffix: "animals",

  // ── Breeding ──
  breedingMgmt: "Reproductive Management",
  logEvent: "Log Event",
  noEvents: "No events recorded",
  pregnantLabel: "Pregnant",
  calvingExpected: "Expected calving:",
  daysAgoSuffix: "d ago",
  overdueLabel: "overdue",
  daysLabel: "days",
  addAnimalsFirst: "Add animals to track breeding",

  // ── Vaccination ──
  vaccinationSchedule: "Vaccination Schedule",
  upcomingOverdue: "⏰ Upcoming / Overdue",
  recentlyAdministered: "✅ Recently Administered",
  noUpcomingVaccines: "No upcoming vaccinations",
  scheduleVaccineBtn: "+ Schedule a Vaccination",
  scheduledDateLabel: "Scheduled:",
  givenDateLabel: "Given:",
  nextDueLabel: "Next due:",
  markDoneBtn: "Done",
  vaccineMarkTitle: "Mark as Administered?",
  vaccineMarkBody: "Record as given today?",
  yes: "Yes",

  // ── Smart Alerts ──
  todayAlerts: "Today's Alerts",
  urgentLabel: "URGENT",
  highLabel: "HIGH",
  milkDropAlert: "Milk Drop Alert",
  milkDropSuffix: "drop",
  todayPrefix: "Today:",
  avgPrefix: "Avg:",

  // ── Help sub-tabs ──
  diagnoseTab: "Diagnose",
  gauguruTab: "GauGuru AI",
  emergencyTab: "Emergency",
  helpTitle: "Help & Advice",
  aiDairyAssistant: "AI Dairy Assistant",
  whichAnimal: "Which animal? (optional)",
  additionalNotes: "Additional notes... (optional)",
  callNow: "Call Now!",
  firstAidTips: "First Aid Tips",
  emergencySosBtn: "Emergency?",
  emergencySosSub: "Tap to call vet",
  quickQuestions: "⚡ Quick Questions",

  // ── GauGuru ──
  gauguruSubtitle: "24/7 Dairy Advisor",
  chatPlaceholder: "Ask GauGuru...",
  clearChat: "Clear",
  thinking: "Thinking...",
  errorMsg: "Sorry, an error occurred. Please try again.",

  // ── Money / Inventory ──
  financeTitle: "Finances",
  incomeTab: "Income",
  expenseTab: "Expenses",
  inventoryTab: "Inventory",
  sevenDayFinancials: "7-Day Financials",
  totalInventoryValue: "Total Inventory Value",
  lowStockItems: "items low on stock",
  noInventory: "No inventory items yet",
  addFirstItem: "+ Add First Item",
  deleteConfirmTitle: "Delete?",
  deleteConfirmBtn: "Delete",
  deleteItemBodyPrefix: "Delete",

  // ── Today ──
  herdStatus: "Herd Status",
  morningTasks: "Morning Tasks",
  eveningTasks: "Evening Tasks",
  loadingTasks: "Loading tasks...",
  reminders: "Reminders",
  remindersSet: "Reminders set!",
  savedLabel: "Saved",
  savingLabel: "Saving...",
  expenseBreakdown: "Expense Breakdown",

  // ── Animal Detail screen ──
  animalDetailHealth: "Health Status",
  animalDetailMilkLog: "Log Milk",
  animalDetailHealthNote: "Health Note",
  animalDetailMilkHistory: "7-Day Milk History",
  animalDetailHealthHistory: "Health History",
  animalDetailRecentMilk: "Recent Milk Entries",
  animalDetailNoNotes: "No notes — tap 'Health Note' above",
  animalDetailNoMilk: "No entries",
  animalDetailTagPrefix: "Tag: #",
  animalDetailDeleteTitle: "Delete Animal",
  animalDetailDeleteBody: "Delete {name}?",
  animalDetailDeleteConfirm: "Delete",
  animalDetailDeleteCancel: "No",
  animalDetailPhotoTitle: "Take Photo",
  animalDetailPhotoBody: "Take a photo or choose from gallery",
  animalDetailCamera: "📷 Camera",
  animalDetailGallery: "🖼 Gallery",
  animalDetailPermissionNeeded: "Permission Required",
  animalDetailCameraPermission: "Please grant camera access",
  animalDetailGalleryPermission: "Please grant gallery access",
  animalDetailNotFound: "Animal not found",
  animalDetailGoBack: "Go Back",
  animalDetailAddHealthNote: "Add Health Note",
  animalDetailSelectSymptom: "Select symptom/event",
  typeCow: "Cow",
  typeBuffalo: "Buffalo",
  typeCalf: "Calf",

  // ── AddAnimalModal ──
  addAnimalTitle: "Add New Animal",
  addAnimalSelectType: "Select Type",
  addAnimalName: "Name *",
  addAnimalNamePlaceholder: "e.g. Lakshmi",
  addAnimalBreed: "Breed",
  addAnimalBreedPlaceholder: "e.g. Jersey, Murrah",
  addAnimalTag: "Tag Number",
  addAnimalTagPlaceholder: "e.g. A001",
  addAnimalSave: "Add",
  addAnimalNameRequired: "Please enter animal name",
  addAnimalCustomBreed: "Custom",
  addAnimalBreedRequired: "Please select a breed",

  // ── MilkLogModal ──
  milkLogSelectSession: "Select Session",
  milkLogQuantityLabel: "Milk Quantity (Litres)",
  milkLogFatLabel: "Fat % (optional)",
  milkLogSaveBtn: "Save",
  milkLogInvalidQty: "Please enter a valid quantity",

  // ── AnimalCard quick actions ──
  quickActionFever: "Fever",
  quickActionNotEating: "Not Eating",
  quickActionInjury: "Injury",
  quickActionInHeat: "In Heat",

  // ── Health event options ──
  healthEventFever: "Fever",
  healthEventNotEating: "Not Eating",
  healthEventLimping: "Limping",
  healthEventDiarrhea: "Diarrhea",
  healthEventCoughing: "Coughing",
  healthEventVetVisit: "Vet Visit",
  healthEventVaccination: "Vaccination",
};

type T = typeof base;

const translations: Record<Language, T> = {
  en: { ...base },

  ta: {
    ...base,
    appName: "துளிர்பண்ணை",
    tagline: "உங்கள் பண்ணை, உங்கள் கையில்",
    tabAnimals: "என் மாடுகள்", tabHelp: "உதவி", tabMoney: "பணம்", tabToday: "இன்று",
    animals: "மாடுகள்", addAnimal: "மாடு சேர்", noAnimals: "மாடுகள் இல்லை",
    noAnimalsHint: "+ பொத்தானை அழுத்தி மாடு சேர்க்கவும்",
    filterAll: "அனைத்தும்", filterCow: "பசு", filterBuffalo: "எருமை",
    filterHealthy: "ஆரோக்கியம்", filterAttention: "கவனிக்கவும்", filterCritical: "அவசரம்",
    milkLog: "பால் பதிவு", milkLogSuccess: "பால் பதிவு ஆனது!", milkToday: "இன்று பால்",
    milkLogTitle: "பால் பதிவு செய்யவும்", session: "நேரம்", morning: "காலை", evening: "மாலை",
    quantity: "அளவு (லிட்டர்)", fatPercentage: "கொழுப்பு % (விருப்பம்)", save: "சேமி", cancel: "ரத்து",
    health: "உடல் நிலை", healthy: "ஆரோக்கியம்", attention: "கவனிக்கவும்", critical: "அவசரம்",
    income: "வருமானம்", expense: "செலவு", profit: "லாபம்", loss: "நஷ்டம்",
    totalIncome: "மொத்த வருமானம்", totalExpense: "மொத்த செலவு",
    addIncome: "வருமானம் சேர்", addExpense: "செலவு சேர்",
    today: "இன்று", goodMorning: "காலை வணக்கம், விவசாயி!", goodAfternoon: "மதிய வணக்கம்",
    goodEvening: "மாலை வணக்கம்", goodNight: "இரவு வணக்கம், விவசாயி!",
    tasks: "பணிகள்", allTasksDone: "அனைத்து பணிகளும் முடிந்தது!", progress: "இன்றைய முன்னேற்றம்",
    help: "பிரச்சனை & உதவி", sosButton: "ஏதாவது தவறா?", sosSub: "அழுத்தி அவசர உதவி பெறவும்",
    symptoms: "அறிகுறிகள் தேர்வு", diagnose: "AI ஆலோசனை பெறவும்", diagnosing: "AI பகுப்பாய்கிறது...",
    emergency: "அவசர தொடர்பு", callVet: "உடனே மருத்துவர் அழைக்கவும்", speak: "கேளு", stop: "நிறுத்து",
    profile: "என் சுயவிவரம்", farmerName: "விவசாயி பெயர்", village: "கிராமம்", district: "மாவட்டம்",
    phone: "தொலைபேசி", totalAnimals: "மொத்த மாடுகள்", language: "மொழி",
    logout: "வெளியேறு", editProfile: "திருத்து", saveProfile: "சுயவிவரம் சேமி",
    login: "உள்நுழை", signup: "பதிவு செய்",
    loginTitle: "துளிர்பண்ணைக்கு வரவேற்கிறோம்!", loginSub: "உங்கள் கைபேசி எண் உள்ளிடவும்",
    signupTitle: "உங்கள் சுயவிவரம் நிரப்பவும்", signupSub: "உங்களைப் பற்றி சொல்லுங்கள்",
    sendOtp: "OTP அனுப்பவும்",
    verifyOtp: "OTP சரிபார்க்கவும்",
    otpSentTo: "OTP அனுப்பப்பட்டது",
    enterOtp: "6 இலக்க OTP உள்ளிடவும்",
    resendOtp: "மீண்டும் OTP அனுப்பவும்",
    resendIn: "மீண்டும் அனுப்ப",
    seconds: "நொடி",
    otpExpiry: "OTP 5 நிமிடங்களில் காலாவதியாகும்",
    wrongOtp: "தவறான OTP",
    otpVerified: "சரிபார்க்கப்பட்டது!",
    namePlaceholder: "பெயர் (எ.கா: முருகன்)",
    villagePlaceholder: "கிராமம் (எ.கா: தஞ்சாவூர்)",
    districtPlaceholder: "மாவட்டம்",
    phonePlaceholder: "கைபேசி எண் (10 இலக்கம்)",
    farmNamePlaceholder: "பண்ணை பெயர் (விருப்பம்)",
    noAccount: "புதியதா?", haveAccount: "ஏற்கனவே உறுப்பினரா?",
    createAccount: "புதிய கணக்கு", skip: "இப்போது வேண்டாம்",
    continueBtn: "தொடர்க",
    required: "இது கட்டாயம்",
    invalidPhone: "சரியான கைபேசி எண் உள்ளிடவும்",
    success: "வெற்றி", error: "பிழை", networkError: "இணைப்பு பிழை",
    sync: "சேமிக்கப்பட்டது", syncing: "சேமிக்கிறது", offline: "offline",
    voice: "குரல்", voiceTitle: "குரல் கட்டளை", voiceSub: "தமிழ் அல்லது ஆங்கிலத்தில் பேசவும்",
    voiceHint: "மேலே பொத்தானை அழுத்தவும்", listening: "கேட்கிறேன்...", processing: "புரிந்துகொள்கிறேன்...",
    sampleCommands: "உதாரண கட்டளைகள்", speakAgain: "மீண்டும் சொல்",
    settingsTitle: "அமைப்புகள்", notifications: "அறிவிப்புகள்",
    notifEnabled: "அறிவிப்புகள் தயார்", enableNotif: "நினைவூட்டல் இயக்கு",
    demoOtpNote: "Demo OTP (சோதனைக்கு மட்டும்)",
    newUser: "புதிய விவசாயி? சுயவிவரம் உருவாக்கவும்",
    existingUser: "ஏற்கனவே உறுப்பினரா? உள்நுழையவும்",
    welcomeBack: "மீண்டும் வரவேற்கிறோம்",
    step1of3: "படி 1/3", step2of3: "படி 2/3", step3of3: "படி 3/3",
    verifying: "சரிபார்க்கிறது...",
    sending: "அனுப்புகிறது...",
    herdTab: "மந்தை", breedingTab: "இனப்பெருக்கம்", vaccinesTab: "தடுப்பூசி",
    myAnimalsTitle: "என் மாடுகள்", animalsCountSuffix: "மாடுகள்",
    breedingMgmt: "இனப்பெருக்க நிர்வாகம்", logEvent: "நிகழ்வு பதிவு",
    noEvents: "பதிவு இல்லை", pregnantLabel: "கர்ப்பம்", calvingExpected: "குட்டி தேதி:",
    daysAgoSuffix: " நாட்கள் முன்", overdueLabel: "கடந்தது", daysLabel: "நாட்கள்",
    addAnimalsFirst: "மாடுகள் சேர்க்கவும்", vaccinationSchedule: "தடுப்பூசி அட்டவணை",
    upcomingOverdue: "⏰ வரவிருக்கும் / கடந்த தடுப்பூசி",
    recentlyAdministered: "✅ சமீபத்தில் போட்டவை",
    noUpcomingVaccines: "தடுப்பூசி பதிவு இல்லை",
    scheduleVaccineBtn: "+ தடுப்பூசி திட்டமிடுங்கள்",
    scheduledDateLabel: "திட்டமிட்ட தேதி:", givenDateLabel: "போட்ட தேதி:",
    nextDueLabel: "அடுத்து:", markDoneBtn: "போட்டாயிற்று",
    vaccineMarkTitle: "தடுப்பூசி போட்டாயிற்றா?",
    vaccineMarkBody: "இன்று தடுப்பூசி போடப்பட்டதாக பதிவு செய்யவும்?", yes: "ஆம்",
    todayAlerts: "இன்றைய எச்சரிக்கைகள்", urgentLabel: "அவசரம்", highLabel: "முக்கியம்",
    milkDropAlert: "பால் குறைவு எச்சரிக்கை", milkDropSuffix: "குறைந்தது",
    todayPrefix: "இன்று:", avgPrefix: "சராசரி:",
    diagnoseTab: "நோய் கண்டறி", gauguruTab: "கோ குரு AI", emergencyTab: "அவசரம்",
    helpTitle: "பிரச்சனை & உதவி", aiDairyAssistant: "AI கால்நடை உதவியாளர்",
    whichAnimal: "எந்த மாடு? (விருப்பம்)", additionalNotes: "கூடுதல் குறிப்புகள்... (விருப்பம்)",
    callNow: "உடனே அழை!", firstAidTips: "முதல் உதவி குறிப்புகள்",
    emergencySosBtn: "ஏதாவது தவறா?", emergencySosSub: "அழுத்தி அவசர உதவி",
    quickQuestions: "⚡ விரைவு கேள்விகள்", gauguruSubtitle: "24/7 பண்ணை உதவியாளர்",
    chatPlaceholder: "GauGuru-ஐ கேளுங்கள்...", clearChat: "அழி",
    thinking: "யோசிக்கிறேன்...", errorMsg: "மன்னிக்கவும், பிழை ஏற்பட்டது. மீண்டும் முயற்சிக்கவும்.",
    financeTitle: "பணம்", incomeTab: "வருமானம்", expenseTab: "செலவுகள்", inventoryTab: "இருப்பு",
    sevenDayFinancials: "7 நாட்கள் நிதி", totalInventoryValue: "மொத்த இருப்பு மதிப்பு",
    lowStockItems: "பொருட்கள் குறைந்தவை", noInventory: "இருப்பு பதிவு இல்லை",
    addFirstItem: "+ பொருள் சேர்க்கவும்", deleteConfirmTitle: "நீக்கு?",
    deleteConfirmBtn: "நீக்கு", deleteItemBodyPrefix: "நீக்கவும்",
    herdStatus: "மாடுகள் நிலை", morningTasks: "காலை பணிகள்", eveningTasks: "மாலை பணிகள்",
    loadingTasks: "பணிகள் ஏற்றப்படுகின்றன...", reminders: "நினைவூட்டல்",
    remindersSet: "நினைவூட்டல் அமைக்கப்பட்டது!", savedLabel: "சேமிக்கப்பட்டது",
    savingLabel: "சேமிக்கிறது...", expenseBreakdown: "செலவு வகைகள்",
    animalDetailHealth: "உடல் நிலை",
    animalDetailMilkLog: "பால் பதிவு",
    animalDetailHealthNote: "உடல் குறிப்பு",
    animalDetailMilkHistory: "7 நாட்கள் பால் வரலாறு",
    animalDetailHealthHistory: "உடல்நிலை வரலாறு",
    animalDetailRecentMilk: "சமீபத்திய பால் பதிவுகள்",
    animalDetailNoNotes: "குறிப்புகள் இல்லை — மேலே 'உடல் குறிப்பு' அழுத்தவும்",
    animalDetailNoMilk: "பதிவுகள் இல்லை",
    animalDetailTagPrefix: "குறி: #",
    animalDetailDeleteTitle: "மாடு நீக்கு",
    animalDetailDeleteBody: "{name} ஐ நீக்கவா?",
    animalDetailDeleteConfirm: "நீக்கு",
    animalDetailDeleteCancel: "இல்லை",
    animalDetailPhotoTitle: "புகைப்படம் எடுக்கவும்",
    animalDetailPhotoBody: "புகைப்படம் எடுக்கவும் அல்லது கேலரியில் இருந்து தேர்வு செய்யவும்",
    animalDetailCamera: "📷 கேமரா",
    animalDetailGallery: "🖼 கேலரி",
    animalDetailPermissionNeeded: "அனுமதி தேவை",
    animalDetailCameraPermission: "கேமரா அணுகல் வழங்கவும்",
    animalDetailGalleryPermission: "கேலரி அணுகல் வழங்கவும்",
    animalDetailNotFound: "மாடு கிடைக்கவில்லை",
    animalDetailGoBack: "திரும்பு",
    animalDetailAddHealthNote: "உடல்நிலை குறிப்பு சேர்க்கவும்",
    animalDetailSelectSymptom: "அறிகுறி/நிகழ்வு தேர்வு செய்யவும்",
    typeCow: "பசு",
    typeBuffalo: "எருமை",
    typeCalf: "கன்று",
    addAnimalTitle: "புதிய மாடு சேர்க்கவும்",
    addAnimalSelectType: "வகை தேர்வு",
    addAnimalName: "பெயர் *",
    addAnimalNamePlaceholder: "உதா: லட்சுமி",
    addAnimalBreed: "ரகம்",
    addAnimalBreedPlaceholder: "உதா: ஜெர்சி, முர்ராஹ்",
    addAnimalTag: "குறி எண்",
    addAnimalTagPlaceholder: "உதா: A001",
    addAnimalSave: "சேர்க்கவும்",
    addAnimalNameRequired: "மாடு பெயர் உள்ளிடவும்",
    addAnimalCustomBreed: "தனிப்பயன்",
    addAnimalBreedRequired: "இனம் தேர்வு செய்யவும்",
    milkLogSelectSession: "அமர்வு தேர்வு",
    milkLogQuantityLabel: "பால் அளவு (லிட்டர்)",
    milkLogFatLabel: "கொழுப்பு % (விருப்பம்)",
    milkLogSaveBtn: "சேமி",
    milkLogInvalidQty: "சரியான அளவை உள்ளிடவும்",
    quickActionFever: "காய்ச்சல்",
    quickActionNotEating: "சாப்பிடவில்லை",
    quickActionInjury: "காயம்",
    quickActionInHeat: "ஈட்டு",
    healthEventFever: "காய்ச்சல் — Fever",
    healthEventNotEating: "சாப்பிடவில்லை — Not Eating",
    healthEventLimping: "கால் வலி — Limping",
    healthEventDiarrhea: "வயிற்றுப்போக்கு — Diarrhea",
    healthEventCoughing: "இருமல் — Coughing",
    healthEventVetVisit: "மருத்துவர் வருகை — Vet Visit",
    healthEventVaccination: "தடுப்பூசி — Vaccination",
  },

  te: {
    ...base,
    appName: "థులిర్‌ఫార్మ్",
    tagline: "మీ పొలం, మీ చేతిలో",
    tabAnimals: "నా జంతువులు", tabHelp: "సహాయం", tabMoney: "డబ్బు", tabToday: "నేడు",
    animals: "జంతువులు", addAnimal: "జంతువు జోడించు", noAnimals: "జంతువులు లేవు",
    noAnimalsHint: "+ నొక్కి జంతువు జోడించండి",
    filterAll: "అన్నీ", filterCow: "ఆవు", filterBuffalo: "గేదె",
    filterHealthy: "ఆరోగ్యకరమైన", filterAttention: "శ్రద్ధ అవసరం", filterCritical: "అత్యవసరం",
    milkLog: "పాలు నమోదు", milkLogSuccess: "పాలు నమోదయ్యాయి!", milkToday: "నేడు పాలు",
    milkLogTitle: "పాలు నమోదు చేయండి", session: "సమయం", morning: "ఉదయం", evening: "సాయంత్రం",
    quantity: "పరిమాణం (లీటర్లు)", fatPercentage: "కొవ్వు % (ఐచ్ఛికం)", save: "సేవ్", cancel: "రద్దు",
    health: "ఆరోగ్యం", healthy: "ఆరోగ్యకరమైన", attention: "శ్రద్ధ అవసరం", critical: "అత్యవసరం",
    income: "ఆదాయం", expense: "వ్యయం", profit: "లాభం", loss: "నష్టం",
    totalIncome: "మొత్తం ఆదాయం", totalExpense: "మొత్తం వ్యయం",
    addIncome: "ఆదాయం జోడించు", addExpense: "వ్యయం జోడించు",
    today: "నేడు", goodMorning: "శుభోదయం, రైతు!", goodAfternoon: "శుభమధ్యాహ్నం",
    goodEvening: "శుభసాయంత్రం", goodNight: "శుభరాత్రి, రైతు!",
    tasks: "పనులు", allTasksDone: "అన్ని పనులు పూర్తయ్యాయి!", progress: "నేటి పురోగతి",
    help: "సమస్య & సహాయం", sosButton: "ఏదైనా తప్పు జరిగిందా?", sosSub: "అత్యవసర సహాయం కోసం నొక్కండి",
    symptoms: "లక్షణాలు ఎంచుకోండి", diagnose: "AI సలహా పొందండి", diagnosing: "AI విశ్లేషిస్తోంది...",
    emergency: "అత్యవసర సంప్రదింపులు", callVet: "వెంటనే వైద్యుని పిలవండి", speak: "వినండి", stop: "ఆపు",
    profile: "నా వివరాలు", farmerName: "రైతు పేరు", village: "గ్రామం", district: "జిల్లా",
    phone: "ఫోన్ నంబర్", totalAnimals: "మొత్తం జంతువులు", language: "భాష",
    logout: "లాగ్అవుట్", editProfile: "సవరించు", saveProfile: "వివరాలు సేవ్ చేయి",
    login: "లాగిన్", signup: "నమోదు",
    loginTitle: "థులిర్‌ఫార్మ్‌కు స్వాగతం!", loginSub: "మీ మొబైల్ నంబర్ నమోదు చేయండి",
    signupTitle: "మీ వివరాలు నమోదు చేయండి", signupSub: "మీ గురించి చెప్పండి",
    sendOtp: "OTP పంపండి",
    verifyOtp: "OTP ధృవీకరించండి",
    otpSentTo: "OTP పంపబడింది",
    enterOtp: "6-అంకె OTP నమోదు చేయండి",
    resendOtp: "OTP మళ్ళీ పంపండి",
    resendIn: "మళ్ళీ పంపు",
    seconds: "సెకన్లు",
    otpExpiry: "OTP 5 నిమిషాలలో గడువు ముగుస్తుంది",
    wrongOtp: "తప్పు OTP",
    otpVerified: "ధృవీకరించబడింది!",
    namePlaceholder: "పేరు (ఉదా: రాములు)",
    villagePlaceholder: "గ్రామం",
    districtPlaceholder: "జిల్లా",
    phonePlaceholder: "10-అంకె మొబైల్ నంబర్",
    farmNamePlaceholder: "పొలం పేరు (ఐచ్ఛికం)",
    noAccount: "కొత్తగా వచ్చారా?", haveAccount: "ఇప్పటికే సభ్యులా?",
    createAccount: "కొత్త ఖాతా", skip: "ఇప్పుడు వద్దు",
    continueBtn: "కొనసాగించు",
    required: "ఇది తప్పనిసరి",
    invalidPhone: "సరైన 10-అంకె మొబైల్ నంబర్ నమోదు చేయండి",
    success: "విజయం", error: "లోపం", networkError: "నెట్‌వర్క్ లోపం",
    sync: "సేవ్ చేయబడింది", syncing: "సేవ్ అవుతోంది...", offline: "ఆఫ్‌లైన్",
    demoOtpNote: "Demo OTP (పరీక్ష మాత్రమే)",
    newUser: "కొత్త రైతు? ప్రొఫైల్ తయారు చేయండి",
    existingUser: "ఇప్పటికే సభ్యులా? లాగిన్ అవ్వండి",
    welcomeBack: "తిరిగి స్వాగతం",
    step1of3: "దశ 1/3", step2of3: "దశ 2/3", step3of3: "దశ 3/3",
    verifying: "ధృవీకరిస్తోంది...",
    sending: "పంపుతోంది...",
    herdTab: "మంద", breedingTab: "పునరుత్పత్తి", vaccinesTab: "టీకాలు",
    myAnimalsTitle: "నా జంతువులు", animalsCountSuffix: "జంతువులు",
    breedingMgmt: "పునరుత్పత్తి నిర్వహణ", logEvent: "ఘటన నమోదు",
    noEvents: "నమోదు లేదు", pregnantLabel: "గర్భం", calvingExpected: "ప్రసవ తేదీ:",
    daysAgoSuffix: " రోజుల క్రితం", overdueLabel: "గడువు మించింది", daysLabel: "రోజులు",
    addAnimalsFirst: "జంతువులను జోడించండి", vaccinationSchedule: "టీకా షెడ్యూల్",
    upcomingOverdue: "⏰ రానున్న / గడువు మించిన",
    recentlyAdministered: "✅ ఇటీవల ఇచ్చినవి",
    noUpcomingVaccines: "రానున్న టీకాలు లేవు",
    scheduleVaccineBtn: "+ టీకా షెడ్యూల్ చేయండి",
    scheduledDateLabel: "నిర్ణయించిన తేదీ:", givenDateLabel: "ఇచ్చిన తేదీ:",
    nextDueLabel: "తర్వాత:", markDoneBtn: "పూర్తి",
    vaccineMarkTitle: "టీకా ఇవ్వబడిందా?",
    vaccineMarkBody: "ఈరోజు ఇచ్చినట్టు నమోదు చేయాలా?", yes: "అవును",
    todayAlerts: "నేటి హెచ్చరికలు", urgentLabel: "అత్యవసరం", highLabel: "ముఖ్యం",
    milkDropAlert: "పాల తగ్గుదల హెచ్చరిక", milkDropSuffix: "తగ్గింది",
    todayPrefix: "నేడు:", avgPrefix: "సగటు:",
    diagnoseTab: "రోగ నిర్ధారణ", gauguruTab: "GauGuru AI", emergencyTab: "అత్యవసరం",
    helpTitle: "సమస్య & సహాయం", aiDairyAssistant: "AI పాడి సహాయకుడు",
    whichAnimal: "ఏ జంతువు? (ఐచ్ఛికం)", additionalNotes: "అదనపు గమనికలు... (ఐచ్ఛికం)",
    callNow: "ఇప్పుడే పిలవండి!", firstAidTips: "ప్రాథమిక చికిత్స చిట్కాలు",
    emergencySosBtn: "ఏదైనా తప్పా?", emergencySosSub: "అత్యవసర సహాయానికి నొక్కండి",
    quickQuestions: "⚡ త్వరిత ప్రశ్నలు", gauguruSubtitle: "24/7 పాడి నిపుణుడు",
    chatPlaceholder: "GauGuru ని అడగండి...", clearChat: "తొలగించు",
    thinking: "ఆలోచిస్తున్నాను...", errorMsg: "క్షమించండి, దోషం సంభవించింది. మళ్ళీ ప్రయత్నించండి.",
    financeTitle: "ఆర్థికం", incomeTab: "ఆదాయం", expenseTab: "వ్యయాలు", inventoryTab: "సూచీ",
    sevenDayFinancials: "7 రోజుల ఆర్థికం", totalInventoryValue: "మొత్తం సూచీ విలువ",
    lowStockItems: "వస్తువులు తక్కువగా ఉన్నాయి", noInventory: "సూచీ లేదు",
    addFirstItem: "+ మొదటి వస్తువు జోడించు", deleteConfirmTitle: "తొలగించాలా?",
    deleteConfirmBtn: "తొలగించు", deleteItemBodyPrefix: "తొలగించు",
    herdStatus: "మంద స్థితి", morningTasks: "ఉదయం పనులు", eveningTasks: "సాయంత్రం పనులు",
    loadingTasks: "పనులు లోడవుతున్నాయి...", reminders: "రిమైండర్లు",
    remindersSet: "రిమైండర్లు సెట్ చేశారు!", savedLabel: "సేవ్ చేయబడింది",
    savingLabel: "సేవ్ అవుతోంది...", expenseBreakdown: "వ్యయ వర్గాలు",
    animalDetailHealth: "ఆరోగ్య స్థితి",
    animalDetailMilkLog: "పాలు నమోదు",
    animalDetailHealthNote: "ఆరోగ్య గమనిక",
    animalDetailMilkHistory: "7 రోజుల పాల చరిత్ర",
    animalDetailHealthHistory: "ఆరోగ్య చరిత్ర",
    animalDetailRecentMilk: "ఇటీవలి పాల నమోదులు",
    animalDetailNoNotes: "గమనికలు లేవు — పైన 'ఆరోగ్య గమనిక' నొక్కండి",
    animalDetailNoMilk: "నమోదులు లేవు",
    animalDetailTagPrefix: "ట్యాగ్: #",
    animalDetailDeleteTitle: "పశువును తొలగించు",
    animalDetailDeleteBody: "{name} ను తొలగించాలా?",
    animalDetailDeleteConfirm: "తొలగించు",
    animalDetailDeleteCancel: "వద్దు",
    animalDetailPhotoTitle: "ఫోటో తీయండి",
    animalDetailPhotoBody: "ఫోటో తీయండి లేదా గ్యాలరీ నుండి ఎంచుకోండి",
    animalDetailCamera: "📷 కెమెరా",
    animalDetailGallery: "🖼 గ్యాలరీ",
    animalDetailPermissionNeeded: "అనుమతి అవసరం",
    animalDetailCameraPermission: "కెమెరా యాక్సెస్ ఇవ్వండి",
    animalDetailGalleryPermission: "గ్యాలరీ యాక్సెస్ ఇవ్వండి",
    animalDetailNotFound: "పశువు కనబడలేదు",
    animalDetailGoBack: "వెనక్కి",
    animalDetailAddHealthNote: "ఆరోగ్య గమనిక చేర్చు",
    animalDetailSelectSymptom: "లక్షణం/సంఘటన ఎంచుకోండి",
    typeCow: "ఆవు",
    typeBuffalo: "గేదె",
    typeCalf: "దూడ",
    addAnimalTitle: "కొత్త పశువు చేర్చు",
    addAnimalSelectType: "రకం ఎంచుకోండి",
    addAnimalName: "పేరు *",
    addAnimalNamePlaceholder: "ఉదా: లక్ష్మి",
    addAnimalBreed: "జాతి",
    addAnimalBreedPlaceholder: "ఉదా: జెర్సీ, మురా",
    addAnimalTag: "ట్యాగ్ నంబర్",
    addAnimalTagPlaceholder: "ఉదా: A001",
    addAnimalSave: "చేర్చు",
    addAnimalNameRequired: "పశువు పేరు నమోదు చేయండి",
    addAnimalCustomBreed: "కస్టమ్",
    addAnimalBreedRequired: "జాతి ఎంచుకోండి",
    milkLogSelectSession: "సెషన్ ఎంచుకోండి",
    milkLogQuantityLabel: "పాల పరిమాణం (లీటర్లు)",
    milkLogFatLabel: "కొవ్వు % (ఐచ్ఛికం)",
    milkLogSaveBtn: "సేవ్ చేయి",
    milkLogInvalidQty: "సరైన పరిమాణం నమోదు చేయండి",
    quickActionFever: "జ్వరం",
    quickActionNotEating: "తినడం లేదు",
    quickActionInjury: "గాయం",
    quickActionInHeat: "ఎదకు వచ్చింది",
    healthEventFever: "జ్వరం — Fever",
    healthEventNotEating: "తినడం లేదు — Not Eating",
    healthEventLimping: "కుంటుతోంది — Limping",
    healthEventDiarrhea: "విరేచనాలు — Diarrhea",
    healthEventCoughing: "దగ్గు — Coughing",
    healthEventVetVisit: "డాక్టర్ సందర్శన — Vet Visit",
    healthEventVaccination: "టీకా — Vaccination",
  },

  kn: {
    ...base,
    appName: "ತುಳಿರ್‌ಫಾರ್ಮ್",
    tagline: "ನಿಮ್ಮ ತೋಟ, ನಿಮ್ಮ ಕೈಯಲ್ಲಿ",
    tabAnimals: "ನನ್ನ ಪ್ರಾಣಿಗಳು", tabHelp: "ಸಹಾಯ", tabMoney: "ಹಣ", tabToday: "ಇಂದು",
    animals: "ಪ್ರಾಣಿಗಳು", addAnimal: "ಪ್ರಾಣಿ ಸೇರಿಸಿ", noAnimals: "ಪ್ರಾಣಿಗಳಿಲ್ಲ",
    noAnimalsHint: "+ ಒತ್ತಿ ಪ್ರಾಣಿ ಸೇರಿಸಿ",
    filterAll: "ಎಲ್ಲ", filterCow: "ಹಸು", filterBuffalo: "ಕೋಣ",
    filterHealthy: "ಆರೋಗ್ಯಕರ", filterAttention: "ಗಮನ ಬೇಕು", filterCritical: "ತುರ್ತು",
    milkLog: "ಹಾಲು ದಾಖಲು", milkLogSuccess: "ಹಾಲು ದಾಖಲಾಯಿತು!", milkToday: "ಇಂದಿನ ಹಾಲು",
    milkLogTitle: "ಹಾಲು ದಾಖಲಿಸಿ", session: "ಸಮಯ", morning: "ಬೆಳಿಗ್ಗೆ", evening: "ಸಂಜೆ",
    quantity: "ಪ್ರಮಾಣ (ಲೀಟರ್)", fatPercentage: "ಕೊಬ್ಬು % (ಐಚ್ಛಿಕ)", save: "ಉಳಿಸಿ", cancel: "ರದ್ದು",
    health: "ಆರೋಗ್ಯ", healthy: "ಆರೋಗ್ಯಕರ", attention: "ಗಮನ ಬೇಕು", critical: "ತುರ್ತು",
    income: "ಆದಾಯ", expense: "ವೆಚ್ಚ", profit: "ಲಾಭ", loss: "ನಷ್ಟ",
    totalIncome: "ಒಟ್ಟು ಆದಾಯ", totalExpense: "ಒಟ್ಟು ವೆಚ್ಚ",
    addIncome: "ಆದಾಯ ಸೇರಿಸಿ", addExpense: "ವೆಚ್ಚ ಸೇರಿಸಿ",
    today: "ಇಂದು", goodMorning: "ಶುಭೋದಯ, ರೈತ!", goodAfternoon: "ಶುಭ ಮಧ್ಯಾಹ್ನ",
    goodEvening: "ಶುಭ ಸಂಜೆ", goodNight: "ಶುಭ ರಾತ್ರಿ, ರೈತ!",
    tasks: "ಕೆಲಸಗಳು", allTasksDone: "ಎಲ್ಲ ಕೆಲಸ ಮುಗಿಯಿತು!", progress: "ಇಂದಿನ ಪ್ರಗತಿ",
    help: "ಸಮಸ್ಯೆ & ಸಹಾಯ", sosButton: "ಏನಾದರೂ ತಪ್ಪಾಯಿತೇ?", sosSub: "ತುರ್ತು ಸಹಾಯಕ್ಕೆ ಒತ್ತಿ",
    symptoms: "ರೋಗಲಕ್ಷಣಗಳು ಆರಿಸಿ", diagnose: "AI ಸಲಹೆ ಪಡೆಯಿರಿ", diagnosing: "AI ವಿಶ್ಲೇಷಿಸುತ್ತಿದೆ...",
    emergency: "ತುರ್ತು ಸಂಪರ್ಕಗಳು", callVet: "ತಕ್ಷಣ ಪಶು ವೈದ್ಯರನ್ನು ಕರೆಯಿರಿ", speak: "ಕೇಳಿ", stop: "ನಿಲ್ಲಿಸಿ",
    profile: "ನನ್ನ ಪ್ರೊಫೈಲ್", farmerName: "ರೈತರ ಹೆಸರು", village: "ಗ್ರಾಮ", district: "ಜಿಲ್ಲೆ",
    phone: "ಫೋನ್ ಸಂಖ್ಯೆ", totalAnimals: "ಒಟ್ಟು ಪ್ರಾಣಿಗಳು", language: "ಭಾಷೆ",
    logout: "ಲಾಗ್ ಔಟ್", editProfile: "ತಿದ್ದಿ", saveProfile: "ಪ್ರೊಫೈಲ್ ಉಳಿಸಿ",
    login: "ಲಾಗಿನ್", signup: "ನೋಂದಣಿ",
    loginTitle: "ತುಳಿರ್‌ಫಾರ್ಮ್‌ಗೆ ಸ್ವಾಗತ!", loginSub: "ನಿಮ್ಮ ಮೊಬೈಲ್ ನಂಬರ್ ನಮೂದಿಸಿ",
    signupTitle: "ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಪೂರ್ಣಗೊಳಿಸಿ", signupSub: "ನಿಮ್ಮ ಬಗ್ಗೆ ಹೇಳಿ",
    sendOtp: "OTP ಕಳುಹಿಸಿ",
    verifyOtp: "OTP ದೃಢೀಕರಿಸಿ",
    otpSentTo: "OTP ಕಳುಹಿಸಲಾಗಿದೆ",
    enterOtp: "6-ಅಂಕಿ OTP ನಮೂದಿಸಿ",
    resendOtp: "OTP ಮತ್ತೆ ಕಳುಹಿಸಿ",
    resendIn: "ಮತ್ತೆ ಕಳುಹಿಸು",
    seconds: "ಸೆಕೆಂಡ್",
    otpExpiry: "OTP 5 ನಿಮಿಷಗಳಲ್ಲಿ ಅವಧಿ ಮೀರುತ್ತದೆ",
    wrongOtp: "ತಪ್ಪು OTP",
    otpVerified: "ದೃಢೀಕರಿಸಲಾಗಿದೆ!",
    namePlaceholder: "ಹೆಸರು (ಉದಾ: ರಾಮಪ್ಪ)",
    villagePlaceholder: "ಗ್ರಾಮ",
    districtPlaceholder: "ಜಿಲ್ಲೆ",
    phonePlaceholder: "10-ಅಂಕಿ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
    farmNamePlaceholder: "ತೋಟದ ಹೆಸರು (ಐಚ್ಛಿಕ)",
    noAccount: "ಹೊಸಬರೇ?", haveAccount: "ಈಗಾಗಲೇ ಸದಸ್ಯರೇ?",
    createAccount: "ಹೊಸ ಖಾತೆ", skip: "ಈಗ ಬೇಡ",
    continueBtn: "ಮುಂದುವರಿಸಿ",
    required: "ಇದು ಅಗತ್ಯ",
    invalidPhone: "ಸರಿಯಾದ 10-ಅಂಕಿ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ",
    success: "ಯಶಸ್ಸು", error: "ದೋಷ", networkError: "ನೆಟ್‌ವರ್ಕ್ ದೋಷ",
    sync: "ಉಳಿಸಲಾಗಿದೆ", syncing: "ಉಳಿಸುತ್ತಿದೆ...", offline: "ಆಫ್‌ಲೈನ್",
    demoOtpNote: "Demo OTP (ಪರೀಕ್ಷೆಗಾಗಿ ಮಾತ್ರ)",
    newUser: "ಹೊಸ ರೈತ? ಪ್ರೊಫೈಲ್ ತಯಾರಿಸಿ",
    existingUser: "ಈಗಾಗಲೇ ಸದಸ್ಯರೇ? ಲಾಗಿನ್ ಅಗಿ",
    welcomeBack: "ಮತ್ತೆ ಸ್ವಾಗತ",
    step1of3: "ಹಂತ 1/3", step2of3: "ಹಂತ 2/3", step3of3: "ಹಂತ 3/3",
    verifying: "ದೃಢೀಕರಿಸುತ್ತಿದೆ...",
    sending: "ಕಳುಹಿಸುತ್ತಿದೆ...",
    herdTab: "ಹಿಂಡು", breedingTab: "ಸಂತಾನೋತ್ಪತ್ತಿ", vaccinesTab: "ಲಸಿಕೆಗಳು",
    myAnimalsTitle: "ನನ್ನ ಪ್ರಾಣಿಗಳು", animalsCountSuffix: "ಪ್ರಾಣಿಗಳು",
    breedingMgmt: "ಸಂತಾನೋತ್ಪತ್ತಿ ನಿರ್ವಹಣೆ", logEvent: "ಘಟನೆ ದಾಖಲಿಸಿ",
    noEvents: "ದಾಖಲೆ ಇಲ್ಲ", pregnantLabel: "ಗರ್ಭ", calvingExpected: "ಹೆರಿಗೆ ದಿನ:",
    daysAgoSuffix: " ದಿನಗಳ ಹಿಂದೆ", overdueLabel: "ಗಡುವು ಮೀರಿದೆ", daysLabel: "ದಿನಗಳು",
    addAnimalsFirst: "ಪ್ರಾಣಿಗಳನ್ನು ಸೇರಿಸಿ", vaccinationSchedule: "ಲಸಿಕೆ ವೇಳಾಪಟ್ಟಿ",
    upcomingOverdue: "⏰ ಮುಂದಿನ / ಗಡುವು ಮೀರಿದ",
    recentlyAdministered: "✅ ಇತ್ತೀಚೆಗೆ ನೀಡಿದವು",
    noUpcomingVaccines: "ಮುಂದಿನ ಲಸಿಕೆಗಳಿಲ್ಲ",
    scheduleVaccineBtn: "+ ಲಸಿಕೆ ನಿಗದಿಪಡಿಸಿ",
    scheduledDateLabel: "ನಿಗದಿ ದಿನ:", givenDateLabel: "ನೀಡಿದ ದಿನ:",
    nextDueLabel: "ಮುಂದಿನ:", markDoneBtn: "ಮುಗಿಯಿತು",
    vaccineMarkTitle: "ಲಸಿಕೆ ನೀಡಿದ್ದೀರಾ?",
    vaccineMarkBody: "ಇಂದು ನೀಡಿದ್ದಾಗಿ ದಾಖಲಿಸಬೇಕೇ?", yes: "ಹೌದು",
    todayAlerts: "ಇಂದಿನ ಎಚ್ಚರಿಕೆಗಳು", urgentLabel: "ತುರ್ತು", highLabel: "ಪ್ರಮುಖ",
    milkDropAlert: "ಹಾಲು ಕಡಿಮೆ ಎಚ್ಚರಿಕೆ", milkDropSuffix: "ಕಡಿಮೆಯಾಗಿದೆ",
    todayPrefix: "ಇಂದು:", avgPrefix: "ಸರಾಸರಿ:",
    diagnoseTab: "ರೋಗ ನಿರ್ಣಯ", gauguruTab: "GauGuru AI", emergencyTab: "ತುರ್ತು",
    helpTitle: "ಸಮಸ್ಯೆ & ಸಹಾಯ", aiDairyAssistant: "AI ಹಾಲು ಸಹಾಯಕ",
    whichAnimal: "ಯಾವ ಪ್ರಾಣಿ? (ಐಚ್ಛಿಕ)", additionalNotes: "ಹೆಚ್ಚಿನ ಟಿಪ್ಪಣಿ... (ಐಚ್ಛಿಕ)",
    callNow: "ತಕ್ಷಣ ಕರೆಯಿರಿ!", firstAidTips: "ಪ್ರಥಮ ಚಿಕಿತ್ಸೆ ಸಲಹೆಗಳು",
    emergencySosBtn: "ಏನಾದರೂ ತಪ್ಪಾಯಿತೇ?", emergencySosSub: "ತುರ್ತು ಸಹಾಯಕ್ಕೆ ಒತ್ತಿ",
    quickQuestions: "⚡ ತ್ವರಿತ ಪ್ರಶ್ನೆಗಳು", gauguruSubtitle: "24/7 ಹಾಲು ತಜ್ಞ",
    chatPlaceholder: "GauGuru ಕೇಳಿ...", clearChat: "ಅಳಿಸು",
    thinking: "ಯೋಚಿಸುತ್ತಿದ್ದೇನೆ...", errorMsg: "ಕ್ಷಮಿಸಿ, ದೋಷ ಸಂಭವಿಸಿದೆ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    financeTitle: "ಹಣಕಾಸು", incomeTab: "ಆದಾಯ", expenseTab: "ವೆಚ್ಚಗಳು", inventoryTab: "ದಾಸ್ತಾನು",
    sevenDayFinancials: "7 ದಿನಗಳ ಹಣಕಾಸು", totalInventoryValue: "ಒಟ್ಟು ದಾಸ್ತಾನು ಮೌಲ್ಯ",
    lowStockItems: "ವಸ್ತುಗಳ ದಾಸ್ತಾನು ಕಡಿಮೆ", noInventory: "ದಾಸ್ತಾನು ಇಲ್ಲ",
    addFirstItem: "+ ಮೊದಲ ವಸ್ತು ಸೇರಿಸಿ", deleteConfirmTitle: "ಅಳಿಸಬೇಕೇ?",
    deleteConfirmBtn: "ಅಳಿಸಿ", deleteItemBodyPrefix: "ಅಳಿಸಿ",
    herdStatus: "ಹಿಂಡಿನ ಸ್ಥಿತಿ", morningTasks: "ಬೆಳಿಗ್ಗೆ ಕೆಲಸಗಳು", eveningTasks: "ಸಂಜೆ ಕೆಲಸಗಳು",
    loadingTasks: "ಕೆಲಸಗಳು ಲೋಡ್ ಆಗುತ್ತಿವೆ...", reminders: "ಜ್ಞಾಪನಗಳು",
    remindersSet: "ಜ್ಞಾಪನಗಳು ಸಿದ್ಧ!", savedLabel: "ಉಳಿಸಲಾಗಿದೆ",
    savingLabel: "ಉಳಿಸುತ್ತಿದೆ...", expenseBreakdown: "ವೆಚ್ಚ ವರ್ಗಗಳು",
    animalDetailHealth: "ಆರೋಗ್ಯ ಸ್ಥಿತಿ",
    animalDetailMilkLog: "ಹಾಲು ದಾಖಲು",
    animalDetailHealthNote: "ಆರೋಗ್ಯ ಟಿಪ್ಪಣಿ",
    animalDetailMilkHistory: "7 ದಿನಗಳ ಹಾಲಿನ ಇತಿಹಾಸ",
    animalDetailHealthHistory: "ಆರೋಗ್ಯ ಇತಿಹಾಸ",
    animalDetailRecentMilk: "ಇತ್ತೀಚಿನ ಹಾಲಿನ ದಾಖಲೆಗಳು",
    animalDetailNoNotes: "ಟಿಪ್ಪಣಿಗಳಿಲ್ಲ — ಮೇಲೆ 'ಆರೋಗ್ಯ ಟಿಪ್ಪಣಿ' ಒತ್ತಿ",
    animalDetailNoMilk: "ದಾಖಲೆಗಳಿಲ್ಲ",
    animalDetailTagPrefix: "ಟ್ಯಾಗ್: #",
    animalDetailDeleteTitle: "ಪ್ರಾಣಿ ತೆಗೆದುಹಾಕು",
    animalDetailDeleteBody: "{name} ಅನ್ನು ತೆಗೆದುಹಾಕಬೇಕೇ?",
    animalDetailDeleteConfirm: "ತೆಗೆದುಹಾಕು",
    animalDetailDeleteCancel: "ಬೇಡ",
    animalDetailPhotoTitle: "ಫೋಟೋ ತೆಗೆಯಿರಿ",
    animalDetailPhotoBody: "ಫೋಟೋ ತೆಗೆಯಿರಿ ಅಥವಾ ಗ್ಯಾಲರಿಯಿಂದ ಆಯ್ಕೆ ಮಾಡಿ",
    animalDetailCamera: "📷 ಕ್ಯಾಮೆರಾ",
    animalDetailGallery: "🖼 ಗ್ಯಾಲರಿ",
    animalDetailPermissionNeeded: "ಅನುಮತಿ ಬೇಕು",
    animalDetailCameraPermission: "ಕ್ಯಾಮೆರಾ ಪ್ರವೇಶ ನೀಡಿ",
    animalDetailGalleryPermission: "ಗ್ಯಾಲರಿ ಪ್ರವೇಶ ನೀಡಿ",
    animalDetailNotFound: "ಪ್ರಾಣಿ ಸಿಗಲಿಲ್ಲ",
    animalDetailGoBack: "ಹಿಂದೆ ಹೋಗಿ",
    animalDetailAddHealthNote: "ಆರೋಗ್ಯ ಟಿಪ್ಪಣಿ ಸೇರಿಸಿ",
    animalDetailSelectSymptom: "ಲಕ್ಷಣ/ಘಟನೆ ಆಯ್ಕೆ ಮಾಡಿ",
    typeCow: "ಹಸು",
    typeBuffalo: "ಎಮ್ಮೆ",
    typeCalf: "ಕರು",
    addAnimalTitle: "ಹೊಸ ಪ್ರಾಣಿ ಸೇರಿಸಿ",
    addAnimalSelectType: "ವಿಧ ಆಯ್ಕೆ ಮಾಡಿ",
    addAnimalName: "ಹೆಸರು *",
    addAnimalNamePlaceholder: "ಉದಾ: ಲಕ್ಷ್ಮಿ",
    addAnimalBreed: "ತಳಿ",
    addAnimalBreedPlaceholder: "ಉದಾ: ಜರ್ಸಿ, ಮುರ್ರಾ",
    addAnimalTag: "ಟ್ಯಾಗ್ ಸಂಖ್ಯೆ",
    addAnimalTagPlaceholder: "ಉದಾ: A001",
    addAnimalSave: "ಸೇರಿಸಿ",
    addAnimalNameRequired: "ಪ್ರಾಣಿಯ ಹೆಸರು ನಮೂದಿಸಿ",
    addAnimalCustomBreed: "ಕಸ್ಟಮ್",
    addAnimalBreedRequired: "ತಳಿ ಆರಿಸಿ",
    milkLogSelectSession: "ಅವಧಿ ಆಯ್ಕೆ ಮಾಡಿ",
    milkLogQuantityLabel: "ಹಾಲಿನ ಪ್ರಮಾಣ (ಲೀಟರ್)",
    milkLogFatLabel: "ಕೊಬ್ಬು % (ಐಚ್ಛಿಕ)",
    milkLogSaveBtn: "ಉಳಿಸಿ",
    milkLogInvalidQty: "ಸರಿಯಾದ ಪ್ರಮಾಣ ನಮೂದಿಸಿ",
    quickActionFever: "ಜ್ವರ",
    quickActionNotEating: "ತಿನ್ನುತ್ತಿಲ್ಲ",
    quickActionInjury: "ಗಾಯ",
    quickActionInHeat: "ಬೆದೆಗೆ ಬಂದಿದೆ",
    healthEventFever: "ಜ್ವರ — Fever",
    healthEventNotEating: "ತಿನ್ನುತ್ತಿಲ್ಲ — Not Eating",
    healthEventLimping: "ಕುಂಟುತ್ತಿದೆ — Limping",
    healthEventDiarrhea: "ಭೇದಿ — Diarrhea",
    healthEventCoughing: "ಕೆಮ್ಮು — Coughing",
    healthEventVetVisit: "ವೈದ್ಯರ ಭೇಟಿ — Vet Visit",
    healthEventVaccination: "ಲಸಿಕೆ — Vaccination",
  },

  ml: {
    ...base,
    appName: "തുളിർ‌ഫാം",
    tagline: "നിങ്ങളുടെ ഫാം, നിങ്ങളുടെ കൈകളിൽ",
    tabAnimals: "എന്റെ മൃഗങ്ങൾ", tabHelp: "സഹായം", tabMoney: "പണം", tabToday: "ഇന്ന്",
    animals: "മൃഗങ്ങൾ", addAnimal: "മൃഗം ചേർക്കുക", noAnimals: "മൃഗങ്ങൾ ഇല്ല",
    noAnimalsHint: "+ അമർത്തി മൃഗം ചേർക്കുക",
    filterAll: "എല്ലാം", filterCow: "പശു", filterBuffalo: "എരുമ",
    filterHealthy: "ആരോഗ്യകരം", filterAttention: "ശ്രദ്ധ വേണം", filterCritical: "അടിയന്തര",
    milkLog: "പാൽ രേഖ", milkLogSuccess: "പാൽ രേഖപ്പെടുത്തി!", milkToday: "ഇന്നത്തെ പാൽ",
    milkLogTitle: "പാൽ രേഖപ്പെടുത്തുക", session: "സമയം", morning: "രാവിലെ", evening: "വൈകുന്നേരം",
    quantity: "അളവ് (ലിറ്റർ)", fatPercentage: "കൊഴുപ്പ് % (ഐഛിക)", save: "സേവ്", cancel: "റദ്ദ്",
    health: "ആരോഗ്യം", healthy: "ആരോഗ്യകരം", attention: "ശ്രദ്ധ വേണം", critical: "അടിയന്തര",
    income: "വരുമാനം", expense: "ചെലവ്", profit: "ലാഭം", loss: "നഷ്ടം",
    totalIncome: "മൊത്തം വരുമാനം", totalExpense: "മൊത്തം ചെലവ്",
    addIncome: "വരുമാനം ചേർക്കുക", addExpense: "ചെലവ് ചേർക്കുക",
    today: "ഇന്ന്", goodMorning: "ശുഭ പ്രഭാതം, കർഷക!", goodAfternoon: "ശുഭ ഉച്ച",
    goodEvening: "ശുഭ സന്ധ്യ", goodNight: "ശുഭ രാത്രി, കർഷക!",
    tasks: "ജോലികൾ", allTasksDone: "എല്ലാ ജോലികളും പൂർത്തി!", progress: "ഇന്നത്തെ പ്രഗതി",
    help: "പ്രശ്നം & സഹായം", sosButton: "എന്തെങ്കിലും തെറ്റായോ?", sosSub: "അടിയന്തര സഹായത്തിന് അമർത്തുക",
    symptoms: "ലക്ഷണങ്ങൾ തിരഞ്ഞെടുക്കുക", diagnose: "AI ഉപദേശം നേടുക", diagnosing: "AI വിശകലനം ചെയ്യുന്നു...",
    emergency: "അടിയന്തര ബന്ധപ്പെടൽ", callVet: "ഉടൻ ഡോക്ടറെ വിളിക്കുക", speak: "കേൾക്കുക", stop: "നിർത്തുക",
    profile: "എന്റെ പ്രൊഫൈൽ", farmerName: "കർഷകന്റെ പേര്", village: "ഗ്രാമം", district: "ജില്ല",
    phone: "ഫോൺ നമ്പർ", totalAnimals: "ആകെ മൃഗങ്ങൾ", language: "ഭാഷ",
    logout: "ലോഗ് ഔട്ട്", editProfile: "എഡിറ്റ്", saveProfile: "പ്രൊഫൈൽ സേവ്",
    login: "ലോഗിൻ", signup: "രജിസ്ട്രേഷൻ",
    loginTitle: "തുളിർ‌ഫാമിലേക്ക് സ്വാഗതം!", loginSub: "നിങ്ങളുടെ മൊബൈൽ നമ്പർ നൽകുക",
    signupTitle: "പ്രൊഫൈൽ പൂർത്തിയാക്കുക", signupSub: "നിങ്ങളെ കുറിച്ച് പറയൂ",
    sendOtp: "OTP അയയ്ക്കുക",
    verifyOtp: "OTP സ്ഥിരീകരിക്കുക",
    otpSentTo: "OTP അയച്ചിരിക്കുന്നു",
    enterOtp: "6-അക്ക OTP നൽകുക",
    resendOtp: "OTP വീണ്ടും അയയ്ക്കുക",
    resendIn: "വീണ്ടും അയക്കൂ",
    seconds: "സെക്കൻഡ്",
    otpExpiry: "OTP 5 മിനിറ്റിൽ കാലഹരണപ്പെടും",
    wrongOtp: "തെറ്റായ OTP",
    otpVerified: "സ്ഥിരീകരിച്ചു!",
    namePlaceholder: "പേര് (ഉദാ: രാജൻ)",
    villagePlaceholder: "ഗ്രാമം",
    districtPlaceholder: "ജില്ല",
    phonePlaceholder: "10-അക്ക മൊബൈൽ നമ്പർ",
    farmNamePlaceholder: "ഫാമിന്റെ പേര് (ഐഛിക)",
    noAccount: "പുതിയതോ?", haveAccount: "ഇതിനകം അംഗമോ?",
    createAccount: "പുതിയ അക്കൗണ്ട്", skip: "ഇപ്പോൾ വേണ്ട",
    continueBtn: "തുടരുക",
    required: "ഇത് ആവശ്യമാണ്",
    invalidPhone: "ശരിയായ 10-അക്ക മൊബൈൽ നമ്പർ നൽകുക",
    success: "വിജയം", error: "പിഴവ്", networkError: "നെറ്റ്‌വർക്ക് പിഴവ്",
    sync: "സേവ് ചെയ്തു", syncing: "സേവ് ചെയ്യുന്നു...", offline: "ഓഫ്‌ലൈൻ",
    demoOtpNote: "Demo OTP (പരീക്ഷണം മാത്രം)",
    newUser: "പുതിയ കർഷക? പ്രൊഫൈൽ ഉണ്ടാക്കൂ",
    existingUser: "ഇതിനകം അംഗമോ? ലോഗിൻ ആകൂ",
    welcomeBack: "തിരിച്ചു സ്വാഗതം",
    step1of3: "ഘട്ടം 1/3", step2of3: "ഘട്ടം 2/3", step3of3: "ഘട്ടം 3/3",
    verifying: "സ്ഥിരീകരിക്കുന്നു...",
    sending: "അയക്കുന്നു...",
    herdTab: "കൂട്ടം", breedingTab: "പ്രജനനം", vaccinesTab: "കുത്തിവയ്പ്പ്",
    myAnimalsTitle: "എന്റെ മൃഗങ്ങൾ", animalsCountSuffix: "മൃഗങ്ങൾ",
    breedingMgmt: "പ്രജനന മാനേജ്‌മെന്റ്", logEvent: "സംഭവം രേഖ",
    noEvents: "രേഖ ഇല്ല", pregnantLabel: "ഗർഭം", calvingExpected: "ഈനൽ തീയതി:",
    daysAgoSuffix: " ദിവസം മുൻ", overdueLabel: "കാലഹരണം", daysLabel: "ദിവസം",
    addAnimalsFirst: "മൃഗങ്ങൾ ചേർക്കൂ", vaccinationSchedule: "കുത്തിവയ്പ്പ് ഷെഡ്യൂൾ",
    upcomingOverdue: "⏰ വരുന്ന / കാലഹരണ",
    recentlyAdministered: "✅ അടുത്തിടെ നൽകിയത്",
    noUpcomingVaccines: "വരുന്ന കുത്തിവയ്പ്പ് ഇല്ല",
    scheduleVaccineBtn: "+ കുത്തിവയ്പ്പ് ഷെഡ്യൂൾ",
    scheduledDateLabel: "നിശ്ചിത തീയതി:", givenDateLabel: "നൽകിയ തീയതി:",
    nextDueLabel: "അടുത്ത:", markDoneBtn: "ചെയ്തു",
    vaccineMarkTitle: "കുത്തിവയ്പ്പ് ചെയ്തോ?",
    vaccineMarkBody: "ഇന്ന് നൽകിയതായി രേഖ ചേർക്കണോ?", yes: "അതേ",
    todayAlerts: "ഇന്നത്തെ അലർട്ടുകൾ", urgentLabel: "അടിയന്തര", highLabel: "പ്രധാനം",
    milkDropAlert: "പാൽ കുറവ് അലർട്ട്", milkDropSuffix: "കുറഞ്ഞു",
    todayPrefix: "ഇന്ന്:", avgPrefix: "ശരാശരി:",
    diagnoseTab: "രോഗ നിർണ്ണയം", gauguruTab: "GauGuru AI", emergencyTab: "അടിയന്തര",
    helpTitle: "പ്രശ്നം & സഹായം", aiDairyAssistant: "AI ഡയറി സഹായി",
    whichAnimal: "ഏത് മൃഗം? (ഐഛിക)", additionalNotes: "കൂടുതൽ കുറിപ്പ്... (ഐഛിക)",
    callNow: "ഉടൻ വിളിക്കൂ!", firstAidTips: "പ്രഥമ ചികിത്സ നുറുങ്ങുകൾ",
    emergencySosBtn: "എന്തെങ്കിലും തെറ്റോ?", emergencySosSub: "അടിയന്തര സഹായത്തിന് അമർത്തുക",
    quickQuestions: "⚡ വേഗ ചോദ്യങ്ങൾ", gauguruSubtitle: "24/7 ഡയറി വിദഗ്ദ്ധൻ",
    chatPlaceholder: "GauGuru ചോദിക്കൂ...", clearChat: "മായ്ക്കൂ",
    thinking: "ചിന്തിക്കുന്നു...", errorMsg: "ക്ഷമിക്കൂ, പിഴവ് സംഭവിച്ചു. വീണ്ടും ശ്രമിക്കൂ.",
    financeTitle: "ധനകാര്യം", incomeTab: "വരുമാനം", expenseTab: "ചെലവുകൾ", inventoryTab: "ശേഖരം",
    sevenDayFinancials: "7 ദിവസ ധനകാര്യം", totalInventoryValue: "ആകെ ശേഖര മൂല്യം",
    lowStockItems: "സ്റ്റോക്ക് കുറഞ്ഞ ഇനങ്ങൾ", noInventory: "ശേഖരം ഇല്ല",
    addFirstItem: "+ ആദ്യ ഇനം ചേർക്കൂ", deleteConfirmTitle: "നീക്കണോ?",
    deleteConfirmBtn: "നീക്കൂ", deleteItemBodyPrefix: "നീക്കൂ",
    herdStatus: "കൂട്ടത്തിന്റെ നില", morningTasks: "രാവിലത്തെ ജോലികൾ", eveningTasks: "വൈകുന്നേര ജോലികൾ",
    loadingTasks: "ജോലികൾ ലോഡ് ആകുന്നു...", reminders: "ഓർമ്മപ്പെടുത്തൽ",
    remindersSet: "ഓർമ്മപ്പെടുത്തൽ സജ്ജം!", savedLabel: "സേവ് ചെയ്തു",
    savingLabel: "സേവ് ചെയ്യുന്നു...", expenseBreakdown: "ചെലവ് വർഗ്ഗങ്ങൾ",
    animalDetailHealth: "ആരോഗ്യ നില",
    animalDetailMilkLog: "പാൽ രേഖ",
    animalDetailHealthNote: "ആരോഗ്യ കുറിപ്പ്",
    animalDetailMilkHistory: "7 ദിവസ പാൽ ചരിത്രം",
    animalDetailHealthHistory: "ആരോഗ്യ ചരിത്രം",
    animalDetailRecentMilk: "സമീപകാല പാൽ രേഖകൾ",
    animalDetailNoNotes: "കുറിപ്പുകൾ ഇല്ല — മുകളിൽ 'ആരോഗ്യ കുറിപ്പ്' അമർത്തുക",
    animalDetailNoMilk: "രേഖകൾ ഇല്ല",
    animalDetailTagPrefix: "ടാഗ്: #",
    animalDetailDeleteTitle: "മൃഗത്തെ നീക്കം ചെയ്യുക",
    animalDetailDeleteBody: "{name} നീക്കം ചെയ്യണോ?",
    animalDetailDeleteConfirm: "നീക്കം",
    animalDetailDeleteCancel: "വേണ്ട",
    animalDetailPhotoTitle: "ഫോട്ടോ എടുക്കൂ",
    animalDetailPhotoBody: "ഫോട്ടോ എടുക്കൂ അല്ലെങ്കിൽ ഗ്യാലറിയിൽ നിന്ന് തിരഞ്ഞെടുക്കൂ",
    animalDetailCamera: "📷 ക്യാമറ",
    animalDetailGallery: "🖼 ഗ്യാലറി",
    animalDetailPermissionNeeded: "അനുമതി ആവശ്യമാണ്",
    animalDetailCameraPermission: "ക്യാമറ ആക്സസ് അനുവദിക്കൂ",
    animalDetailGalleryPermission: "ഗ്യാലറി ആക്സസ് അനുവദിക്കൂ",
    animalDetailNotFound: "മൃഗം കണ്ടെത്തിയില്ല",
    animalDetailGoBack: "തിരിച്ചു പോകൂ",
    animalDetailAddHealthNote: "ആരോഗ്യ കുറിപ്പ് ചേർക്കൂ",
    animalDetailSelectSymptom: "ലക്ഷണം/സംഭവം തിരഞ്ഞെടുക്കൂ",
    typeCow: "പശു",
    typeBuffalo: "എരുമ",
    typeCalf: "കിടാവ്",
    addAnimalTitle: "പുതിയ മൃഗം ചേർക്കൂ",
    addAnimalSelectType: "തരം തിരഞ്ഞെടുക്കൂ",
    addAnimalName: "പേര് *",
    addAnimalNamePlaceholder: "ഉദാ: ലക്ഷ്മി",
    addAnimalBreed: "ഇനം",
    addAnimalBreedPlaceholder: "ഉദാ: ജേഴ്സി, മുർറ",
    addAnimalTag: "ടാഗ് നമ്പർ",
    addAnimalTagPlaceholder: "ഉദാ: A001",
    addAnimalSave: "ചേർക്കൂ",
    addAnimalNameRequired: "മൃഗത്തിന്റെ പേര് നൽകൂ",
    addAnimalCustomBreed: "കസ്റ്റം",
    addAnimalBreedRequired: "ജാതി തിരഞ്ഞെടുക്കൂ",
    milkLogSelectSession: "സെഷൻ തിരഞ്ഞെടുക്കൂ",
    milkLogQuantityLabel: "പാൽ അളവ് (ലിറ്റർ)",
    milkLogFatLabel: "കൊഴുപ്പ് % (ഐഛിക)",
    milkLogSaveBtn: "സേവ് ചെയ്യൂ",
    milkLogInvalidQty: "ശരിയായ അളവ് നൽകൂ",
    quickActionFever: "പനി",
    quickActionNotEating: "തിന്നുന്നില്ല",
    quickActionInjury: "പരിക്ക്",
    quickActionInHeat: "മദി വന്നു",
    healthEventFever: "പനി — Fever",
    healthEventNotEating: "തിന്നുന്നില്ല — Not Eating",
    healthEventLimping: "മുടന്തുന്നു — Limping",
    healthEventDiarrhea: "വയറിളക്കം — Diarrhea",
    healthEventCoughing: "ചുമ — Coughing",
    healthEventVetVisit: "ഡോക്ടർ സന്ദർശനം — Vet Visit",
    healthEventVaccination: "കുത്തിവയ്പ്പ് — Vaccination",
  },

  hi: {
    ...base,
    appName: "थुलिर फार्म",
    tagline: "आपका फार्म, आपके हाथ में",
    tabAnimals: "मेरे पशु", tabHelp: "मदद", tabMoney: "पैसा", tabToday: "आज",
    animals: "पशु", addAnimal: "पशु जोड़ें", noAnimals: "कोई पशु नहीं",
    noAnimalsHint: "+ दबाएं और पशु जोड़ें",
    filterAll: "सभी", filterCow: "गाय", filterBuffalo: "भैंस",
    filterHealthy: "स्वस्थ", filterAttention: "ध्यान दें", filterCritical: "गंभीर",
    milkLog: "दूध दर्ज", milkLogSuccess: "दूध दर्ज हो गया!", milkToday: "आज का दूध",
    milkLogTitle: "दूध दर्ज करें", session: "समय", morning: "सुबह", evening: "शाम",
    quantity: "मात्रा (लीटर)", fatPercentage: "वसा % (वैकल्पिक)", save: "सेव करें", cancel: "रद्द",
    health: "स्वास्थ्य", healthy: "स्वस्थ", attention: "ध्यान दें", critical: "गंभीर",
    income: "आय", expense: "व्यय", profit: "लाभ", loss: "हानि",
    totalIncome: "कुल आय", totalExpense: "कुल व्यय",
    addIncome: "आय जोड़ें", addExpense: "व्यय जोड़ें",
    today: "आज", goodMorning: "सुप्रभात, किसान!", goodAfternoon: "नमस्कार",
    goodEvening: "शुभ संध्या", goodNight: "शुभ रात्रि, किसान!",
    tasks: "कार्य", allTasksDone: "सभी काम पूरे!", progress: "आज की प्रगति",
    help: "समस्या और मदद", sosButton: "कुछ गलत है?", sosSub: "आपातकाल के लिए दबाएं",
    symptoms: "लक्षण चुनें", diagnose: "AI सलाह लें", diagnosing: "AI जांच रहा है...",
    emergency: "आपातकालीन संपर्क", callVet: "तुरंत पशु डॉक्टर बुलाएं", speak: "सुनें", stop: "रोकें",
    profile: "मेरी प्रोफ़ाइल", farmerName: "किसान का नाम", village: "गाँव", district: "जिला",
    phone: "फ़ोन नंबर", totalAnimals: "कुल पशु", language: "भाषा",
    logout: "लॉगआउट", editProfile: "बदलें", saveProfile: "प्रोफ़ाइल सेव करें",
    login: "लॉगिन", signup: "साइन अप",
    loginTitle: "थुलिर फार्म में स्वागत!", loginSub: "अपना मोबाइल नंबर दर्ज करें",
    signupTitle: "अपनी प्रोफ़ाइल बनाएं", signupSub: "अपने बारे में बताएं",
    sendOtp: "OTP भेजें",
    verifyOtp: "OTP जाँचें",
    otpSentTo: "OTP भेजा गया",
    enterOtp: "6-अंकों का OTP दर्ज करें",
    resendOtp: "OTP फिर से भेजें",
    resendIn: "फिर से भेजें",
    seconds: "सेकंड",
    otpExpiry: "OTP 5 मिनट में समाप्त हो जाएगा",
    wrongOtp: "गलत OTP",
    otpVerified: "सत्यापित!",
    namePlaceholder: "नाम (जैसे: रामलाल)",
    villagePlaceholder: "गाँव",
    districtPlaceholder: "जिला",
    phonePlaceholder: "10 अंकों का मोबाइल नंबर",
    farmNamePlaceholder: "फार्म का नाम (वैकल्पिक)",
    noAccount: "नए हैं?", haveAccount: "पहले से सदस्य?",
    createAccount: "नया खाता", skip: "अभी छोड़ें",
    continueBtn: "जारी रखें",
    required: "यह ज़रूरी है",
    invalidPhone: "सही 10 अंकों का मोबाइल नंबर दर्ज करें",
    success: "सफलता", error: "त्रुटि", networkError: "नेटवर्क त्रुटि",
    sync: "सेव हो गया", syncing: "सेव हो रहा है...", offline: "ऑफ़लाइन",
    demoOtpNote: "Demo OTP (परीक्षण केवल)",
    newUser: "नए किसान? प्रोफ़ाइल बनाएं",
    existingUser: "पहले से सदस्य? लॉगिन करें",
    welcomeBack: "वापस स्वागत है",
    step1of3: "चरण 1/3", step2of3: "चरण 2/3", step3of3: "चरण 3/3",
    verifying: "जाँच रहा है...",
    sending: "भेज रहा है...",
    herdTab: "झुंड", breedingTab: "प्रजनन", vaccinesTab: "टीके",
    myAnimalsTitle: "मेरे पशु", animalsCountSuffix: "पशु",
    breedingMgmt: "प्रजनन प्रबंधन", logEvent: "घटना दर्ज करें",
    noEvents: "कोई रिकॉर्ड नहीं", pregnantLabel: "गर्भवती", calvingExpected: "ब्याने की तारीख:",
    daysAgoSuffix: " दिन पहले", overdueLabel: "अवधि पूरी", daysLabel: "दिन",
    addAnimalsFirst: "पशु जोड़ें", vaccinationSchedule: "टीकाकरण अनुसूची",
    upcomingOverdue: "⏰ आगामी / अतिदेय",
    recentlyAdministered: "✅ हाल ही में दिए गए",
    noUpcomingVaccines: "कोई आगामी टीके नहीं",
    scheduleVaccineBtn: "+ टीका शेड्यूल करें",
    scheduledDateLabel: "निर्धारित तारीख:", givenDateLabel: "दी गई तारीख:",
    nextDueLabel: "अगला:", markDoneBtn: "हो गया",
    vaccineMarkTitle: "टीका दिया गया?",
    vaccineMarkBody: "आज दिया गया दर्ज करें?", yes: "हाँ",
    todayAlerts: "आज की अलर्ट", urgentLabel: "अत्यावश्यक", highLabel: "महत्वपूर्ण",
    milkDropAlert: "दूध कमी अलर्ट", milkDropSuffix: "कम हो गया",
    todayPrefix: "आज:", avgPrefix: "औसत:",
    diagnoseTab: "रोग निदान", gauguruTab: "GauGuru AI", emergencyTab: "आपातकाल",
    helpTitle: "समस्या और मदद", aiDairyAssistant: "AI डेयरी सहायक",
    whichAnimal: "कौनसा पशु? (वैकल्पिक)", additionalNotes: "अतिरिक्त नोट्स... (वैकल्पिक)",
    callNow: "अभी कॉल करें!", firstAidTips: "प्राथमिक चिकित्सा टिप्स",
    emergencySosBtn: "कुछ गलत है?", emergencySosSub: "आपातकाल के लिए दबाएं",
    quickQuestions: "⚡ त्वरित प्रश्न", gauguruSubtitle: "24/7 डेयरी विशेषज्ञ",
    chatPlaceholder: "GauGuru से पूछें...", clearChat: "साफ करें",
    thinking: "सोच रहा हूँ...", errorMsg: "माफ़ करें, त्रुटि हुई। फिर से प्रयास करें।",
    financeTitle: "वित्त", incomeTab: "आय", expenseTab: "व्यय", inventoryTab: "भंडार",
    sevenDayFinancials: "7 दिन का वित्त", totalInventoryValue: "कुल स्टॉक मूल्य",
    lowStockItems: "कम स्टॉक वाली वस्तुएं", noInventory: "कोई स्टॉक नहीं",
    addFirstItem: "+ पहली वस्तु जोड़ें", deleteConfirmTitle: "हटाएं?",
    deleteConfirmBtn: "हटाएं", deleteItemBodyPrefix: "हटाएं",
    herdStatus: "झुंड की स्थिति", morningTasks: "सुबह के कार्य", eveningTasks: "शाम के कार्य",
    loadingTasks: "कार्य लोड हो रहे हैं...", reminders: "रिमाइंडर",
    remindersSet: "रिमाइंडर सेट हो गए!", savedLabel: "सेव हो गया",
    savingLabel: "सेव हो रहा है...", expenseBreakdown: "व्यय वर्ग",
    animalDetailHealth: "स्वास्थ्य स्थिति",
    animalDetailMilkLog: "दूध दर्ज",
    animalDetailHealthNote: "स्वास्थ्य नोट",
    animalDetailMilkHistory: "7 दिन का दूध इतिहास",
    animalDetailHealthHistory: "स्वास्थ्य इतिहास",
    animalDetailRecentMilk: "हालिया दूध प्रविष्टियाँ",
    animalDetailNoNotes: "कोई नोट नहीं — ऊपर 'स्वास्थ्य नोट' दबाएं",
    animalDetailNoMilk: "कोई प्रविष्टि नहीं",
    animalDetailTagPrefix: "टैग: #",
    animalDetailDeleteTitle: "पशु हटाएं",
    animalDetailDeleteBody: "{name} को हटाना है?",
    animalDetailDeleteConfirm: "हटाएं",
    animalDetailDeleteCancel: "नहीं",
    animalDetailPhotoTitle: "फोटो लें",
    animalDetailPhotoBody: "फोटो लें या गैलरी से चुनें",
    animalDetailCamera: "📷 कैमरा",
    animalDetailGallery: "🖼 गैलरी",
    animalDetailPermissionNeeded: "अनुमति आवश्यक",
    animalDetailCameraPermission: "कैमरा एक्सेस दें",
    animalDetailGalleryPermission: "गैलरी एक्सेस दें",
    animalDetailNotFound: "पशु नहीं मिला",
    animalDetailGoBack: "वापस जाएं",
    animalDetailAddHealthNote: "स्वास्थ्य नोट जोड़ें",
    animalDetailSelectSymptom: "लक्षण/घटना चुनें",
    typeCow: "गाय",
    typeBuffalo: "भैंस",
    typeCalf: "बछड़ा",
    addAnimalTitle: "नया पशु जोड़ें",
    addAnimalSelectType: "प्रकार चुनें",
    addAnimalName: "नाम *",
    addAnimalNamePlaceholder: "जैसे: लक्ष्मी",
    addAnimalBreed: "नस्ल",
    addAnimalBreedPlaceholder: "जैसे: जर्सी, मुर्रा",
    addAnimalTag: "टैग नंबर",
    addAnimalTagPlaceholder: "जैसे: A001",
    addAnimalSave: "जोड़ें",
    addAnimalNameRequired: "पशु का नाम दर्ज करें",
    addAnimalCustomBreed: "कस्टम",
    addAnimalBreedRequired: "नस्ल चुनें",
    milkLogSelectSession: "सत्र चुनें",
    milkLogQuantityLabel: "दूध मात्रा (लीटर)",
    milkLogFatLabel: "वसा % (वैकल्पिक)",
    milkLogSaveBtn: "सेव करें",
    milkLogInvalidQty: "सही मात्रा दर्ज करें",
    quickActionFever: "बुखार",
    quickActionNotEating: "नहीं खा रहा",
    quickActionInjury: "चोट",
    quickActionInHeat: "गर्मी में",
    healthEventFever: "बुखार — Fever",
    healthEventNotEating: "नहीं खा रहा — Not Eating",
    healthEventLimping: "लंगड़ा रहा — Limping",
    healthEventDiarrhea: "दस्त — Diarrhea",
    healthEventCoughing: "खांसी — Coughing",
    healthEventVetVisit: "डॉक्टर की विज़िट — Vet Visit",
    healthEventVaccination: "टीका — Vaccination",
  },
};

export type Translations = T;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: T;
}

const LanguageContext = createContext<LanguageContextType | null>(null);
const LANGUAGE_KEY = "thulirafarm_language";

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("ta");

  useEffect(() => {
    AsyncStorage.getItem(LANGUAGE_KEY).then((stored) => {
      if (stored && stored in translations) {
        setLanguageState(stored as Language);
      }
    });
  }, []);

  const setLanguage = useCallback(async (lang: Language) => {
    setLanguageState(lang);
    await AsyncStorage.setItem(LANGUAGE_KEY, lang);
  }, []);

  const t = translations[language];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
