import AsyncStorage from "@react-native-async-storage/async-storage";
import React, { createContext, useCallback, useContext, useEffect, useState } from "react";

export type Language = "ta" | "te" | "kn" | "ml" | "hi" | "en";

export const LANGUAGE_NAMES: Record<Language, string> = {
  ta: "தமிழ்",
  te: "తెలుగు",
  kn: "ಕನ್ನಡ",
  ml: "മലയാളം",
  hi: "हिंदी",
  en: "English",
};

export const LANGUAGE_NATIVE: Record<Language, { name: string; flag: string; english: string }> = {
  ta: { name: "தமிழ்", flag: "🏛️", english: "Tamil" },
  te: { name: "తెలుగు", flag: "🌺", english: "Telugu" },
  kn: { name: "ಕನ್ನಡ", flag: "🌿", english: "Kannada" },
  ml: { name: "മലയാളം", flag: "🌴", english: "Malayalam" },
  hi: { name: "हिंदी", flag: "🇮🇳", english: "Hindi" },
  en: { name: "English", flag: "🔤", english: "English" },
};

const base = {
  appName: "ThulirFarm",
  tagline: "Your Farm, In Your Hands",
  tabAnimals: "My Animals", tabHelp: "Help", tabMoney: "Money", tabToday: "Today",
  animals: "Animals", addAnimal: "Add Animal", noAnimals: "No Animals",
  noAnimalsHint: "Tap + to add your first animal",
  filterAll: "All", filterCow: "Cow 🐄", filterBuffalo: "Buffalo 🐃",
  filterHealthy: "Healthy", filterAttention: "Attention", filterCritical: "Critical",
  milkLog: "Log Milk", milkLogSuccess: "Milk logged!", milkToday: "Today's Milk",
  milkLogTitle: "Log Milk Entry", session: "Session", morning: "Morning", evening: "Evening",
  quantity: "Quantity (Litres)", fatPercentage: "Fat % (optional)", save: "Save", cancel: "Cancel",
  health: "Health", healthy: "Healthy", attention: "Needs Attention", critical: "Critical",
  income: "Income", expense: "Expense", profit: "Profit", loss: "Loss",
  totalIncome: "Total Income", totalExpense: "Total Expense",
  addIncome: "Add Income", addExpense: "Add Expense",
  today: "Today", goodMorning: "Good Morning, Farmer!", goodAfternoon: "Good Afternoon",
  goodEvening: "Good Evening", goodNight: "Good Night, Farmer!",
  tasks: "Tasks", allTasksDone: "All tasks done! 🎉", progress: "Today's Progress",
  help: "Problems & Help", sosButton: "Something Wrong?", sosSub: "Tap to call for emergency",
  symptoms: "Select Symptoms", diagnose: "Get AI Advice", diagnosing: "AI is analyzing...",
  emergency: "Emergency Contacts", callVet: "Call Vet Immediately", speak: "Listen", stop: "Stop",
  profile: "My Profile", farmerName: "Farmer Name", village: "Village", district: "District",
  phone: "Phone Number", totalAnimals: "Total Animals", language: "Language",
  logout: "Log Out", editProfile: "Edit", saveProfile: "Save Profile",
  login: "Login", signup: "Sign Up",
  loginTitle: "Welcome to ThulirFarm", loginSub: "Enter your mobile number",
  signupTitle: "Complete Your Profile", signupSub: "Tell us about yourself",
  sendOtp: "Send OTP",
  verifyOtp: "Verify OTP",
  otpSentTo: "OTP sent to",
  enterOtp: "Enter 6-digit OTP",
  resendOtp: "Resend OTP",
  resendIn: "Resend in",
  seconds: "sec",
  otpExpiry: "OTP valid for 5 minutes",
  wrongOtp: "Incorrect OTP",
  otpVerified: "Verified!",
  namePlaceholder: "Your name (e.g. Murugan)",
  villagePlaceholder: "Village name",
  districtPlaceholder: "District",
  phonePlaceholder: "10-digit mobile number",
  farmNamePlaceholder: "Your farm's name (optional)",
  noAccount: "New to ThulirFarm?",
  haveAccount: "Already registered?",
  createAccount: "Create account",
  skip: "Skip for now",
  continueBtn: "Continue",
  required: "This field is required",
  invalidPhone: "Enter a valid 10-digit mobile number",
  success: "Success", error: "Error", networkError: "Network error",
  sync: "Saved", syncing: "Saving...", offline: "Offline",
  voice: "Voice", voiceTitle: "Voice Command", voiceSub: "Speak in Tamil or English",
  voiceHint: "Press the button to start", listening: "Listening...", processing: "Processing...",
  sampleCommands: "Sample Commands", speakAgain: "Speak Again",
  settingsTitle: "Settings", notifications: "Notifications",
  notifEnabled: "Notifications enabled", enableNotif: "Enable reminders",
  demoOtpNote: "Demo OTP (testing only)",
  newUser: "New farmer? Create profile",
  existingUser: "Already a member? Log in",
  welcomeBack: "Welcome back",
  step1of3: "Step 1/3", step2of3: "Step 2/3", step3of3: "Step 3/3",
  verifying: "Verifying...",
  sending: "Sending...",
};

type T = typeof base;

const translations: Record<Language, T> = {
  en: { ...base },

  ta: {
    ...base,
    appName: "துளிர்பண்ணை",
    tagline: "உங்கள் பண்ணை, உங்கள் கையில்",
    tabAnimals: "என் மாடுகள்", tabHelp: "உதவி", tabMoney: "பணம்", tabToday: "இன்று",
    animals: "மாடுகள்", addAnimal: "மாடு சேர்", noAnimals: "மாடுகள் இல்லை",
    noAnimalsHint: "+ பொத்தானை அழுத்தி மாடு சேர்க்கவும்",
    filterAll: "அனைத்தும்", filterCow: "பசு 🐄", filterBuffalo: "எருமை 🐃",
    filterHealthy: "ஆரோக்கியம்", filterAttention: "கவனிக்கவும்", filterCritical: "அவசரம்",
    milkLog: "பால் பதிவு", milkLogSuccess: "பால் பதிவு ஆனது!", milkToday: "இன்று பால்",
    milkLogTitle: "பால் பதிவு செய்யவும்", session: "நேரம்", morning: "காலை", evening: "மாலை",
    quantity: "அளவு (லிட்டர்)", fatPercentage: "கொழுப்பு % (விருப்பம்)", save: "சேமி", cancel: "ரத்து",
    health: "உடல் நிலை", healthy: "ஆரோக்கியம்", attention: "கவனிக்கவும்", critical: "அவசரம்",
    income: "வருமானம்", expense: "செலவு", profit: "லாபம்", loss: "நஷ்டம்",
    totalIncome: "மொத்த வருமானம்", totalExpense: "மொத்த செலவு",
    addIncome: "வருமானம் சேர்", addExpense: "செலவு சேர்",
    today: "இன்று", goodMorning: "காலை வணக்கம், விவசாயி!", goodAfternoon: "மதிய வணக்கம்",
    goodEvening: "மாலை வணக்கம்", goodNight: "இரவு வணக்கம், விவசாயி!",
    tasks: "பணிகள்", allTasksDone: "அனைத்து பணிகளும் முடிந்தது! 🎉", progress: "இன்றைய முன்னேற்றம்",
    help: "பிரச்சனை & உதவி", sosButton: "ஏதாவது தவறா?", sosSub: "அழுத்தி அவசர உதவி பெறவும்",
    symptoms: "அறிகுறிகள் தேர்வு", diagnose: "AI ஆலோசனை பெறவும்", diagnosing: "AI பகுப்பாய்கிறது...",
    emergency: "அவசர தொடர்பு", callVet: "உடனே மருத்துவர் அழைக்கவும்", speak: "கேளு", stop: "நிறுத்து",
    profile: "என் சுயவிவரம்", farmerName: "விவசாயி பெயர்", village: "கிராமம்", district: "மாவட்டம்",
    phone: "தொலைபேசி", totalAnimals: "மொத்த மாடுகள்", language: "மொழி",
    logout: "வெளியேறு", editProfile: "திருத்து", saveProfile: "சுயவிவரம் சேமி",
    login: "உள்நுழை", signup: "பதிவு செய்",
    loginTitle: "துளிர்பண்ணைக்கு வரவேற்கிறோம்!", loginSub: "உங்கள் கைபேசி எண் உள்ளிடவும்",
    signupTitle: "உங்கள் சுயவிவரம் நிரப்பவும்", signupSub: "உங்களைப் பற்றி சொல்லுங்கள்",
    sendOtp: "OTP அனுப்பவும்",
    verifyOtp: "OTP சரிபார்க்கவும்",
    otpSentTo: "OTP அனுப்பப்பட்டது",
    enterOtp: "6 இலக்க OTP உள்ளிடவும்",
    resendOtp: "மீண்டும் OTP அனுப்பவும்",
    resendIn: "மீண்டும் அனுப்ப",
    seconds: "நொடி",
    otpExpiry: "OTP 5 நிமிடங்களில் காலாவதியாகும்",
    wrongOtp: "தவறான OTP",
    otpVerified: "சரிபார்க்கப்பட்டது!",
    namePlaceholder: "பெயர் (எ.கா: முருகன்)",
    villagePlaceholder: "கிராமம் (எ.கா: தஞ்சாவூர்)",
    districtPlaceholder: "மாவட்டம்",
    phonePlaceholder: "கைபேசி எண் (10 இலக்கம்)",
    farmNamePlaceholder: "பண்ணை பெயர் (விருப்பம்)",
    noAccount: "புதியதா?", haveAccount: "ஏற்கனவே உறுப்பினரா?",
    createAccount: "புதிய கணக்கு", skip: "இப்போது வேண்டாம்",
    continueBtn: "தொடர்க",
    required: "இது கட்டாயம்",
    invalidPhone: "சரியான கைபேசி எண் உள்ளிடவும்",
    success: "வெற்றி", error: "பிழை", networkError: "இணைப்பு பிழை",
    sync: "சேமிக்கப்பட்டது", syncing: "சேமிக்கிறது", offline: "offline",
    voice: "குரல்", voiceTitle: "குரல் கட்டளை", voiceSub: "தமிழ் அல்லது ஆங்கிலத்தில் பேசவும்",
    voiceHint: "மேலே பொத்தானை அழுத்தவும்", listening: "கேட்கிறேன்...", processing: "புரிந்துகொள்கிறேன்...",
    sampleCommands: "உதாரண கட்டளைகள்", speakAgain: "மீண்டும் சொல்",
    settingsTitle: "அமைப்புகள்", notifications: "அறிவிப்புகள்",
    notifEnabled: "அறிவிப்புகள் தயார்", enableNotif: "நினைவூட்டல் இயக்கு",
    demoOtpNote: "Demo OTP (சோதனைக்கு மட்டும்)",
    newUser: "புதிய விவசாயி? சுயவிவரம் உருவாக்கவும்",
    existingUser: "ஏற்கனவே உறுப்பினரா? உள்நுழையவும்",
    welcomeBack: "மீண்டும் வரவேற்கிறோம்",
    step1of3: "படி 1/3", step2of3: "படி 2/3", step3of3: "படி 3/3",
    verifying: "சரிபார்க்கிறது...",
    sending: "அனுப்புகிறது...",
  },

  te: {
    ...base,
    appName: "థులిర్‌ఫార్మ్",
    tagline: "మీ పొలం, మీ చేతిలో",
    tabAnimals: "నా జంతువులు", tabHelp: "సహాయం", tabMoney: "డబ్బు", tabToday: "నేడు",
    animals: "జంతువులు", addAnimal: "జంతువు జోడించు", noAnimals: "జంతువులు లేవు",
    noAnimalsHint: "+ నొక్కి జంతువు జోడించండి",
    filterAll: "అన్నీ", filterCow: "ఆవు 🐄", filterBuffalo: "గేదె 🐃",
    filterHealthy: "ఆరోగ్యకరమైన", filterAttention: "శ్రద్ధ అవసరం", filterCritical: "అత్యవసరం",
    milkLog: "పాలు నమోదు", milkLogSuccess: "పాలు నమోదయ్యాయి!", milkToday: "నేడు పాలు",
    milkLogTitle: "పాలు నమోదు చేయండి", session: "సమయం", morning: "ఉదయం", evening: "సాయంత్రం",
    quantity: "పరిమాణం (లీటర్లు)", fatPercentage: "కొవ్వు % (ఐచ్ఛికం)", save: "సేవ్", cancel: "రద్దు",
    health: "ఆరోగ్యం", healthy: "ఆరోగ్యకరమైన", attention: "శ్రద్ధ అవసరం", critical: "అత్యవసరం",
    income: "ఆదాయం", expense: "వ్యయం", profit: "లాభం", loss: "నష్టం",
    totalIncome: "మొత్తం ఆదాయం", totalExpense: "మొత్తం వ్యయం",
    addIncome: "ఆదాయం జోడించు", addExpense: "వ్యయం జోడించు",
    today: "నేడు", goodMorning: "శుభోదయం, రైతు!", goodAfternoon: "శుభమధ్యాహ్నం",
    goodEvening: "శుభసాయంత్రం", goodNight: "శుభరాత్రి, రైతు!",
    tasks: "పనులు", allTasksDone: "అన్ని పనులు పూర్తయ్యాయి! 🎉", progress: "నేటి పురోగతి",
    help: "సమస్య & సహాయం", sosButton: "ఏదైనా తప్పు జరిగిందా?", sosSub: "అత్యవసర సహాయం కోసం నొక్కండి",
    symptoms: "లక్షణాలు ఎంచుకోండి", diagnose: "AI సలహా పొందండి", diagnosing: "AI విశ్లేషిస్తోంది...",
    emergency: "అత్యవసర సంప్రదింపులు", callVet: "వెంటనే వైద్యుని పిలవండి", speak: "వినండి", stop: "ఆపు",
    profile: "నా వివరాలు", farmerName: "రైతు పేరు", village: "గ్రామం", district: "జిల్లా",
    phone: "ఫోన్ నంబర్", totalAnimals: "మొత్తం జంతువులు", language: "భాష",
    logout: "లాగ్అవుట్", editProfile: "సవరించు", saveProfile: "వివరాలు సేవ్ చేయి",
    login: "లాగిన్", signup: "నమోదు",
    loginTitle: "థులిర్‌ఫార్మ్‌కు స్వాగతం!", loginSub: "మీ మొబైల్ నంబర్ నమోదు చేయండి",
    signupTitle: "మీ వివరాలు నమోదు చేయండి", signupSub: "మీ గురించి చెప్పండి",
    sendOtp: "OTP పంపండి",
    verifyOtp: "OTP ధృవీకరించండి",
    otpSentTo: "OTP పంపబడింది",
    enterOtp: "6-అంకె OTP నమోదు చేయండి",
    resendOtp: "OTP మళ్ళీ పంపండి",
    resendIn: "మళ్ళీ పంపు",
    seconds: "సెకన్లు",
    otpExpiry: "OTP 5 నిమిషాలలో గడువు ముగుస్తుంది",
    wrongOtp: "తప్పు OTP",
    otpVerified: "ధృవీకరించబడింది!",
    namePlaceholder: "పేరు (ఉదా: రాములు)",
    villagePlaceholder: "గ్రామం",
    districtPlaceholder: "జిల్లా",
    phonePlaceholder: "10-అంకె మొబైల్ నంబర్",
    farmNamePlaceholder: "పొలం పేరు (ఐచ్ఛికం)",
    noAccount: "కొత్తగా వచ్చారా?", haveAccount: "ఇప్పటికే సభ్యులా?",
    createAccount: "కొత్త ఖాతా", skip: "ఇప్పుడు వద్దు",
    continueBtn: "కొనసాగించు",
    required: "ఇది తప్పనిసరి",
    invalidPhone: "సరైన 10-అంకె మొబైల్ నంబర్ నమోదు చేయండి",
    success: "విజయం", error: "లోపం", networkError: "నెట్‌వర్క్ లోపం",
    sync: "సేవ్ చేయబడింది", syncing: "సేవ్ అవుతోంది...", offline: "ఆఫ్‌లైన్",
    demoOtpNote: "Demo OTP (పరీక్ష మాత్రమే)",
    newUser: "కొత్త రైతు? ప్రొఫైల్ తయారు చేయండి",
    existingUser: "ఇప్పటికే సభ్యులా? లాగిన్ అవ్వండి",
    welcomeBack: "తిరిగి స్వాగతం",
    step1of3: "దశ 1/3", step2of3: "దశ 2/3", step3of3: "దశ 3/3",
    verifying: "ధృవీకరిస్తోంది...",
    sending: "పంపుతోంది...",
  },

  kn: {
    ...base,
    appName: "ತುಳಿರ್‌ಫಾರ್ಮ್",
    tagline: "ನಿಮ್ಮ ತೋಟ, ನಿಮ್ಮ ಕೈಯಲ್ಲಿ",
    tabAnimals: "ನನ್ನ ಪ್ರಾಣಿಗಳು", tabHelp: "ಸಹಾಯ", tabMoney: "ಹಣ", tabToday: "ಇಂದು",
    animals: "ಪ್ರಾಣಿಗಳು", addAnimal: "ಪ್ರಾಣಿ ಸೇರಿಸಿ", noAnimals: "ಪ್ರಾಣಿಗಳಿಲ್ಲ",
    noAnimalsHint: "+ ಒತ್ತಿ ಪ್ರಾಣಿ ಸೇರಿಸಿ",
    filterAll: "ಎಲ್ಲ", filterCow: "ಹಸು 🐄", filterBuffalo: "ಕೋಣ 🐃",
    filterHealthy: "ಆರೋಗ್ಯಕರ", filterAttention: "ಗಮನ ಬೇಕು", filterCritical: "ತುರ್ತು",
    milkLog: "ಹಾಲು ದಾಖಲು", milkLogSuccess: "ಹಾಲು ದಾಖಲಾಯಿತು!", milkToday: "ಇಂದಿನ ಹಾಲು",
    milkLogTitle: "ಹಾಲು ದಾಖಲಿಸಿ", session: "ಸಮಯ", morning: "ಬೆಳಿಗ್ಗೆ", evening: "ಸಂಜೆ",
    quantity: "ಪ್ರಮಾಣ (ಲೀಟರ್)", fatPercentage: "ಕೊಬ್ಬು % (ಐಚ್ಛಿಕ)", save: "ಉಳಿಸಿ", cancel: "ರದ್ದು",
    health: "ಆರೋಗ್ಯ", healthy: "ಆರೋಗ್ಯಕರ", attention: "ಗಮನ ಬೇಕು", critical: "ತುರ್ತು",
    income: "ಆದಾಯ", expense: "ವೆಚ್ಚ", profit: "ಲಾಭ", loss: "ನಷ್ಟ",
    totalIncome: "ಒಟ್ಟು ಆದಾಯ", totalExpense: "ಒಟ್ಟು ವೆಚ್ಚ",
    addIncome: "ಆದಾಯ ಸೇರಿಸಿ", addExpense: "ವೆಚ್ಚ ಸೇರಿಸಿ",
    today: "ಇಂದು", goodMorning: "ಶುಭೋದಯ, ರೈತ!", goodAfternoon: "ಶುಭ ಮಧ್ಯಾಹ್ನ",
    goodEvening: "ಶುಭ ಸಂಜೆ", goodNight: "ಶುಭ ರಾತ್ರಿ, ರೈತ!",
    tasks: "ಕೆಲಸಗಳು", allTasksDone: "ಎಲ್ಲ ಕೆಲಸ ಮುಗಿಯಿತು! 🎉", progress: "ಇಂದಿನ ಪ್ರಗತಿ",
    help: "ಸಮಸ್ಯೆ & ಸಹಾಯ", sosButton: "ಏನಾದರೂ ತಪ್ಪಾಯಿತೇ?", sosSub: "ತುರ್ತು ಸಹಾಯಕ್ಕೆ ಒತ್ತಿ",
    symptoms: "ರೋಗಲಕ್ಷಣಗಳು ಆರಿಸಿ", diagnose: "AI ಸಲಹೆ ಪಡೆಯಿರಿ", diagnosing: "AI ವಿಶ್ಲೇಷಿಸುತ್ತಿದೆ...",
    emergency: "ತುರ್ತು ಸಂಪರ್ಕಗಳು", callVet: "ತಕ್ಷಣ ಪಶು ವೈದ್ಯರನ್ನು ಕರೆಯಿರಿ", speak: "ಕೇಳಿ", stop: "ನಿಲ್ಲಿಸಿ",
    profile: "ನನ್ನ ಪ್ರೊಫೈಲ್", farmerName: "ರೈತರ ಹೆಸರು", village: "ಗ್ರಾಮ", district: "ಜಿಲ್ಲೆ",
    phone: "ಫೋನ್ ಸಂಖ್ಯೆ", totalAnimals: "ಒಟ್ಟು ಪ್ರಾಣಿಗಳು", language: "ಭಾಷೆ",
    logout: "ಲಾಗ್ ಔಟ್", editProfile: "ತಿದ್ದಿ", saveProfile: "ಪ್ರೊಫೈಲ್ ಉಳಿಸಿ",
    login: "ಲಾಗಿನ್", signup: "ನೋಂದಣಿ",
    loginTitle: "ತುಳಿರ್‌ಫಾರ್ಮ್‌ಗೆ ಸ್ವಾಗತ!", loginSub: "ನಿಮ್ಮ ಮೊಬೈಲ್ ನಂಬರ್ ನಮೂದಿಸಿ",
    signupTitle: "ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಪೂರ್ಣಗೊಳಿಸಿ", signupSub: "ನಿಮ್ಮ ಬಗ್ಗೆ ಹೇಳಿ",
    sendOtp: "OTP ಕಳುಹಿಸಿ",
    verifyOtp: "OTP ದೃಢೀಕರಿಸಿ",
    otpSentTo: "OTP ಕಳುಹಿಸಲಾಗಿದೆ",
    enterOtp: "6-ಅಂಕಿ OTP ನಮೂದಿಸಿ",
    resendOtp: "OTP ಮತ್ತೆ ಕಳುಹಿಸಿ",
    resendIn: "ಮತ್ತೆ ಕಳುಹಿಸು",
    seconds: "ಸೆಕೆಂಡ್",
    otpExpiry: "OTP 5 ನಿಮಿಷಗಳಲ್ಲಿ ಅವಧಿ ಮೀರುತ್ತದೆ",
    wrongOtp: "ತಪ್ಪು OTP",
    otpVerified: "ದೃಢೀಕರಿಸಲಾಗಿದೆ!",
    namePlaceholder: "ಹೆಸರು (ಉದಾ: ರಾಮಪ್ಪ)",
    villagePlaceholder: "ಗ್ರಾಮ",
    districtPlaceholder: "ಜಿಲ್ಲೆ",
    phonePlaceholder: "10-ಅಂಕಿ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
    farmNamePlaceholder: "ತೋಟದ ಹೆಸರು (ಐಚ್ಛಿಕ)",
    noAccount: "ಹೊಸಬರೇ?", haveAccount: "ಈಗಾಗಲೇ ಸದಸ್ಯರೇ?",
    createAccount: "ಹೊಸ ಖಾತೆ", skip: "ಈಗ ಬೇಡ",
    continueBtn: "ಮುಂದುವರಿಸಿ",
    required: "ಇದು ಅಗತ್ಯ",
    invalidPhone: "ಸರಿಯಾದ 10-ಅಂಕಿ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ",
    success: "ಯಶಸ್ಸು", error: "ದೋಷ", networkError: "ನೆಟ್‌ವರ್ಕ್ ದೋಷ",
    sync: "ಉಳಿಸಲಾಗಿದೆ", syncing: "ಉಳಿಸುತ್ತಿದೆ...", offline: "ಆಫ್‌ಲೈನ್",
    demoOtpNote: "Demo OTP (ಪರೀಕ್ಷೆಗಾಗಿ ಮಾತ್ರ)",
    newUser: "ಹೊಸ ರೈತ? ಪ್ರೊಫೈಲ್ ತಯಾರಿಸಿ",
    existingUser: "ಈಗಾಗಲೇ ಸದಸ್ಯರೇ? ಲಾಗಿನ್ ಅಗಿ",
    welcomeBack: "ಮತ್ತೆ ಸ್ವಾಗತ",
    step1of3: "ಹಂತ 1/3", step2of3: "ಹಂತ 2/3", step3of3: "ಹಂತ 3/3",
    verifying: "ದೃಢೀಕರಿಸುತ್ತಿದೆ...",
    sending: "ಕಳುಹಿಸುತ್ತಿದೆ...",
  },

  ml: {
    ...base,
    appName: "തുളിർ‌ഫാം",
    tagline: "നിങ്ങളുടെ ഫാം, നിങ്ങളുടെ കൈകളിൽ",
    tabAnimals: "എന്റെ മൃഗങ്ങൾ", tabHelp: "സഹായം", tabMoney: "പണം", tabToday: "ഇന്ന്",
    animals: "മൃഗങ്ങൾ", addAnimal: "മൃഗം ചേർക്കുക", noAnimals: "മൃഗങ്ങൾ ഇല്ല",
    noAnimalsHint: "+ അമർത്തി മൃഗം ചേർക്കുക",
    filterAll: "എല്ലാം", filterCow: "പശു 🐄", filterBuffalo: "എരുമ 🐃",
    filterHealthy: "ആരോഗ്യകരം", filterAttention: "ശ്രദ്ധ വേണം", filterCritical: "അടിയന്തര",
    milkLog: "പാൽ രേഖ", milkLogSuccess: "പാൽ രേഖപ്പെടുത്തി!", milkToday: "ഇന്നത്തെ പാൽ",
    milkLogTitle: "പാൽ രേഖപ്പെടുത്തുക", session: "സമയം", morning: "രാവിലെ", evening: "വൈകുന്നേരം",
    quantity: "അളവ് (ലിറ്റർ)", fatPercentage: "കൊഴുപ്പ് % (ഐഛിക)", save: "സേവ്", cancel: "റദ്ദ്",
    health: "ആരോഗ്യം", healthy: "ആരോഗ്യകരം", attention: "ശ്രദ്ധ വേണം", critical: "അടിയന്തര",
    income: "വരുമാനം", expense: "ചെലവ്", profit: "ലാഭം", loss: "നഷ്ടം",
    totalIncome: "മൊത്തം വരുമാനം", totalExpense: "മൊത്തം ചെലവ്",
    addIncome: "വരുമാനം ചേർക്കുക", addExpense: "ചെലവ് ചേർക്കുക",
    today: "ഇന്ന്", goodMorning: "ശുഭ പ്രഭാതം, കർഷക!", goodAfternoon: "ശുഭ ഉച്ച",
    goodEvening: "ശുഭ സന്ധ്യ", goodNight: "ശുഭ രാത്രി, കർഷക!",
    tasks: "ജോലികൾ", allTasksDone: "എല്ലാ ജോലികളും പൂർത്തി! 🎉", progress: "ഇന്നത്തെ പ്രഗതി",
    help: "പ്രശ്നം & സഹായം", sosButton: "എന്തെങ്കിലും തെറ്റായോ?", sosSub: "അടിയന്തര സഹായത്തിന് അമർത്തുക",
    symptoms: "ലക്ഷണങ്ങൾ തിരഞ്ഞെടുക്കുക", diagnose: "AI ഉപദേശം നേടുക", diagnosing: "AI വിശകലനം ചെയ്യുന്നു...",
    emergency: "അടിയന്തര ബന്ധപ്പെടൽ", callVet: "ഉടൻ ഡോക്ടറെ വിളിക്കുക", speak: "കേൾക്കുക", stop: "നിർത്തുക",
    profile: "എന്റെ പ്രൊഫൈൽ", farmerName: "കർഷകന്റെ പേര്", village: "ഗ്രാമം", district: "ജില്ല",
    phone: "ഫോൺ നമ്പർ", totalAnimals: "ആകെ മൃഗങ്ങൾ", language: "ഭാഷ",
    logout: "ലോഗ് ഔട്ട്", editProfile: "എഡിറ്റ്", saveProfile: "പ്രൊഫൈൽ സേവ്",
    login: "ലോഗിൻ", signup: "രജിസ്ട്രേഷൻ",
    loginTitle: "തുളിർ‌ഫാമിലേക്ക് സ്വാഗതം!", loginSub: "നിങ്ങളുടെ മൊബൈൽ നമ്പർ നൽകുക",
    signupTitle: "പ്രൊഫൈൽ പൂർത്തിയാക്കുക", signupSub: "നിങ്ങളെ കുറിച്ച് പറയൂ",
    sendOtp: "OTP അയയ്ക്കുക",
    verifyOtp: "OTP സ്ഥിരീകരിക്കുക",
    otpSentTo: "OTP അയച്ചിരിക്കുന്നു",
    enterOtp: "6-അക്ക OTP നൽകുക",
    resendOtp: "OTP വീണ്ടും അയയ്ക്കുക",
    resendIn: "വീണ്ടും അയക്കൂ",
    seconds: "സെക്കൻഡ്",
    otpExpiry: "OTP 5 മിനിറ്റിൽ കാലഹരണപ്പെടും",
    wrongOtp: "തെറ്റായ OTP",
    otpVerified: "സ്ഥിരീകരിച്ചു!",
    namePlaceholder: "പേര് (ഉദാ: രാജൻ)",
    villagePlaceholder: "ഗ്രാമം",
    districtPlaceholder: "ജില്ല",
    phonePlaceholder: "10-അക്ക മൊബൈൽ നമ്പർ",
    farmNamePlaceholder: "ഫാമിന്റെ പേര് (ഐഛിക)",
    noAccount: "പുതിയതോ?", haveAccount: "ഇതിനകം അംഗമോ?",
    createAccount: "പുതിയ അക്കൗണ്ട്", skip: "ഇപ്പോൾ വേണ്ട",
    continueBtn: "തുടരുക",
    required: "ഇത് ആവശ്യമാണ്",
    invalidPhone: "ശരിയായ 10-അക്ക മൊബൈൽ നമ്പർ നൽകുക",
    success: "വിജയം", error: "പിഴവ്", networkError: "നെറ്റ്‌വർക്ക് പിഴവ്",
    sync: "സേവ് ചെയ്തു", syncing: "സേവ് ചെയ്യുന്നു...", offline: "ഓഫ്‌ലൈൻ",
    demoOtpNote: "Demo OTP (പരീക്ഷണം മാത്രം)",
    newUser: "പുതിയ കർഷക? പ്രൊഫൈൽ ഉണ്ടാക്കൂ",
    existingUser: "ഇതിനകം അംഗമോ? ലോഗിൻ ആകൂ",
    welcomeBack: "തിരിച്ചു സ്വാഗതം",
    step1of3: "ഘട്ടം 1/3", step2of3: "ഘട്ടം 2/3", step3of3: "ഘട്ടം 3/3",
    verifying: "സ്ഥിരീകരിക്കുന്നു...",
    sending: "അയക്കുന്നു...",
  },

  hi: {
    ...base,
    appName: "थुलिर फार्म",
    tagline: "आपका फार्म, आपके हाथ में",
    tabAnimals: "मेरे पशु", tabHelp: "मदद", tabMoney: "पैसा", tabToday: "आज",
    animals: "पशु", addAnimal: "पशु जोड़ें", noAnimals: "कोई पशु नहीं",
    noAnimalsHint: "+ दबाएं और पशु जोड़ें",
    filterAll: "सभी", filterCow: "गाय 🐄", filterBuffalo: "भैंस 🐃",
    filterHealthy: "स्वस्थ", filterAttention: "ध्यान दें", filterCritical: "गंभीर",
    milkLog: "दूध दर्ज", milkLogSuccess: "दूध दर्ज हो गया!", milkToday: "आज का दूध",
    milkLogTitle: "दूध दर्ज करें", session: "समय", morning: "सुबह", evening: "शाम",
    quantity: "मात्रा (लीटर)", fatPercentage: "वसा % (वैकल्पिक)", save: "सेव करें", cancel: "रद्द",
    health: "स्वास्थ्य", healthy: "स्वस्थ", attention: "ध्यान दें", critical: "गंभीर",
    income: "आय", expense: "व्यय", profit: "लाभ", loss: "हानि",
    totalIncome: "कुल आय", totalExpense: "कुल व्यय",
    addIncome: "आय जोड़ें", addExpense: "व्यय जोड़ें",
    today: "आज", goodMorning: "सुप्रभात, किसान!", goodAfternoon: "नमस्कार",
    goodEvening: "शुभ संध्या", goodNight: "शुभ रात्रि, किसान!",
    tasks: "कार्य", allTasksDone: "सभी काम पूरे! 🎉", progress: "आज की प्रगति",
    help: "समस्या और मदद", sosButton: "कुछ गलत है?", sosSub: "आपातकाल के लिए दबाएं",
    symptoms: "लक्षण चुनें", diagnose: "AI सलाह लें", diagnosing: "AI जांच रहा है...",
    emergency: "आपातकालीन संपर्क", callVet: "तुरंत पशु डॉक्टर बुलाएं", speak: "सुनें", stop: "रोकें",
    profile: "मेरी प्रोफ़ाइल", farmerName: "किसान का नाम", village: "गाँव", district: "जिला",
    phone: "फ़ोन नंबर", totalAnimals: "कुल पशु", language: "भाषा",
    logout: "लॉगआउट", editProfile: "बदलें", saveProfile: "प्रोफ़ाइल सेव करें",
    login: "लॉगिन", signup: "साइन अप",
    loginTitle: "थुलिर फार्म में स्वागत!", loginSub: "अपना मोबाइल नंबर दर्ज करें",
    signupTitle: "अपनी प्रोफ़ाइल बनाएं", signupSub: "अपने बारे में बताएं",
    sendOtp: "OTP भेजें",
    verifyOtp: "OTP जाँचें",
    otpSentTo: "OTP भेजा गया",
    enterOtp: "6-अंकों का OTP दर्ज करें",
    resendOtp: "OTP फिर से भेजें",
    resendIn: "फिर से भेजें",
    seconds: "सेकंड",
    otpExpiry: "OTP 5 मिनट में समाप्त हो जाएगा",
    wrongOtp: "गलत OTP",
    otpVerified: "सत्यापित!",
    namePlaceholder: "नाम (जैसे: रामलाल)",
    villagePlaceholder: "गाँव",
    districtPlaceholder: "जिला",
    phonePlaceholder: "10 अंकों का मोबाइल नंबर",
    farmNamePlaceholder: "फार्म का नाम (वैकल्पिक)",
    noAccount: "नए हैं?", haveAccount: "पहले से सदस्य?",
    createAccount: "नया खाता", skip: "अभी छोड़ें",
    continueBtn: "जारी रखें",
    required: "यह ज़रूरी है",
    invalidPhone: "सही 10 अंकों का मोबाइल नंबर दर्ज करें",
    success: "सफलता", error: "त्रुटि", networkError: "नेटवर्क त्रुटि",
    sync: "सेव हो गया", syncing: "सेव हो रहा है...", offline: "ऑफ़लाइन",
    demoOtpNote: "Demo OTP (परीक्षण केवल)",
    newUser: "नए किसान? प्रोफ़ाइल बनाएं",
    existingUser: "पहले से सदस्य? लॉगिन करें",
    welcomeBack: "वापस स्वागत है",
    step1of3: "चरण 1/3", step2of3: "चरण 2/3", step3of3: "चरण 3/3",
    verifying: "जाँच रहा है...",
    sending: "भेज रहा है...",
  },
};

export type Translations = T;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: T;
}

const LanguageContext = createContext<LanguageContextType | null>(null);
const LANGUAGE_KEY = "thulirafarm_language";

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("ta");

  useEffect(() => {
    AsyncStorage.getItem(LANGUAGE_KEY).then((stored) => {
      if (stored && stored in translations) {
        setLanguageState(stored as Language);
      }
    });
  }, []);

  const setLanguage = useCallback(async (lang: Language) => {
    setLanguageState(lang);
    await AsyncStorage.setItem(LANGUAGE_KEY, lang);
  }, []);

  const t = translations[language];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
